// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/transaction/ent/predicate"
	"github.com/yucai/server/internal/transaction/ent/transaction"
	"github.com/yucai/server/internal/transaction/ent/transactionentry"
)

// TransactionEntryUpdate is the builder for updating TransactionEntry entities.
type TransactionEntryUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionEntryMutation
}

// Where appends a list predicates to the TransactionEntryUpdate builder.
func (teu *TransactionEntryUpdate) Where(ps ...predicate.TransactionEntry) *TransactionEntryUpdate {
	teu.mutation.Where(ps...)
	return teu
}

// SetTransactionID sets the "transaction_id" field.
func (teu *TransactionEntryUpdate) SetTransactionID(u uuid.UUID) *TransactionEntryUpdate {
	teu.mutation.SetTransactionID(u)
	return teu
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (teu *TransactionEntryUpdate) SetNillableTransactionID(u *uuid.UUID) *TransactionEntryUpdate {
	if u != nil {
		teu.SetTransactionID(*u)
	}
	return teu
}

// SetChartOfAccountCode sets the "chart_of_account_code" field.
func (teu *TransactionEntryUpdate) SetChartOfAccountCode(s string) *TransactionEntryUpdate {
	teu.mutation.SetChartOfAccountCode(s)
	return teu
}

// SetNillableChartOfAccountCode sets the "chart_of_account_code" field if the given value is not nil.
func (teu *TransactionEntryUpdate) SetNillableChartOfAccountCode(s *string) *TransactionEntryUpdate {
	if s != nil {
		teu.SetChartOfAccountCode(*s)
	}
	return teu
}

// SetDebitCents sets the "debit_cents" field.
func (teu *TransactionEntryUpdate) SetDebitCents(i int64) *TransactionEntryUpdate {
	teu.mutation.ResetDebitCents()
	teu.mutation.SetDebitCents(i)
	return teu
}

// SetNillableDebitCents sets the "debit_cents" field if the given value is not nil.
func (teu *TransactionEntryUpdate) SetNillableDebitCents(i *int64) *TransactionEntryUpdate {
	if i != nil {
		teu.SetDebitCents(*i)
	}
	return teu
}

// AddDebitCents adds i to the "debit_cents" field.
func (teu *TransactionEntryUpdate) AddDebitCents(i int64) *TransactionEntryUpdate {
	teu.mutation.AddDebitCents(i)
	return teu
}

// SetCreditCents sets the "credit_cents" field.
func (teu *TransactionEntryUpdate) SetCreditCents(i int64) *TransactionEntryUpdate {
	teu.mutation.ResetCreditCents()
	teu.mutation.SetCreditCents(i)
	return teu
}

// SetNillableCreditCents sets the "credit_cents" field if the given value is not nil.
func (teu *TransactionEntryUpdate) SetNillableCreditCents(i *int64) *TransactionEntryUpdate {
	if i != nil {
		teu.SetCreditCents(*i)
	}
	return teu
}

// AddCreditCents adds i to the "credit_cents" field.
func (teu *TransactionEntryUpdate) AddCreditCents(i int64) *TransactionEntryUpdate {
	teu.mutation.AddCreditCents(i)
	return teu
}

// SetNote sets the "note" field.
func (teu *TransactionEntryUpdate) SetNote(s string) *TransactionEntryUpdate {
	teu.mutation.SetNote(s)
	return teu
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (teu *TransactionEntryUpdate) SetNillableNote(s *string) *TransactionEntryUpdate {
	if s != nil {
		teu.SetNote(*s)
	}
	return teu
}

// ClearNote clears the value of the "note" field.
func (teu *TransactionEntryUpdate) ClearNote() *TransactionEntryUpdate {
	teu.mutation.ClearNote()
	return teu
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (teu *TransactionEntryUpdate) SetTransaction(t *Transaction) *TransactionEntryUpdate {
	return teu.SetTransactionID(t.ID)
}

// Mutation returns the TransactionEntryMutation object of the builder.
func (teu *TransactionEntryUpdate) Mutation() *TransactionEntryMutation {
	return teu.mutation
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (teu *TransactionEntryUpdate) ClearTransaction() *TransactionEntryUpdate {
	teu.mutation.ClearTransaction()
	return teu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (teu *TransactionEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, teu.sqlSave, teu.mutation, teu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (teu *TransactionEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := teu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (teu *TransactionEntryUpdate) Exec(ctx context.Context) error {
	_, err := teu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (teu *TransactionEntryUpdate) ExecX(ctx context.Context) {
	if err := teu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (teu *TransactionEntryUpdate) check() error {
	if v, ok := teu.mutation.DebitCents(); ok {
		if err := transactionentry.DebitCentsValidator(v); err != nil {
			return &ValidationError{Name: "debit_cents", err: fmt.Errorf(`ent: validator failed for field "TransactionEntry.debit_cents": %w`, err)}
		}
	}
	if v, ok := teu.mutation.CreditCents(); ok {
		if err := transactionentry.CreditCentsValidator(v); err != nil {
			return &ValidationError{Name: "credit_cents", err: fmt.Errorf(`ent: validator failed for field "TransactionEntry.credit_cents": %w`, err)}
		}
	}
	if teu.mutation.TransactionCleared() && len(teu.mutation.TransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransactionEntry.transaction"`)
	}
	return nil
}

func (teu *TransactionEntryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := teu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactionentry.Table, transactionentry.Columns, sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeUUID))
	if ps := teu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := teu.mutation.ChartOfAccountCode(); ok {
		_spec.SetField(transactionentry.FieldChartOfAccountCode, field.TypeString, value)
	}
	if value, ok := teu.mutation.DebitCents(); ok {
		_spec.SetField(transactionentry.FieldDebitCents, field.TypeInt64, value)
	}
	if value, ok := teu.mutation.AddedDebitCents(); ok {
		_spec.AddField(transactionentry.FieldDebitCents, field.TypeInt64, value)
	}
	if value, ok := teu.mutation.CreditCents(); ok {
		_spec.SetField(transactionentry.FieldCreditCents, field.TypeInt64, value)
	}
	if value, ok := teu.mutation.AddedCreditCents(); ok {
		_spec.AddField(transactionentry.FieldCreditCents, field.TypeInt64, value)
	}
	if value, ok := teu.mutation.Note(); ok {
		_spec.SetField(transactionentry.FieldNote, field.TypeString, value)
	}
	if teu.mutation.NoteCleared() {
		_spec.ClearField(transactionentry.FieldNote, field.TypeString)
	}
	if teu.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionentry.TransactionTable,
			Columns: []string{transactionentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := teu.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionentry.TransactionTable,
			Columns: []string{transactionentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, teu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	teu.mutation.done = true
	return n, nil
}

// TransactionEntryUpdateOne is the builder for updating a single TransactionEntry entity.
type TransactionEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionEntryMutation
}

// SetTransactionID sets the "transaction_id" field.
func (teuo *TransactionEntryUpdateOne) SetTransactionID(u uuid.UUID) *TransactionEntryUpdateOne {
	teuo.mutation.SetTransactionID(u)
	return teuo
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (teuo *TransactionEntryUpdateOne) SetNillableTransactionID(u *uuid.UUID) *TransactionEntryUpdateOne {
	if u != nil {
		teuo.SetTransactionID(*u)
	}
	return teuo
}

// SetChartOfAccountCode sets the "chart_of_account_code" field.
func (teuo *TransactionEntryUpdateOne) SetChartOfAccountCode(s string) *TransactionEntryUpdateOne {
	teuo.mutation.SetChartOfAccountCode(s)
	return teuo
}

// SetNillableChartOfAccountCode sets the "chart_of_account_code" field if the given value is not nil.
func (teuo *TransactionEntryUpdateOne) SetNillableChartOfAccountCode(s *string) *TransactionEntryUpdateOne {
	if s != nil {
		teuo.SetChartOfAccountCode(*s)
	}
	return teuo
}

// SetDebitCents sets the "debit_cents" field.
func (teuo *TransactionEntryUpdateOne) SetDebitCents(i int64) *TransactionEntryUpdateOne {
	teuo.mutation.ResetDebitCents()
	teuo.mutation.SetDebitCents(i)
	return teuo
}

// SetNillableDebitCents sets the "debit_cents" field if the given value is not nil.
func (teuo *TransactionEntryUpdateOne) SetNillableDebitCents(i *int64) *TransactionEntryUpdateOne {
	if i != nil {
		teuo.SetDebitCents(*i)
	}
	return teuo
}

// AddDebitCents adds i to the "debit_cents" field.
func (teuo *TransactionEntryUpdateOne) AddDebitCents(i int64) *TransactionEntryUpdateOne {
	teuo.mutation.AddDebitCents(i)
	return teuo
}

// SetCreditCents sets the "credit_cents" field.
func (teuo *TransactionEntryUpdateOne) SetCreditCents(i int64) *TransactionEntryUpdateOne {
	teuo.mutation.ResetCreditCents()
	teuo.mutation.SetCreditCents(i)
	return teuo
}

// SetNillableCreditCents sets the "credit_cents" field if the given value is not nil.
func (teuo *TransactionEntryUpdateOne) SetNillableCreditCents(i *int64) *TransactionEntryUpdateOne {
	if i != nil {
		teuo.SetCreditCents(*i)
	}
	return teuo
}

// AddCreditCents adds i to the "credit_cents" field.
func (teuo *TransactionEntryUpdateOne) AddCreditCents(i int64) *TransactionEntryUpdateOne {
	teuo.mutation.AddCreditCents(i)
	return teuo
}

// SetNote sets the "note" field.
func (teuo *TransactionEntryUpdateOne) SetNote(s string) *TransactionEntryUpdateOne {
	teuo.mutation.SetNote(s)
	return teuo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (teuo *TransactionEntryUpdateOne) SetNillableNote(s *string) *TransactionEntryUpdateOne {
	if s != nil {
		teuo.SetNote(*s)
	}
	return teuo
}

// ClearNote clears the value of the "note" field.
func (teuo *TransactionEntryUpdateOne) ClearNote() *TransactionEntryUpdateOne {
	teuo.mutation.ClearNote()
	return teuo
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (teuo *TransactionEntryUpdateOne) SetTransaction(t *Transaction) *TransactionEntryUpdateOne {
	return teuo.SetTransactionID(t.ID)
}

// Mutation returns the TransactionEntryMutation object of the builder.
func (teuo *TransactionEntryUpdateOne) Mutation() *TransactionEntryMutation {
	return teuo.mutation
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (teuo *TransactionEntryUpdateOne) ClearTransaction() *TransactionEntryUpdateOne {
	teuo.mutation.ClearTransaction()
	return teuo
}

// Where appends a list predicates to the TransactionEntryUpdate builder.
func (teuo *TransactionEntryUpdateOne) Where(ps ...predicate.TransactionEntry) *TransactionEntryUpdateOne {
	teuo.mutation.Where(ps...)
	return teuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (teuo *TransactionEntryUpdateOne) Select(field string, fields ...string) *TransactionEntryUpdateOne {
	teuo.fields = append([]string{field}, fields...)
	return teuo
}

// Save executes the query and returns the updated TransactionEntry entity.
func (teuo *TransactionEntryUpdateOne) Save(ctx context.Context) (*TransactionEntry, error) {
	return withHooks(ctx, teuo.sqlSave, teuo.mutation, teuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (teuo *TransactionEntryUpdateOne) SaveX(ctx context.Context) *TransactionEntry {
	node, err := teuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (teuo *TransactionEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := teuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (teuo *TransactionEntryUpdateOne) ExecX(ctx context.Context) {
	if err := teuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (teuo *TransactionEntryUpdateOne) check() error {
	if v, ok := teuo.mutation.DebitCents(); ok {
		if err := transactionentry.DebitCentsValidator(v); err != nil {
			return &ValidationError{Name: "debit_cents", err: fmt.Errorf(`ent: validator failed for field "TransactionEntry.debit_cents": %w`, err)}
		}
	}
	if v, ok := teuo.mutation.CreditCents(); ok {
		if err := transactionentry.CreditCentsValidator(v); err != nil {
			return &ValidationError{Name: "credit_cents", err: fmt.Errorf(`ent: validator failed for field "TransactionEntry.credit_cents": %w`, err)}
		}
	}
	if teuo.mutation.TransactionCleared() && len(teuo.mutation.TransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransactionEntry.transaction"`)
	}
	return nil
}

func (teuo *TransactionEntryUpdateOne) sqlSave(ctx context.Context) (_node *TransactionEntry, err error) {
	if err := teuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactionentry.Table, transactionentry.Columns, sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeUUID))
	id, ok := teuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransactionEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := teuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactionentry.FieldID)
		for _, f := range fields {
			if !transactionentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transactionentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := teuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := teuo.mutation.ChartOfAccountCode(); ok {
		_spec.SetField(transactionentry.FieldChartOfAccountCode, field.TypeString, value)
	}
	if value, ok := teuo.mutation.DebitCents(); ok {
		_spec.SetField(transactionentry.FieldDebitCents, field.TypeInt64, value)
	}
	if value, ok := teuo.mutation.AddedDebitCents(); ok {
		_spec.AddField(transactionentry.FieldDebitCents, field.TypeInt64, value)
	}
	if value, ok := teuo.mutation.CreditCents(); ok {
		_spec.SetField(transactionentry.FieldCreditCents, field.TypeInt64, value)
	}
	if value, ok := teuo.mutation.AddedCreditCents(); ok {
		_spec.AddField(transactionentry.FieldCreditCents, field.TypeInt64, value)
	}
	if value, ok := teuo.mutation.Note(); ok {
		_spec.SetField(transactionentry.FieldNote, field.TypeString, value)
	}
	if teuo.mutation.NoteCleared() {
		_spec.ClearField(transactionentry.FieldNote, field.TypeString)
	}
	if teuo.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionentry.TransactionTable,
			Columns: []string{transactionentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := teuo.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transactionentry.TransactionTable,
			Columns: []string{transactionentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TransactionEntry{config: teuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, teuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	teuo.mutation.done = true
	return _node, nil
}
