// Code generated by ent, DO NOT EDIT.

package goalprogresssnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the goalprogresssnapshot type in the database.
	Label = "goal_progress_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldGoalID holds the string denoting the goal_id field in the database.
	FieldGoalID = "goal_id"
	// FieldSnapshotDate holds the string denoting the snapshot_date field in the database.
	FieldSnapshotDate = "snapshot_date"
	// FieldCurrentAmountCents holds the string denoting the current_amount_cents field in the database.
	FieldCurrentAmountCents = "current_amount_cents"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeGoal holds the string denoting the goal edge name in mutations.
	EdgeGoal = "goal"
	// Table holds the table name of the goalprogresssnapshot in the database.
	Table = "goal_progress_snapshots"
	// GoalTable is the table that holds the goal relation/edge.
	GoalTable = "goal_progress_snapshots"
	// GoalInverseTable is the table name for the Goal entity.
	// It exists in this package in order to avoid circular dependency with the "goal" package.
	GoalInverseTable = "goals"
	// GoalColumn is the table column denoting the goal relation/edge.
	GoalColumn = "goal_id"
)

// Columns holds all SQL columns for goalprogresssnapshot fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldGoalID,
	FieldSnapshotDate,
	FieldCurrentAmountCents,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GoalProgressSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByGoalID orders the results by the goal_id field.
func ByGoalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoalID, opts...).ToFunc()
}

// BySnapshotDate orders the results by the snapshot_date field.
func BySnapshotDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotDate, opts...).ToFunc()
}

// ByCurrentAmountCents orders the results by the current_amount_cents field.
func ByCurrentAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentAmountCents, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByGoalField orders the results by goal field.
func ByGoalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoalStep(), sql.OrderByField(field, opts...))
	}
}
func newGoalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GoalTable, GoalColumn),
	)
}
