// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/sync/ent/predicate"
	"github.com/yucai/server/internal/sync/ent/synclog"
)

// SyncLogUpdate is the builder for updating SyncLog entities.
type SyncLogUpdate struct {
	config
	hooks    []Hook
	mutation *SyncLogMutation
}

// Where appends a list predicates to the SyncLogUpdate builder.
func (slu *SyncLogUpdate) Where(ps ...predicate.SyncLog) *SyncLogUpdate {
	slu.mutation.Where(ps...)
	return slu
}

// SetEntityType sets the "entity_type" field.
func (slu *SyncLogUpdate) SetEntityType(s string) *SyncLogUpdate {
	slu.mutation.SetEntityType(s)
	return slu
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (slu *SyncLogUpdate) SetNillableEntityType(s *string) *SyncLogUpdate {
	if s != nil {
		slu.SetEntityType(*s)
	}
	return slu
}

// SetEntityID sets the "entity_id" field.
func (slu *SyncLogUpdate) SetEntityID(u uuid.UUID) *SyncLogUpdate {
	slu.mutation.SetEntityID(u)
	return slu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (slu *SyncLogUpdate) SetNillableEntityID(u *uuid.UUID) *SyncLogUpdate {
	if u != nil {
		slu.SetEntityID(*u)
	}
	return slu
}

// SetOperation sets the "operation" field.
func (slu *SyncLogUpdate) SetOperation(s string) *SyncLogUpdate {
	slu.mutation.SetOperation(s)
	return slu
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (slu *SyncLogUpdate) SetNillableOperation(s *string) *SyncLogUpdate {
	if s != nil {
		slu.SetOperation(*s)
	}
	return slu
}

// SetPayload sets the "payload" field.
func (slu *SyncLogUpdate) SetPayload(b []byte) *SyncLogUpdate {
	slu.mutation.SetPayload(b)
	return slu
}

// SetVersion sets the "version" field.
func (slu *SyncLogUpdate) SetVersion(i int64) *SyncLogUpdate {
	slu.mutation.ResetVersion()
	slu.mutation.SetVersion(i)
	return slu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (slu *SyncLogUpdate) SetNillableVersion(i *int64) *SyncLogUpdate {
	if i != nil {
		slu.SetVersion(*i)
	}
	return slu
}

// AddVersion adds i to the "version" field.
func (slu *SyncLogUpdate) AddVersion(i int64) *SyncLogUpdate {
	slu.mutation.AddVersion(i)
	return slu
}

// SetDeviceID sets the "device_id" field.
func (slu *SyncLogUpdate) SetDeviceID(u uuid.UUID) *SyncLogUpdate {
	slu.mutation.SetDeviceID(u)
	return slu
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (slu *SyncLogUpdate) SetNillableDeviceID(u *uuid.UUID) *SyncLogUpdate {
	if u != nil {
		slu.SetDeviceID(*u)
	}
	return slu
}

// Mutation returns the SyncLogMutation object of the builder.
func (slu *SyncLogUpdate) Mutation() *SyncLogMutation {
	return slu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (slu *SyncLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, slu.sqlSave, slu.mutation, slu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (slu *SyncLogUpdate) SaveX(ctx context.Context) int {
	affected, err := slu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (slu *SyncLogUpdate) Exec(ctx context.Context) error {
	_, err := slu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slu *SyncLogUpdate) ExecX(ctx context.Context) {
	if err := slu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (slu *SyncLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(synclog.Table, synclog.Columns, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeUUID))
	if ps := slu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := slu.mutation.EntityType(); ok {
		_spec.SetField(synclog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := slu.mutation.EntityID(); ok {
		_spec.SetField(synclog.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := slu.mutation.Operation(); ok {
		_spec.SetField(synclog.FieldOperation, field.TypeString, value)
	}
	if value, ok := slu.mutation.Payload(); ok {
		_spec.SetField(synclog.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := slu.mutation.Version(); ok {
		_spec.SetField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := slu.mutation.AddedVersion(); ok {
		_spec.AddField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := slu.mutation.DeviceID(); ok {
		_spec.SetField(synclog.FieldDeviceID, field.TypeUUID, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, slu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synclog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	slu.mutation.done = true
	return n, nil
}

// SyncLogUpdateOne is the builder for updating a single SyncLog entity.
type SyncLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncLogMutation
}

// SetEntityType sets the "entity_type" field.
func (sluo *SyncLogUpdateOne) SetEntityType(s string) *SyncLogUpdateOne {
	sluo.mutation.SetEntityType(s)
	return sluo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (sluo *SyncLogUpdateOne) SetNillableEntityType(s *string) *SyncLogUpdateOne {
	if s != nil {
		sluo.SetEntityType(*s)
	}
	return sluo
}

// SetEntityID sets the "entity_id" field.
func (sluo *SyncLogUpdateOne) SetEntityID(u uuid.UUID) *SyncLogUpdateOne {
	sluo.mutation.SetEntityID(u)
	return sluo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (sluo *SyncLogUpdateOne) SetNillableEntityID(u *uuid.UUID) *SyncLogUpdateOne {
	if u != nil {
		sluo.SetEntityID(*u)
	}
	return sluo
}

// SetOperation sets the "operation" field.
func (sluo *SyncLogUpdateOne) SetOperation(s string) *SyncLogUpdateOne {
	sluo.mutation.SetOperation(s)
	return sluo
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (sluo *SyncLogUpdateOne) SetNillableOperation(s *string) *SyncLogUpdateOne {
	if s != nil {
		sluo.SetOperation(*s)
	}
	return sluo
}

// SetPayload sets the "payload" field.
func (sluo *SyncLogUpdateOne) SetPayload(b []byte) *SyncLogUpdateOne {
	sluo.mutation.SetPayload(b)
	return sluo
}

// SetVersion sets the "version" field.
func (sluo *SyncLogUpdateOne) SetVersion(i int64) *SyncLogUpdateOne {
	sluo.mutation.ResetVersion()
	sluo.mutation.SetVersion(i)
	return sluo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (sluo *SyncLogUpdateOne) SetNillableVersion(i *int64) *SyncLogUpdateOne {
	if i != nil {
		sluo.SetVersion(*i)
	}
	return sluo
}

// AddVersion adds i to the "version" field.
func (sluo *SyncLogUpdateOne) AddVersion(i int64) *SyncLogUpdateOne {
	sluo.mutation.AddVersion(i)
	return sluo
}

// SetDeviceID sets the "device_id" field.
func (sluo *SyncLogUpdateOne) SetDeviceID(u uuid.UUID) *SyncLogUpdateOne {
	sluo.mutation.SetDeviceID(u)
	return sluo
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (sluo *SyncLogUpdateOne) SetNillableDeviceID(u *uuid.UUID) *SyncLogUpdateOne {
	if u != nil {
		sluo.SetDeviceID(*u)
	}
	return sluo
}

// Mutation returns the SyncLogMutation object of the builder.
func (sluo *SyncLogUpdateOne) Mutation() *SyncLogMutation {
	return sluo.mutation
}

// Where appends a list predicates to the SyncLogUpdate builder.
func (sluo *SyncLogUpdateOne) Where(ps ...predicate.SyncLog) *SyncLogUpdateOne {
	sluo.mutation.Where(ps...)
	return sluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sluo *SyncLogUpdateOne) Select(field string, fields ...string) *SyncLogUpdateOne {
	sluo.fields = append([]string{field}, fields...)
	return sluo
}

// Save executes the query and returns the updated SyncLog entity.
func (sluo *SyncLogUpdateOne) Save(ctx context.Context) (*SyncLog, error) {
	return withHooks(ctx, sluo.sqlSave, sluo.mutation, sluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sluo *SyncLogUpdateOne) SaveX(ctx context.Context) *SyncLog {
	node, err := sluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sluo *SyncLogUpdateOne) Exec(ctx context.Context) error {
	_, err := sluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sluo *SyncLogUpdateOne) ExecX(ctx context.Context) {
	if err := sluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sluo *SyncLogUpdateOne) sqlSave(ctx context.Context) (_node *SyncLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(synclog.Table, synclog.Columns, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeUUID))
	id, ok := sluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, synclog.FieldID)
		for _, f := range fields {
			if !synclog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != synclog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sluo.mutation.EntityType(); ok {
		_spec.SetField(synclog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := sluo.mutation.EntityID(); ok {
		_spec.SetField(synclog.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := sluo.mutation.Operation(); ok {
		_spec.SetField(synclog.FieldOperation, field.TypeString, value)
	}
	if value, ok := sluo.mutation.Payload(); ok {
		_spec.SetField(synclog.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := sluo.mutation.Version(); ok {
		_spec.SetField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := sluo.mutation.AddedVersion(); ok {
		_spec.AddField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := sluo.mutation.DeviceID(); ok {
		_spec.SetField(synclog.FieldDeviceID, field.TypeUUID, value)
	}
	_node = &SyncLog{config: sluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synclog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sluo.mutation.done = true
	return _node, nil
}
