// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/sync/ent/predicate"
	"github.com/yucai/server/internal/sync/ent/syncconflict"
)

// SyncConflictUpdate is the builder for updating SyncConflict entities.
type SyncConflictUpdate struct {
	config
	hooks    []Hook
	mutation *SyncConflictMutation
}

// Where appends a list predicates to the SyncConflictUpdate builder.
func (scu *SyncConflictUpdate) Where(ps ...predicate.SyncConflict) *SyncConflictUpdate {
	scu.mutation.Where(ps...)
	return scu
}

// SetEntityType sets the "entity_type" field.
func (scu *SyncConflictUpdate) SetEntityType(s string) *SyncConflictUpdate {
	scu.mutation.SetEntityType(s)
	return scu
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (scu *SyncConflictUpdate) SetNillableEntityType(s *string) *SyncConflictUpdate {
	if s != nil {
		scu.SetEntityType(*s)
	}
	return scu
}

// SetEntityID sets the "entity_id" field.
func (scu *SyncConflictUpdate) SetEntityID(u uuid.UUID) *SyncConflictUpdate {
	scu.mutation.SetEntityID(u)
	return scu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (scu *SyncConflictUpdate) SetNillableEntityID(u *uuid.UUID) *SyncConflictUpdate {
	if u != nil {
		scu.SetEntityID(*u)
	}
	return scu
}

// SetConflictType sets the "conflict_type" field.
func (scu *SyncConflictUpdate) SetConflictType(s string) *SyncConflictUpdate {
	scu.mutation.SetConflictType(s)
	return scu
}

// SetNillableConflictType sets the "conflict_type" field if the given value is not nil.
func (scu *SyncConflictUpdate) SetNillableConflictType(s *string) *SyncConflictUpdate {
	if s != nil {
		scu.SetConflictType(*s)
	}
	return scu
}

// SetServerPayload sets the "server_payload" field.
func (scu *SyncConflictUpdate) SetServerPayload(b []byte) *SyncConflictUpdate {
	scu.mutation.SetServerPayload(b)
	return scu
}

// SetClientPayload sets the "client_payload" field.
func (scu *SyncConflictUpdate) SetClientPayload(b []byte) *SyncConflictUpdate {
	scu.mutation.SetClientPayload(b)
	return scu
}

// SetResolution sets the "resolution" field.
func (scu *SyncConflictUpdate) SetResolution(s string) *SyncConflictUpdate {
	scu.mutation.SetResolution(s)
	return scu
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (scu *SyncConflictUpdate) SetNillableResolution(s *string) *SyncConflictUpdate {
	if s != nil {
		scu.SetResolution(*s)
	}
	return scu
}

// SetResolvedAt sets the "resolved_at" field.
func (scu *SyncConflictUpdate) SetResolvedAt(t time.Time) *SyncConflictUpdate {
	scu.mutation.SetResolvedAt(t)
	return scu
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (scu *SyncConflictUpdate) SetNillableResolvedAt(t *time.Time) *SyncConflictUpdate {
	if t != nil {
		scu.SetResolvedAt(*t)
	}
	return scu
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (scu *SyncConflictUpdate) ClearResolvedAt() *SyncConflictUpdate {
	scu.mutation.ClearResolvedAt()
	return scu
}

// SetUpdatedAt sets the "updated_at" field.
func (scu *SyncConflictUpdate) SetUpdatedAt(t time.Time) *SyncConflictUpdate {
	scu.mutation.SetUpdatedAt(t)
	return scu
}

// Mutation returns the SyncConflictMutation object of the builder.
func (scu *SyncConflictUpdate) Mutation() *SyncConflictMutation {
	return scu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (scu *SyncConflictUpdate) Save(ctx context.Context) (int, error) {
	scu.defaults()
	return withHooks(ctx, scu.sqlSave, scu.mutation, scu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scu *SyncConflictUpdate) SaveX(ctx context.Context) int {
	affected, err := scu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (scu *SyncConflictUpdate) Exec(ctx context.Context) error {
	_, err := scu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scu *SyncConflictUpdate) ExecX(ctx context.Context) {
	if err := scu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scu *SyncConflictUpdate) defaults() {
	if _, ok := scu.mutation.UpdatedAt(); !ok {
		v := syncconflict.UpdateDefaultUpdatedAt()
		scu.mutation.SetUpdatedAt(v)
	}
}

func (scu *SyncConflictUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncconflict.Table, syncconflict.Columns, sqlgraph.NewFieldSpec(syncconflict.FieldID, field.TypeUUID))
	if ps := scu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scu.mutation.EntityType(); ok {
		_spec.SetField(syncconflict.FieldEntityType, field.TypeString, value)
	}
	if value, ok := scu.mutation.EntityID(); ok {
		_spec.SetField(syncconflict.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := scu.mutation.ConflictType(); ok {
		_spec.SetField(syncconflict.FieldConflictType, field.TypeString, value)
	}
	if value, ok := scu.mutation.ServerPayload(); ok {
		_spec.SetField(syncconflict.FieldServerPayload, field.TypeBytes, value)
	}
	if value, ok := scu.mutation.ClientPayload(); ok {
		_spec.SetField(syncconflict.FieldClientPayload, field.TypeBytes, value)
	}
	if value, ok := scu.mutation.Resolution(); ok {
		_spec.SetField(syncconflict.FieldResolution, field.TypeString, value)
	}
	if value, ok := scu.mutation.ResolvedAt(); ok {
		_spec.SetField(syncconflict.FieldResolvedAt, field.TypeTime, value)
	}
	if scu.mutation.ResolvedAtCleared() {
		_spec.ClearField(syncconflict.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := scu.mutation.UpdatedAt(); ok {
		_spec.SetField(syncconflict.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, scu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncconflict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	scu.mutation.done = true
	return n, nil
}

// SyncConflictUpdateOne is the builder for updating a single SyncConflict entity.
type SyncConflictUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncConflictMutation
}

// SetEntityType sets the "entity_type" field.
func (scuo *SyncConflictUpdateOne) SetEntityType(s string) *SyncConflictUpdateOne {
	scuo.mutation.SetEntityType(s)
	return scuo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (scuo *SyncConflictUpdateOne) SetNillableEntityType(s *string) *SyncConflictUpdateOne {
	if s != nil {
		scuo.SetEntityType(*s)
	}
	return scuo
}

// SetEntityID sets the "entity_id" field.
func (scuo *SyncConflictUpdateOne) SetEntityID(u uuid.UUID) *SyncConflictUpdateOne {
	scuo.mutation.SetEntityID(u)
	return scuo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (scuo *SyncConflictUpdateOne) SetNillableEntityID(u *uuid.UUID) *SyncConflictUpdateOne {
	if u != nil {
		scuo.SetEntityID(*u)
	}
	return scuo
}

// SetConflictType sets the "conflict_type" field.
func (scuo *SyncConflictUpdateOne) SetConflictType(s string) *SyncConflictUpdateOne {
	scuo.mutation.SetConflictType(s)
	return scuo
}

// SetNillableConflictType sets the "conflict_type" field if the given value is not nil.
func (scuo *SyncConflictUpdateOne) SetNillableConflictType(s *string) *SyncConflictUpdateOne {
	if s != nil {
		scuo.SetConflictType(*s)
	}
	return scuo
}

// SetServerPayload sets the "server_payload" field.
func (scuo *SyncConflictUpdateOne) SetServerPayload(b []byte) *SyncConflictUpdateOne {
	scuo.mutation.SetServerPayload(b)
	return scuo
}

// SetClientPayload sets the "client_payload" field.
func (scuo *SyncConflictUpdateOne) SetClientPayload(b []byte) *SyncConflictUpdateOne {
	scuo.mutation.SetClientPayload(b)
	return scuo
}

// SetResolution sets the "resolution" field.
func (scuo *SyncConflictUpdateOne) SetResolution(s string) *SyncConflictUpdateOne {
	scuo.mutation.SetResolution(s)
	return scuo
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (scuo *SyncConflictUpdateOne) SetNillableResolution(s *string) *SyncConflictUpdateOne {
	if s != nil {
		scuo.SetResolution(*s)
	}
	return scuo
}

// SetResolvedAt sets the "resolved_at" field.
func (scuo *SyncConflictUpdateOne) SetResolvedAt(t time.Time) *SyncConflictUpdateOne {
	scuo.mutation.SetResolvedAt(t)
	return scuo
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (scuo *SyncConflictUpdateOne) SetNillableResolvedAt(t *time.Time) *SyncConflictUpdateOne {
	if t != nil {
		scuo.SetResolvedAt(*t)
	}
	return scuo
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (scuo *SyncConflictUpdateOne) ClearResolvedAt() *SyncConflictUpdateOne {
	scuo.mutation.ClearResolvedAt()
	return scuo
}

// SetUpdatedAt sets the "updated_at" field.
func (scuo *SyncConflictUpdateOne) SetUpdatedAt(t time.Time) *SyncConflictUpdateOne {
	scuo.mutation.SetUpdatedAt(t)
	return scuo
}

// Mutation returns the SyncConflictMutation object of the builder.
func (scuo *SyncConflictUpdateOne) Mutation() *SyncConflictMutation {
	return scuo.mutation
}

// Where appends a list predicates to the SyncConflictUpdate builder.
func (scuo *SyncConflictUpdateOne) Where(ps ...predicate.SyncConflict) *SyncConflictUpdateOne {
	scuo.mutation.Where(ps...)
	return scuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (scuo *SyncConflictUpdateOne) Select(field string, fields ...string) *SyncConflictUpdateOne {
	scuo.fields = append([]string{field}, fields...)
	return scuo
}

// Save executes the query and returns the updated SyncConflict entity.
func (scuo *SyncConflictUpdateOne) Save(ctx context.Context) (*SyncConflict, error) {
	scuo.defaults()
	return withHooks(ctx, scuo.sqlSave, scuo.mutation, scuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scuo *SyncConflictUpdateOne) SaveX(ctx context.Context) *SyncConflict {
	node, err := scuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (scuo *SyncConflictUpdateOne) Exec(ctx context.Context) error {
	_, err := scuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scuo *SyncConflictUpdateOne) ExecX(ctx context.Context) {
	if err := scuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scuo *SyncConflictUpdateOne) defaults() {
	if _, ok := scuo.mutation.UpdatedAt(); !ok {
		v := syncconflict.UpdateDefaultUpdatedAt()
		scuo.mutation.SetUpdatedAt(v)
	}
}

func (scuo *SyncConflictUpdateOne) sqlSave(ctx context.Context) (_node *SyncConflict, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncconflict.Table, syncconflict.Columns, sqlgraph.NewFieldSpec(syncconflict.FieldID, field.TypeUUID))
	id, ok := scuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncConflict.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := scuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncconflict.FieldID)
		for _, f := range fields {
			if !syncconflict.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncconflict.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := scuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scuo.mutation.EntityType(); ok {
		_spec.SetField(syncconflict.FieldEntityType, field.TypeString, value)
	}
	if value, ok := scuo.mutation.EntityID(); ok {
		_spec.SetField(syncconflict.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := scuo.mutation.ConflictType(); ok {
		_spec.SetField(syncconflict.FieldConflictType, field.TypeString, value)
	}
	if value, ok := scuo.mutation.ServerPayload(); ok {
		_spec.SetField(syncconflict.FieldServerPayload, field.TypeBytes, value)
	}
	if value, ok := scuo.mutation.ClientPayload(); ok {
		_spec.SetField(syncconflict.FieldClientPayload, field.TypeBytes, value)
	}
	if value, ok := scuo.mutation.Resolution(); ok {
		_spec.SetField(syncconflict.FieldResolution, field.TypeString, value)
	}
	if value, ok := scuo.mutation.ResolvedAt(); ok {
		_spec.SetField(syncconflict.FieldResolvedAt, field.TypeTime, value)
	}
	if scuo.mutation.ResolvedAtCleared() {
		_spec.ClearField(syncconflict.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := scuo.mutation.UpdatedAt(); ok {
		_spec.SetField(syncconflict.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SyncConflict{config: scuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, scuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncconflict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	scuo.mutation.done = true
	return _node, nil
}
