// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/sync/ent/syncconflict"
)

// SyncConflict is the model entity for the SyncConflict schema.
type SyncConflict struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FK to tenants table — data isolation boundary
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// account, transaction, etc.
	EntityType string `json:"entity_type,omitempty"`
	// ID of the conflicting entity
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// update_update, delete_update, create_create
	ConflictType string `json:"conflict_type,omitempty"`
	// Server-side entity state
	ServerPayload []byte `json:"server_payload,omitempty"`
	// Client-side entity state
	ClientPayload []byte `json:"client_payload,omitempty"`
	// pending, server, client, merged
	Resolution string `json:"resolution,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncConflict) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case syncconflict.FieldServerPayload, syncconflict.FieldClientPayload:
			values[i] = new([]byte)
		case syncconflict.FieldEntityType, syncconflict.FieldConflictType, syncconflict.FieldResolution:
			values[i] = new(sql.NullString)
		case syncconflict.FieldResolvedAt, syncconflict.FieldCreatedAt, syncconflict.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case syncconflict.FieldID, syncconflict.FieldTenantID, syncconflict.FieldEntityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncConflict fields.
func (sc *SyncConflict) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case syncconflict.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sc.ID = *value
			}
		case syncconflict.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				sc.TenantID = *value
			}
		case syncconflict.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				sc.EntityType = value.String
			}
		case syncconflict.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				sc.EntityID = *value
			}
		case syncconflict.FieldConflictType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field conflict_type", values[i])
			} else if value.Valid {
				sc.ConflictType = value.String
			}
		case syncconflict.FieldServerPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field server_payload", values[i])
			} else if value != nil {
				sc.ServerPayload = *value
			}
		case syncconflict.FieldClientPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field client_payload", values[i])
			} else if value != nil {
				sc.ClientPayload = *value
			}
		case syncconflict.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				sc.Resolution = value.String
			}
		case syncconflict.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				sc.ResolvedAt = new(time.Time)
				*sc.ResolvedAt = value.Time
			}
		case syncconflict.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sc.CreatedAt = value.Time
			}
		case syncconflict.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sc.UpdatedAt = value.Time
			}
		default:
			sc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncConflict.
// This includes values selected through modifiers, order, etc.
func (sc *SyncConflict) Value(name string) (ent.Value, error) {
	return sc.selectValues.Get(name)
}

// Update returns a builder for updating this SyncConflict.
// Note that you need to call SyncConflict.Unwrap() before calling this method if this SyncConflict
// was returned from a transaction, and the transaction was committed or rolled back.
func (sc *SyncConflict) Update() *SyncConflictUpdateOne {
	return NewSyncConflictClient(sc.config).UpdateOne(sc)
}

// Unwrap unwraps the SyncConflict entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sc *SyncConflict) Unwrap() *SyncConflict {
	_tx, ok := sc.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncConflict is not a transactional entity")
	}
	sc.config.driver = _tx.drv
	return sc
}

// String implements the fmt.Stringer.
func (sc *SyncConflict) String() string {
	var builder strings.Builder
	builder.WriteString("SyncConflict(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sc.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", sc.TenantID))
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(sc.EntityType)
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", sc.EntityID))
	builder.WriteString(", ")
	builder.WriteString("conflict_type=")
	builder.WriteString(sc.ConflictType)
	builder.WriteString(", ")
	builder.WriteString("server_payload=")
	builder.WriteString(fmt.Sprintf("%v", sc.ServerPayload))
	builder.WriteString(", ")
	builder.WriteString("client_payload=")
	builder.WriteString(fmt.Sprintf("%v", sc.ClientPayload))
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(sc.Resolution)
	builder.WriteString(", ")
	if v := sc.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SyncConflicts is a parsable slice of SyncConflict.
type SyncConflicts []*SyncConflict
