CREATE TABLE IF NOT EXISTS transaction_templates (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    amount TEXT NOT NULL DEFAULT '0',
    direction TEXT NOT NULL DEFAULT 'expense',
    source_account_id TEXT NOT NULL,
    destination_account_id TEXT,
    cycle TEXT NOT NULL DEFAULT 'monthly',
    cycle_days INTEGER,
    billing_day INTEGER,
    next_date TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT,
    auto_record INTEGER NOT NULL DEFAULT 1,
    paused INTEGER NOT NULL DEFAULT 0,
    last_transaction_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    deleted_at TEXT
);
