// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yucai/server/internal/backup/ent/backup"
	"github.com/yucai/server/internal/backup/ent/predicate"
)

// BackupUpdate is the builder for updating Backup entities.
type BackupUpdate struct {
	config
	hooks    []Hook
	mutation *BackupMutation
}

// Where appends a list predicates to the BackupUpdate builder.
func (bu *BackupUpdate) Where(ps ...predicate.Backup) *BackupUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetProvider sets the "provider" field.
func (bu *BackupUpdate) SetProvider(s string) *BackupUpdate {
	bu.mutation.SetProvider(s)
	return bu
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableProvider(s *string) *BackupUpdate {
	if s != nil {
		bu.SetProvider(*s)
	}
	return bu
}

// SetFilename sets the "filename" field.
func (bu *BackupUpdate) SetFilename(s string) *BackupUpdate {
	bu.mutation.SetFilename(s)
	return bu
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableFilename(s *string) *BackupUpdate {
	if s != nil {
		bu.SetFilename(*s)
	}
	return bu
}

// SetSizeBytes sets the "size_bytes" field.
func (bu *BackupUpdate) SetSizeBytes(i int64) *BackupUpdate {
	bu.mutation.ResetSizeBytes()
	bu.mutation.SetSizeBytes(i)
	return bu
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableSizeBytes(i *int64) *BackupUpdate {
	if i != nil {
		bu.SetSizeBytes(*i)
	}
	return bu
}

// AddSizeBytes adds i to the "size_bytes" field.
func (bu *BackupUpdate) AddSizeBytes(i int64) *BackupUpdate {
	bu.mutation.AddSizeBytes(i)
	return bu
}

// SetChecksum sets the "checksum" field.
func (bu *BackupUpdate) SetChecksum(s string) *BackupUpdate {
	bu.mutation.SetChecksum(s)
	return bu
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableChecksum(s *string) *BackupUpdate {
	if s != nil {
		bu.SetChecksum(*s)
	}
	return bu
}

// SetEncrypted sets the "encrypted" field.
func (bu *BackupUpdate) SetEncrypted(b bool) *BackupUpdate {
	bu.mutation.SetEncrypted(b)
	return bu
}

// SetNillableEncrypted sets the "encrypted" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableEncrypted(b *bool) *BackupUpdate {
	if b != nil {
		bu.SetEncrypted(*b)
	}
	return bu
}

// SetAuto sets the "auto" field.
func (bu *BackupUpdate) SetAuto(b bool) *BackupUpdate {
	bu.mutation.SetAuto(b)
	return bu
}

// SetNillableAuto sets the "auto" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableAuto(b *bool) *BackupUpdate {
	if b != nil {
		bu.SetAuto(*b)
	}
	return bu
}

// SetVersion sets the "version" field.
func (bu *BackupUpdate) SetVersion(i int64) *BackupUpdate {
	bu.mutation.ResetVersion()
	bu.mutation.SetVersion(i)
	return bu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (bu *BackupUpdate) SetNillableVersion(i *int64) *BackupUpdate {
	if i != nil {
		bu.SetVersion(*i)
	}
	return bu
}

// AddVersion adds i to the "version" field.
func (bu *BackupUpdate) AddVersion(i int64) *BackupUpdate {
	bu.mutation.AddVersion(i)
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BackupUpdate) SetUpdatedAt(t time.Time) *BackupUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// Mutation returns the BackupMutation object of the builder.
func (bu *BackupUpdate) Mutation() *BackupMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BackupUpdate) Save(ctx context.Context) (int, error) {
	bu.defaults()
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BackupUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BackupUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BackupUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bu *BackupUpdate) defaults() {
	if _, ok := bu.mutation.UpdatedAt(); !ok {
		v := backup.UpdateDefaultUpdatedAt()
		bu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BackupUpdate) check() error {
	if v, ok := bu.mutation.Filename(); ok {
		if err := backup.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Backup.filename": %w`, err)}
		}
	}
	return nil
}

func (bu *BackupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(backup.Table, backup.Columns, sqlgraph.NewFieldSpec(backup.FieldID, field.TypeUUID))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Provider(); ok {
		_spec.SetField(backup.FieldProvider, field.TypeString, value)
	}
	if value, ok := bu.mutation.Filename(); ok {
		_spec.SetField(backup.FieldFilename, field.TypeString, value)
	}
	if value, ok := bu.mutation.SizeBytes(); ok {
		_spec.SetField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.AddedSizeBytes(); ok {
		_spec.AddField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.Checksum(); ok {
		_spec.SetField(backup.FieldChecksum, field.TypeString, value)
	}
	if value, ok := bu.mutation.Encrypted(); ok {
		_spec.SetField(backup.FieldEncrypted, field.TypeBool, value)
	}
	if value, ok := bu.mutation.Auto(); ok {
		_spec.SetField(backup.FieldAuto, field.TypeBool, value)
	}
	if value, ok := bu.mutation.Version(); ok {
		_spec.SetField(backup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.AddedVersion(); ok {
		_spec.AddField(backup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(backup.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BackupUpdateOne is the builder for updating a single Backup entity.
type BackupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupMutation
}

// SetProvider sets the "provider" field.
func (buo *BackupUpdateOne) SetProvider(s string) *BackupUpdateOne {
	buo.mutation.SetProvider(s)
	return buo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableProvider(s *string) *BackupUpdateOne {
	if s != nil {
		buo.SetProvider(*s)
	}
	return buo
}

// SetFilename sets the "filename" field.
func (buo *BackupUpdateOne) SetFilename(s string) *BackupUpdateOne {
	buo.mutation.SetFilename(s)
	return buo
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableFilename(s *string) *BackupUpdateOne {
	if s != nil {
		buo.SetFilename(*s)
	}
	return buo
}

// SetSizeBytes sets the "size_bytes" field.
func (buo *BackupUpdateOne) SetSizeBytes(i int64) *BackupUpdateOne {
	buo.mutation.ResetSizeBytes()
	buo.mutation.SetSizeBytes(i)
	return buo
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableSizeBytes(i *int64) *BackupUpdateOne {
	if i != nil {
		buo.SetSizeBytes(*i)
	}
	return buo
}

// AddSizeBytes adds i to the "size_bytes" field.
func (buo *BackupUpdateOne) AddSizeBytes(i int64) *BackupUpdateOne {
	buo.mutation.AddSizeBytes(i)
	return buo
}

// SetChecksum sets the "checksum" field.
func (buo *BackupUpdateOne) SetChecksum(s string) *BackupUpdateOne {
	buo.mutation.SetChecksum(s)
	return buo
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableChecksum(s *string) *BackupUpdateOne {
	if s != nil {
		buo.SetChecksum(*s)
	}
	return buo
}

// SetEncrypted sets the "encrypted" field.
func (buo *BackupUpdateOne) SetEncrypted(b bool) *BackupUpdateOne {
	buo.mutation.SetEncrypted(b)
	return buo
}

// SetNillableEncrypted sets the "encrypted" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableEncrypted(b *bool) *BackupUpdateOne {
	if b != nil {
		buo.SetEncrypted(*b)
	}
	return buo
}

// SetAuto sets the "auto" field.
func (buo *BackupUpdateOne) SetAuto(b bool) *BackupUpdateOne {
	buo.mutation.SetAuto(b)
	return buo
}

// SetNillableAuto sets the "auto" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableAuto(b *bool) *BackupUpdateOne {
	if b != nil {
		buo.SetAuto(*b)
	}
	return buo
}

// SetVersion sets the "version" field.
func (buo *BackupUpdateOne) SetVersion(i int64) *BackupUpdateOne {
	buo.mutation.ResetVersion()
	buo.mutation.SetVersion(i)
	return buo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (buo *BackupUpdateOne) SetNillableVersion(i *int64) *BackupUpdateOne {
	if i != nil {
		buo.SetVersion(*i)
	}
	return buo
}

// AddVersion adds i to the "version" field.
func (buo *BackupUpdateOne) AddVersion(i int64) *BackupUpdateOne {
	buo.mutation.AddVersion(i)
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BackupUpdateOne) SetUpdatedAt(t time.Time) *BackupUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// Mutation returns the BackupMutation object of the builder.
func (buo *BackupUpdateOne) Mutation() *BackupMutation {
	return buo.mutation
}

// Where appends a list predicates to the BackupUpdate builder.
func (buo *BackupUpdateOne) Where(ps ...predicate.Backup) *BackupUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BackupUpdateOne) Select(field string, fields ...string) *BackupUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Backup entity.
func (buo *BackupUpdateOne) Save(ctx context.Context) (*Backup, error) {
	buo.defaults()
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BackupUpdateOne) SaveX(ctx context.Context) *Backup {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BackupUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BackupUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (buo *BackupUpdateOne) defaults() {
	if _, ok := buo.mutation.UpdatedAt(); !ok {
		v := backup.UpdateDefaultUpdatedAt()
		buo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BackupUpdateOne) check() error {
	if v, ok := buo.mutation.Filename(); ok {
		if err := backup.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Backup.filename": %w`, err)}
		}
	}
	return nil
}

func (buo *BackupUpdateOne) sqlSave(ctx context.Context) (_node *Backup, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backup.Table, backup.Columns, sqlgraph.NewFieldSpec(backup.FieldID, field.TypeUUID))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Backup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backup.FieldID)
		for _, f := range fields {
			if !backup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Provider(); ok {
		_spec.SetField(backup.FieldProvider, field.TypeString, value)
	}
	if value, ok := buo.mutation.Filename(); ok {
		_spec.SetField(backup.FieldFilename, field.TypeString, value)
	}
	if value, ok := buo.mutation.SizeBytes(); ok {
		_spec.SetField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.AddedSizeBytes(); ok {
		_spec.AddField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.Checksum(); ok {
		_spec.SetField(backup.FieldChecksum, field.TypeString, value)
	}
	if value, ok := buo.mutation.Encrypted(); ok {
		_spec.SetField(backup.FieldEncrypted, field.TypeBool, value)
	}
	if value, ok := buo.mutation.Auto(); ok {
		_spec.SetField(backup.FieldAuto, field.TypeBool, value)
	}
	if value, ok := buo.mutation.Version(); ok {
		_spec.SetField(backup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.AddedVersion(); ok {
		_spec.AddField(backup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(backup.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Backup{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
