// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: debt/v1/debt.proto

package debtv1

import (
	v1 "github.com/yucai/server/internal/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AmortizationMethod int32

const (
	AmortizationMethod_AMORTIZATION_UNSPECIFIED              AmortizationMethod = 0
	AmortizationMethod_AMORTIZATION_EQUAL_PRINCIPAL_INTEREST AmortizationMethod = 1
	AmortizationMethod_AMORTIZATION_EQUAL_PRINCIPAL          AmortizationMethod = 2
	AmortizationMethod_AMORTIZATION_LUMP_SUM                 AmortizationMethod = 3
)

// Enum value maps for AmortizationMethod.
var (
	AmortizationMethod_name = map[int32]string{
		0: "AMORTIZATION_UNSPECIFIED",
		1: "AMORTIZATION_EQUAL_PRINCIPAL_INTEREST",
		2: "AMORTIZATION_EQUAL_PRINCIPAL",
		3: "AMORTIZATION_LUMP_SUM",
	}
	AmortizationMethod_value = map[string]int32{
		"AMORTIZATION_UNSPECIFIED":              0,
		"AMORTIZATION_EQUAL_PRINCIPAL_INTEREST": 1,
		"AMORTIZATION_EQUAL_PRINCIPAL":          2,
		"AMORTIZATION_LUMP_SUM":                 3,
	}
)

func (x AmortizationMethod) Enum() *AmortizationMethod {
	p := new(AmortizationMethod)
	*p = x
	return p
}

func (x AmortizationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmortizationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_debt_v1_debt_proto_enumTypes[0].Descriptor()
}

func (AmortizationMethod) Type() protoreflect.EnumType {
	return &file_debt_v1_debt_proto_enumTypes[0]
}

func (x AmortizationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmortizationMethod.Descriptor instead.
func (AmortizationMethod) EnumDescriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{0}
}

type DebtDTO struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId               string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Counterparty            string                 `protobuf:"bytes,3,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	InterestRate            float64                `protobuf:"fixed64,4,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	AmortizationMethod      AmortizationMethod     `protobuf:"varint,5,opt,name=amortization_method,json=amortizationMethod,proto3,enum=yucai.debt.v1.AmortizationMethod" json:"amortization_method,omitempty"`
	StartDate               string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	DueDate                 string                 `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	TotalPrincipalCents     int64                  `protobuf:"varint,8,opt,name=total_principal_cents,json=totalPrincipalCents,proto3" json:"total_principal_cents,omitempty"`
	RemainingPrincipalCents int64                  `protobuf:"varint,9,opt,name=remaining_principal_cents,json=remainingPrincipalCents,proto3" json:"remaining_principal_cents,omitempty"`
	Version                 int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DebtDTO) Reset() {
	*x = DebtDTO{}
	mi := &file_debt_v1_debt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebtDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebtDTO) ProtoMessage() {}

func (x *DebtDTO) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebtDTO.ProtoReflect.Descriptor instead.
func (*DebtDTO) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{0}
}

func (x *DebtDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DebtDTO) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DebtDTO) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *DebtDTO) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *DebtDTO) GetAmortizationMethod() AmortizationMethod {
	if x != nil {
		return x.AmortizationMethod
	}
	return AmortizationMethod_AMORTIZATION_UNSPECIFIED
}

func (x *DebtDTO) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DebtDTO) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *DebtDTO) GetTotalPrincipalCents() int64 {
	if x != nil {
		return x.TotalPrincipalCents
	}
	return 0
}

func (x *DebtDTO) GetRemainingPrincipalCents() int64 {
	if x != nil {
		return x.RemainingPrincipalCents
	}
	return 0
}

func (x *DebtDTO) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DebtDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DebtDTO) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaymentEntryDTO struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentDate    string                 `protobuf:"bytes,2,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	PrincipalCents int64                  `protobuf:"varint,3,opt,name=principal_cents,json=principalCents,proto3" json:"principal_cents,omitempty"`
	InterestCents  int64                  `protobuf:"varint,4,opt,name=interest_cents,json=interestCents,proto3" json:"interest_cents,omitempty"`
	TotalCents     int64                  `protobuf:"varint,5,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Paid           bool                   `protobuf:"varint,6,opt,name=paid,proto3" json:"paid,omitempty"`
	PaidCents      int64                  `protobuf:"varint,7,opt,name=paid_cents,json=paidCents,proto3" json:"paid_cents,omitempty"`
	TransactionId  string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentEntryDTO) Reset() {
	*x = PaymentEntryDTO{}
	mi := &file_debt_v1_debt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEntryDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEntryDTO) ProtoMessage() {}

func (x *PaymentEntryDTO) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEntryDTO.ProtoReflect.Descriptor instead.
func (*PaymentEntryDTO) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentEntryDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentEntryDTO) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *PaymentEntryDTO) GetPrincipalCents() int64 {
	if x != nil {
		return x.PrincipalCents
	}
	return 0
}

func (x *PaymentEntryDTO) GetInterestCents() int64 {
	if x != nil {
		return x.InterestCents
	}
	return 0
}

func (x *PaymentEntryDTO) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *PaymentEntryDTO) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *PaymentEntryDTO) GetPaidCents() int64 {
	if x != nil {
		return x.PaidCents
	}
	return 0
}

func (x *PaymentEntryDTO) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type DebtDetailDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debt          *DebtDTO               `protobuf:"bytes,1,opt,name=debt,proto3" json:"debt,omitempty"`
	Schedule      []*PaymentEntryDTO     `protobuf:"bytes,2,rep,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebtDetailDTO) Reset() {
	*x = DebtDetailDTO{}
	mi := &file_debt_v1_debt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebtDetailDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebtDetailDTO) ProtoMessage() {}

func (x *DebtDetailDTO) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebtDetailDTO.ProtoReflect.Descriptor instead.
func (*DebtDetailDTO) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{2}
}

func (x *DebtDetailDTO) GetDebt() *DebtDTO {
	if x != nil {
		return x.Debt
	}
	return nil
}

func (x *DebtDetailDTO) GetSchedule() []*PaymentEntryDTO {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type CreateDebtRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccountId           string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Counterparty        string                 `protobuf:"bytes,2,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	InterestRate        float64                `protobuf:"fixed64,3,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	AmortizationMethod  AmortizationMethod     `protobuf:"varint,4,opt,name=amortization_method,json=amortizationMethod,proto3,enum=yucai.debt.v1.AmortizationMethod" json:"amortization_method,omitempty"`
	StartDate           string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	DueDate             string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	TotalPrincipalCents int64                  `protobuf:"varint,7,opt,name=total_principal_cents,json=totalPrincipalCents,proto3" json:"total_principal_cents,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateDebtRequest) Reset() {
	*x = CreateDebtRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDebtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDebtRequest) ProtoMessage() {}

func (x *CreateDebtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDebtRequest.ProtoReflect.Descriptor instead.
func (*CreateDebtRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDebtRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateDebtRequest) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *CreateDebtRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *CreateDebtRequest) GetAmortizationMethod() AmortizationMethod {
	if x != nil {
		return x.AmortizationMethod
	}
	return AmortizationMethod_AMORTIZATION_UNSPECIFIED
}

func (x *CreateDebtRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateDebtRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *CreateDebtRequest) GetTotalPrincipalCents() int64 {
	if x != nil {
		return x.TotalPrincipalCents
	}
	return 0
}

type UpdateDebtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Counterparty  string                 `protobuf:"bytes,2,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	InterestRate  float64                `protobuf:"fixed64,3,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDebtRequest) Reset() {
	*x = UpdateDebtRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDebtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDebtRequest) ProtoMessage() {}

func (x *UpdateDebtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDebtRequest.ProtoReflect.Descriptor instead.
func (*UpdateDebtRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDebtRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDebtRequest) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *UpdateDebtRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *UpdateDebtRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteDebtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDebtRequest) Reset() {
	*x = DeleteDebtRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDebtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDebtRequest) ProtoMessage() {}

func (x *DeleteDebtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDebtRequest.ProtoReflect.Descriptor instead.
func (*DeleteDebtRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDebtRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecordPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DebtId          string                 `protobuf:"bytes,1,opt,name=debt_id,json=debtId,proto3" json:"debt_id,omitempty"`
	ScheduleEntryId string                 `protobuf:"bytes,2,opt,name=schedule_entry_id,json=scheduleEntryId,proto3" json:"schedule_entry_id,omitempty"`
	FromAccountId   string                 `protobuf:"bytes,3,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordPaymentRequest) Reset() {
	*x = RecordPaymentRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPaymentRequest) ProtoMessage() {}

func (x *RecordPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPaymentRequest.ProtoReflect.Descriptor instead.
func (*RecordPaymentRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{6}
}

func (x *RecordPaymentRequest) GetDebtId() string {
	if x != nil {
		return x.DebtId
	}
	return ""
}

func (x *RecordPaymentRequest) GetScheduleEntryId() string {
	if x != nil {
		return x.ScheduleEntryId
	}
	return ""
}

func (x *RecordPaymentRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

type RecordPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Entry         *PaymentEntryDTO       `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPaymentResponse) Reset() {
	*x = RecordPaymentResponse{}
	mi := &file_debt_v1_debt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPaymentResponse) ProtoMessage() {}

func (x *RecordPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPaymentResponse.ProtoReflect.Descriptor instead.
func (*RecordPaymentResponse) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{7}
}

func (x *RecordPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordPaymentResponse) GetEntry() *PaymentEntryDTO {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetDebtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebtRequest) Reset() {
	*x = GetDebtRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebtRequest) ProtoMessage() {}

func (x *GetDebtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebtRequest.ProtoReflect.Descriptor instead.
func (*GetDebtRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{8}
}

func (x *GetDebtRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDebtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDebtsRequest) Reset() {
	*x = ListDebtsRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDebtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDebtsRequest) ProtoMessage() {}

func (x *ListDebtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDebtsRequest.ProtoReflect.Descriptor instead.
func (*ListDebtsRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{9}
}

func (x *ListDebtsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListDebtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debts         []*DebtDTO             `protobuf:"bytes,1,rep,name=debts,proto3" json:"debts,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDebtsResponse) Reset() {
	*x = ListDebtsResponse{}
	mi := &file_debt_v1_debt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDebtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDebtsResponse) ProtoMessage() {}

func (x *ListDebtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDebtsResponse.ProtoReflect.Descriptor instead.
func (*ListDebtsResponse) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{10}
}

func (x *ListDebtsResponse) GetDebts() []*DebtDTO {
	if x != nil {
		return x.Debts
	}
	return nil
}

func (x *ListDebtsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetUpcomingPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaysAhead     int32                  `protobuf:"varint,1,opt,name=days_ahead,json=daysAhead,proto3" json:"days_ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingPaymentsRequest) Reset() {
	*x = GetUpcomingPaymentsRequest{}
	mi := &file_debt_v1_debt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingPaymentsRequest) ProtoMessage() {}

func (x *GetUpcomingPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{11}
}

func (x *GetUpcomingPaymentsRequest) GetDaysAhead() int32 {
	if x != nil {
		return x.DaysAhead
	}
	return 0
}

type DebtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debt          *DebtDTO               `protobuf:"bytes,1,opt,name=debt,proto3" json:"debt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebtResponse) Reset() {
	*x = DebtResponse{}
	mi := &file_debt_v1_debt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebtResponse) ProtoMessage() {}

func (x *DebtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebtResponse.ProtoReflect.Descriptor instead.
func (*DebtResponse) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{12}
}

func (x *DebtResponse) GetDebt() *DebtDTO {
	if x != nil {
		return x.Debt
	}
	return nil
}

type DebtDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debt          *DebtDetailDTO         `protobuf:"bytes,1,opt,name=debt,proto3" json:"debt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebtDetailResponse) Reset() {
	*x = DebtDetailResponse{}
	mi := &file_debt_v1_debt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebtDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebtDetailResponse) ProtoMessage() {}

func (x *DebtDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debt_v1_debt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebtDetailResponse.ProtoReflect.Descriptor instead.
func (*DebtDetailResponse) Descriptor() ([]byte, []int) {
	return file_debt_v1_debt_proto_rawDescGZIP(), []int{13}
}

func (x *DebtDetailResponse) GetDebt() *DebtDetailDTO {
	if x != nil {
		return x.Debt
	}
	return nil
}

var File_debt_v1_debt_proto protoreflect.FileDescriptor

const file_debt_v1_debt_proto_rawDesc = "" +
	"\n" +
	"\x12debt/v1/debt.proto\x12\ryucai.debt.v1\x1a\x1acommon/v1/pagination.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x04\n" +
	"\aDebtDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\"\n" +
	"\fcounterparty\x18\x03 \x01(\tR\fcounterparty\x12#\n" +
	"\rinterest_rate\x18\x04 \x01(\x01R\finterestRate\x12R\n" +
	"\x13amortization_method\x18\x05 \x01(\x0e2!.yucai.debt.v1.AmortizationMethodR\x12amortizationMethod\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bdue_date\x18\a \x01(\tR\adueDate\x122\n" +
	"\x15total_principal_cents\x18\b \x01(\x03R\x13totalPrincipalCents\x12:\n" +
	"\x19remaining_principal_cents\x18\t \x01(\x03R\x17remainingPrincipalCents\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8f\x02\n" +
	"\x0fPaymentEntryDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpayment_date\x18\x02 \x01(\tR\vpaymentDate\x12'\n" +
	"\x0fprincipal_cents\x18\x03 \x01(\x03R\x0eprincipalCents\x12%\n" +
	"\x0einterest_cents\x18\x04 \x01(\x03R\rinterestCents\x12\x1f\n" +
	"\vtotal_cents\x18\x05 \x01(\x03R\n" +
	"totalCents\x12\x12\n" +
	"\x04paid\x18\x06 \x01(\bR\x04paid\x12\x1d\n" +
	"\n" +
	"paid_cents\x18\a \x01(\x03R\tpaidCents\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\"w\n" +
	"\rDebtDetailDTO\x12*\n" +
	"\x04debt\x18\x01 \x01(\v2\x16.yucai.debt.v1.DebtDTOR\x04debt\x12:\n" +
	"\bschedule\x18\x02 \x03(\v2\x1e.yucai.debt.v1.PaymentEntryDTOR\bschedule\"\xbd\x02\n" +
	"\x11CreateDebtRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\"\n" +
	"\fcounterparty\x18\x02 \x01(\tR\fcounterparty\x12#\n" +
	"\rinterest_rate\x18\x03 \x01(\x01R\finterestRate\x12R\n" +
	"\x13amortization_method\x18\x04 \x01(\x0e2!.yucai.debt.v1.AmortizationMethodR\x12amortizationMethod\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x122\n" +
	"\x15total_principal_cents\x18\a \x01(\x03R\x13totalPrincipalCents\"\x86\x01\n" +
	"\x11UpdateDebtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcounterparty\x18\x02 \x01(\tR\fcounterparty\x12#\n" +
	"\rinterest_rate\x18\x03 \x01(\x01R\finterestRate\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"#\n" +
	"\x11DeleteDebtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x01\n" +
	"\x14RecordPaymentRequest\x12\x17\n" +
	"\adebt_id\x18\x01 \x01(\tR\x06debtId\x12*\n" +
	"\x11schedule_entry_id\x18\x02 \x01(\tR\x0fscheduleEntryId\x12&\n" +
	"\x0ffrom_account_id\x18\x03 \x01(\tR\rfromAccountId\"t\n" +
	"\x15RecordPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x124\n" +
	"\x05entry\x18\x02 \x01(\v2\x1e.yucai.debt.v1.PaymentEntryDTOR\x05entry\" \n" +
	"\x0eGetDebtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10ListDebtsRequest\x120\n" +
	"\x04page\x18\x01 \x01(\v2\x1c.yucai.common.v1.PageRequestR\x04page\"t\n" +
	"\x11ListDebtsResponse\x12,\n" +
	"\x05debts\x18\x01 \x03(\v2\x16.yucai.debt.v1.DebtDTOR\x05debts\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.yucai.common.v1.PageResponseR\x04page\";\n" +
	"\x1aGetUpcomingPaymentsRequest\x12\x1d\n" +
	"\n" +
	"days_ahead\x18\x01 \x01(\x05R\tdaysAhead\":\n" +
	"\fDebtResponse\x12*\n" +
	"\x04debt\x18\x01 \x01(\v2\x16.yucai.debt.v1.DebtDTOR\x04debt\"F\n" +
	"\x12DebtDetailResponse\x120\n" +
	"\x04debt\x18\x01 \x01(\v2\x1c.yucai.debt.v1.DebtDetailDTOR\x04debt*\x9a\x01\n" +
	"\x12AmortizationMethod\x12\x1c\n" +
	"\x18AMORTIZATION_UNSPECIFIED\x10\x00\x12)\n" +
	"%AMORTIZATION_EQUAL_PRINCIPAL_INTEREST\x10\x01\x12 \n" +
	"\x1cAMORTIZATION_EQUAL_PRINCIPAL\x10\x02\x12\x19\n" +
	"\x15AMORTIZATION_LUMP_SUM\x10\x032\xcc\x04\n" +
	"\vDebtService\x12K\n" +
	"\n" +
	"CreateDebt\x12 .yucai.debt.v1.CreateDebtRequest\x1a\x1b.yucai.debt.v1.DebtResponse\x12K\n" +
	"\n" +
	"UpdateDebt\x12 .yucai.debt.v1.UpdateDebtRequest\x1a\x1b.yucai.debt.v1.DebtResponse\x12F\n" +
	"\n" +
	"DeleteDebt\x12 .yucai.debt.v1.DeleteDebtRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\rRecordPayment\x12#.yucai.debt.v1.RecordPaymentRequest\x1a$.yucai.debt.v1.RecordPaymentResponse\x12K\n" +
	"\aGetDebt\x12\x1d.yucai.debt.v1.GetDebtRequest\x1a!.yucai.debt.v1.DebtDetailResponse\x12N\n" +
	"\tListDebts\x12\x1f.yucai.debt.v1.ListDebtsRequest\x1a .yucai.debt.v1.ListDebtsResponse\x12b\n" +
	"\x13GetUpcomingPayments\x12).yucai.debt.v1.GetUpcomingPaymentsRequest\x1a .yucai.debt.v1.ListDebtsResponseB\xab\x01\n" +
	"\x11com.yucai.debt.v1B\tDebtProtoP\x01Z5github.com/yucai/server/internal/proto/debt/v1;debtv1\xa2\x02\x03YDX\xaa\x02\rYucai.Debt.V1\xca\x02\rYucai\\Debt\\V1\xe2\x02\x19Yucai\\Debt\\V1\\GPBMetadata\xea\x02\x0fYucai::Debt::V1b\x06proto3"

var (
	file_debt_v1_debt_proto_rawDescOnce sync.Once
	file_debt_v1_debt_proto_rawDescData []byte
)

func file_debt_v1_debt_proto_rawDescGZIP() []byte {
	file_debt_v1_debt_proto_rawDescOnce.Do(func() {
		file_debt_v1_debt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debt_v1_debt_proto_rawDesc), len(file_debt_v1_debt_proto_rawDesc)))
	})
	return file_debt_v1_debt_proto_rawDescData
}

var file_debt_v1_debt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_debt_v1_debt_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_debt_v1_debt_proto_goTypes = []any{
	(AmortizationMethod)(0),            // 0: yucai.debt.v1.AmortizationMethod
	(*DebtDTO)(nil),                    // 1: yucai.debt.v1.DebtDTO
	(*PaymentEntryDTO)(nil),            // 2: yucai.debt.v1.PaymentEntryDTO
	(*DebtDetailDTO)(nil),              // 3: yucai.debt.v1.DebtDetailDTO
	(*CreateDebtRequest)(nil),          // 4: yucai.debt.v1.CreateDebtRequest
	(*UpdateDebtRequest)(nil),          // 5: yucai.debt.v1.UpdateDebtRequest
	(*DeleteDebtRequest)(nil),          // 6: yucai.debt.v1.DeleteDebtRequest
	(*RecordPaymentRequest)(nil),       // 7: yucai.debt.v1.RecordPaymentRequest
	(*RecordPaymentResponse)(nil),      // 8: yucai.debt.v1.RecordPaymentResponse
	(*GetDebtRequest)(nil),             // 9: yucai.debt.v1.GetDebtRequest
	(*ListDebtsRequest)(nil),           // 10: yucai.debt.v1.ListDebtsRequest
	(*ListDebtsResponse)(nil),          // 11: yucai.debt.v1.ListDebtsResponse
	(*GetUpcomingPaymentsRequest)(nil), // 12: yucai.debt.v1.GetUpcomingPaymentsRequest
	(*DebtResponse)(nil),               // 13: yucai.debt.v1.DebtResponse
	(*DebtDetailResponse)(nil),         // 14: yucai.debt.v1.DebtDetailResponse
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),             // 16: yucai.common.v1.PageRequest
	(*v1.PageResponse)(nil),            // 17: yucai.common.v1.PageResponse
	(*emptypb.Empty)(nil),              // 18: google.protobuf.Empty
}
var file_debt_v1_debt_proto_depIdxs = []int32{
	0,  // 0: yucai.debt.v1.DebtDTO.amortization_method:type_name -> yucai.debt.v1.AmortizationMethod
	15, // 1: yucai.debt.v1.DebtDTO.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: yucai.debt.v1.DebtDTO.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: yucai.debt.v1.DebtDetailDTO.debt:type_name -> yucai.debt.v1.DebtDTO
	2,  // 4: yucai.debt.v1.DebtDetailDTO.schedule:type_name -> yucai.debt.v1.PaymentEntryDTO
	0,  // 5: yucai.debt.v1.CreateDebtRequest.amortization_method:type_name -> yucai.debt.v1.AmortizationMethod
	2,  // 6: yucai.debt.v1.RecordPaymentResponse.entry:type_name -> yucai.debt.v1.PaymentEntryDTO
	16, // 7: yucai.debt.v1.ListDebtsRequest.page:type_name -> yucai.common.v1.PageRequest
	1,  // 8: yucai.debt.v1.ListDebtsResponse.debts:type_name -> yucai.debt.v1.DebtDTO
	17, // 9: yucai.debt.v1.ListDebtsResponse.page:type_name -> yucai.common.v1.PageResponse
	1,  // 10: yucai.debt.v1.DebtResponse.debt:type_name -> yucai.debt.v1.DebtDTO
	3,  // 11: yucai.debt.v1.DebtDetailResponse.debt:type_name -> yucai.debt.v1.DebtDetailDTO
	4,  // 12: yucai.debt.v1.DebtService.CreateDebt:input_type -> yucai.debt.v1.CreateDebtRequest
	5,  // 13: yucai.debt.v1.DebtService.UpdateDebt:input_type -> yucai.debt.v1.UpdateDebtRequest
	6,  // 14: yucai.debt.v1.DebtService.DeleteDebt:input_type -> yucai.debt.v1.DeleteDebtRequest
	7,  // 15: yucai.debt.v1.DebtService.RecordPayment:input_type -> yucai.debt.v1.RecordPaymentRequest
	9,  // 16: yucai.debt.v1.DebtService.GetDebt:input_type -> yucai.debt.v1.GetDebtRequest
	10, // 17: yucai.debt.v1.DebtService.ListDebts:input_type -> yucai.debt.v1.ListDebtsRequest
	12, // 18: yucai.debt.v1.DebtService.GetUpcomingPayments:input_type -> yucai.debt.v1.GetUpcomingPaymentsRequest
	13, // 19: yucai.debt.v1.DebtService.CreateDebt:output_type -> yucai.debt.v1.DebtResponse
	13, // 20: yucai.debt.v1.DebtService.UpdateDebt:output_type -> yucai.debt.v1.DebtResponse
	18, // 21: yucai.debt.v1.DebtService.DeleteDebt:output_type -> google.protobuf.Empty
	8,  // 22: yucai.debt.v1.DebtService.RecordPayment:output_type -> yucai.debt.v1.RecordPaymentResponse
	14, // 23: yucai.debt.v1.DebtService.GetDebt:output_type -> yucai.debt.v1.DebtDetailResponse
	11, // 24: yucai.debt.v1.DebtService.ListDebts:output_type -> yucai.debt.v1.ListDebtsResponse
	11, // 25: yucai.debt.v1.DebtService.GetUpcomingPayments:output_type -> yucai.debt.v1.ListDebtsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_debt_v1_debt_proto_init() }
func file_debt_v1_debt_proto_init() {
	if File_debt_v1_debt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debt_v1_debt_proto_rawDesc), len(file_debt_v1_debt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_debt_v1_debt_proto_goTypes,
		DependencyIndexes: file_debt_v1_debt_proto_depIdxs,
		EnumInfos:         file_debt_v1_debt_proto_enumTypes,
		MessageInfos:      file_debt_v1_debt_proto_msgTypes,
	}.Build()
	File_debt_v1_debt_proto = out.File
	file_debt_v1_debt_proto_goTypes = nil
	file_debt_v1_debt_proto_depIdxs = nil
}
