// Code generated by ent, DO NOT EDIT.

package debtprogresssnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the debtprogresssnapshot type in the database.
	Label = "debt_progress_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDebtID holds the string denoting the debt_id field in the database.
	FieldDebtID = "debt_id"
	// FieldSnapshotDate holds the string denoting the snapshot_date field in the database.
	FieldSnapshotDate = "snapshot_date"
	// FieldTotalPrincipalCents holds the string denoting the total_principal_cents field in the database.
	FieldTotalPrincipalCents = "total_principal_cents"
	// FieldRemainingPrincipalCents holds the string denoting the remaining_principal_cents field in the database.
	FieldRemainingPrincipalCents = "remaining_principal_cents"
	// FieldPaidTotalCents holds the string denoting the paid_total_cents field in the database.
	FieldPaidTotalCents = "paid_total_cents"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the debtprogresssnapshot in the database.
	Table = "debt_progress_snapshots"
)

// Columns holds all SQL columns for debtprogresssnapshot fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldDebtID,
	FieldSnapshotDate,
	FieldTotalPrincipalCents,
	FieldRemainingPrincipalCents,
	FieldPaidTotalCents,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DebtProgressSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDebtID orders the results by the debt_id field.
func ByDebtID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDebtID, opts...).ToFunc()
}

// BySnapshotDate orders the results by the snapshot_date field.
func BySnapshotDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotDate, opts...).ToFunc()
}

// ByTotalPrincipalCents orders the results by the total_principal_cents field.
func ByTotalPrincipalCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrincipalCents, opts...).ToFunc()
}

// ByRemainingPrincipalCents orders the results by the remaining_principal_cents field.
func ByRemainingPrincipalCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemainingPrincipalCents, opts...).ToFunc()
}

// ByPaidTotalCents orders the results by the paid_total_cents field.
func ByPaidTotalCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidTotalCents, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
