// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/holding/ent/holdinglot"
)

// HoldingLotCreate is the builder for creating a HoldingLot entity.
type HoldingLotCreate struct {
	config
	mutation *HoldingLotMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (hlc *HoldingLotCreate) SetTenantID(u uuid.UUID) *HoldingLotCreate {
	hlc.mutation.SetTenantID(u)
	return hlc
}

// SetHoldingID sets the "holding_id" field.
func (hlc *HoldingLotCreate) SetHoldingID(u uuid.UUID) *HoldingLotCreate {
	hlc.mutation.SetHoldingID(u)
	return hlc
}

// SetSecurityID sets the "security_id" field.
func (hlc *HoldingLotCreate) SetSecurityID(u uuid.UUID) *HoldingLotCreate {
	hlc.mutation.SetSecurityID(u)
	return hlc
}

// SetAcquiredDate sets the "acquired_date" field.
func (hlc *HoldingLotCreate) SetAcquiredDate(t time.Time) *HoldingLotCreate {
	hlc.mutation.SetAcquiredDate(t)
	return hlc
}

// SetAcquiredTradeID sets the "acquired_trade_id" field.
func (hlc *HoldingLotCreate) SetAcquiredTradeID(u uuid.UUID) *HoldingLotCreate {
	hlc.mutation.SetAcquiredTradeID(u)
	return hlc
}

// SetPriceCents sets the "price_cents" field.
func (hlc *HoldingLotCreate) SetPriceCents(i int64) *HoldingLotCreate {
	hlc.mutation.SetPriceCents(i)
	return hlc
}

// SetQuantity sets the "quantity" field.
func (hlc *HoldingLotCreate) SetQuantity(f float64) *HoldingLotCreate {
	hlc.mutation.SetQuantity(f)
	return hlc
}

// SetRemainingQuantity sets the "remaining_quantity" field.
func (hlc *HoldingLotCreate) SetRemainingQuantity(f float64) *HoldingLotCreate {
	hlc.mutation.SetRemainingQuantity(f)
	return hlc
}

// SetCreatedAt sets the "created_at" field.
func (hlc *HoldingLotCreate) SetCreatedAt(t time.Time) *HoldingLotCreate {
	hlc.mutation.SetCreatedAt(t)
	return hlc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hlc *HoldingLotCreate) SetNillableCreatedAt(t *time.Time) *HoldingLotCreate {
	if t != nil {
		hlc.SetCreatedAt(*t)
	}
	return hlc
}

// SetID sets the "id" field.
func (hlc *HoldingLotCreate) SetID(u uuid.UUID) *HoldingLotCreate {
	hlc.mutation.SetID(u)
	return hlc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (hlc *HoldingLotCreate) SetNillableID(u *uuid.UUID) *HoldingLotCreate {
	if u != nil {
		hlc.SetID(*u)
	}
	return hlc
}

// Mutation returns the HoldingLotMutation object of the builder.
func (hlc *HoldingLotCreate) Mutation() *HoldingLotMutation {
	return hlc.mutation
}

// Save creates the HoldingLot in the database.
func (hlc *HoldingLotCreate) Save(ctx context.Context) (*HoldingLot, error) {
	hlc.defaults()
	return withHooks(ctx, hlc.sqlSave, hlc.mutation, hlc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hlc *HoldingLotCreate) SaveX(ctx context.Context) *HoldingLot {
	v, err := hlc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hlc *HoldingLotCreate) Exec(ctx context.Context) error {
	_, err := hlc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hlc *HoldingLotCreate) ExecX(ctx context.Context) {
	if err := hlc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hlc *HoldingLotCreate) defaults() {
	if _, ok := hlc.mutation.CreatedAt(); !ok {
		v := holdinglot.DefaultCreatedAt()
		hlc.mutation.SetCreatedAt(v)
	}
	if _, ok := hlc.mutation.ID(); !ok {
		v := holdinglot.DefaultID()
		hlc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hlc *HoldingLotCreate) check() error {
	if _, ok := hlc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "HoldingLot.tenant_id"`)}
	}
	if _, ok := hlc.mutation.HoldingID(); !ok {
		return &ValidationError{Name: "holding_id", err: errors.New(`ent: missing required field "HoldingLot.holding_id"`)}
	}
	if _, ok := hlc.mutation.SecurityID(); !ok {
		return &ValidationError{Name: "security_id", err: errors.New(`ent: missing required field "HoldingLot.security_id"`)}
	}
	if _, ok := hlc.mutation.AcquiredDate(); !ok {
		return &ValidationError{Name: "acquired_date", err: errors.New(`ent: missing required field "HoldingLot.acquired_date"`)}
	}
	if _, ok := hlc.mutation.AcquiredTradeID(); !ok {
		return &ValidationError{Name: "acquired_trade_id", err: errors.New(`ent: missing required field "HoldingLot.acquired_trade_id"`)}
	}
	if _, ok := hlc.mutation.PriceCents(); !ok {
		return &ValidationError{Name: "price_cents", err: errors.New(`ent: missing required field "HoldingLot.price_cents"`)}
	}
	if _, ok := hlc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "HoldingLot.quantity"`)}
	}
	if _, ok := hlc.mutation.RemainingQuantity(); !ok {
		return &ValidationError{Name: "remaining_quantity", err: errors.New(`ent: missing required field "HoldingLot.remaining_quantity"`)}
	}
	if _, ok := hlc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HoldingLot.created_at"`)}
	}
	return nil
}

func (hlc *HoldingLotCreate) sqlSave(ctx context.Context) (*HoldingLot, error) {
	if err := hlc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hlc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hlc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	hlc.mutation.id = &_node.ID
	hlc.mutation.done = true
	return _node, nil
}

func (hlc *HoldingLotCreate) createSpec() (*HoldingLot, *sqlgraph.CreateSpec) {
	var (
		_node = &HoldingLot{config: hlc.config}
		_spec = sqlgraph.NewCreateSpec(holdinglot.Table, sqlgraph.NewFieldSpec(holdinglot.FieldID, field.TypeUUID))
	)
	if id, ok := hlc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := hlc.mutation.TenantID(); ok {
		_spec.SetField(holdinglot.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := hlc.mutation.HoldingID(); ok {
		_spec.SetField(holdinglot.FieldHoldingID, field.TypeUUID, value)
		_node.HoldingID = value
	}
	if value, ok := hlc.mutation.SecurityID(); ok {
		_spec.SetField(holdinglot.FieldSecurityID, field.TypeUUID, value)
		_node.SecurityID = value
	}
	if value, ok := hlc.mutation.AcquiredDate(); ok {
		_spec.SetField(holdinglot.FieldAcquiredDate, field.TypeTime, value)
		_node.AcquiredDate = value
	}
	if value, ok := hlc.mutation.AcquiredTradeID(); ok {
		_spec.SetField(holdinglot.FieldAcquiredTradeID, field.TypeUUID, value)
		_node.AcquiredTradeID = value
	}
	if value, ok := hlc.mutation.PriceCents(); ok {
		_spec.SetField(holdinglot.FieldPriceCents, field.TypeInt64, value)
		_node.PriceCents = value
	}
	if value, ok := hlc.mutation.Quantity(); ok {
		_spec.SetField(holdinglot.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := hlc.mutation.RemainingQuantity(); ok {
		_spec.SetField(holdinglot.FieldRemainingQuantity, field.TypeFloat64, value)
		_node.RemainingQuantity = value
	}
	if value, ok := hlc.mutation.CreatedAt(); ok {
		_spec.SetField(holdinglot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// HoldingLotCreateBulk is the builder for creating many HoldingLot entities in bulk.
type HoldingLotCreateBulk struct {
	config
	err      error
	builders []*HoldingLotCreate
}

// Save creates the HoldingLot entities in the database.
func (hlcb *HoldingLotCreateBulk) Save(ctx context.Context) ([]*HoldingLot, error) {
	if hlcb.err != nil {
		return nil, hlcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hlcb.builders))
	nodes := make([]*HoldingLot, len(hlcb.builders))
	mutators := make([]Mutator, len(hlcb.builders))
	for i := range hlcb.builders {
		func(i int, root context.Context) {
			builder := hlcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HoldingLotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hlcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hlcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hlcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hlcb *HoldingLotCreateBulk) SaveX(ctx context.Context) []*HoldingLot {
	v, err := hlcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hlcb *HoldingLotCreateBulk) Exec(ctx context.Context) error {
	_, err := hlcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hlcb *HoldingLotCreateBulk) ExecX(ctx context.Context) {
	if err := hlcb.Exec(ctx); err != nil {
		panic(err)
	}
}
