// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/holding/ent/predicate"
	"github.com/yucai/server/internal/holding/ent/security"
	"github.com/yucai/server/internal/holding/ent/securitypricehistory"
)

// SecurityPriceHistoryQuery is the builder for querying SecurityPriceHistory entities.
type SecurityPriceHistoryQuery struct {
	config
	ctx          *QueryContext
	order        []securitypricehistory.OrderOption
	inters       []Interceptor
	predicates   []predicate.SecurityPriceHistory
	withSecurity *SecurityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SecurityPriceHistoryQuery builder.
func (sphq *SecurityPriceHistoryQuery) Where(ps ...predicate.SecurityPriceHistory) *SecurityPriceHistoryQuery {
	sphq.predicates = append(sphq.predicates, ps...)
	return sphq
}

// Limit the number of records to be returned by this query.
func (sphq *SecurityPriceHistoryQuery) Limit(limit int) *SecurityPriceHistoryQuery {
	sphq.ctx.Limit = &limit
	return sphq
}

// Offset to start from.
func (sphq *SecurityPriceHistoryQuery) Offset(offset int) *SecurityPriceHistoryQuery {
	sphq.ctx.Offset = &offset
	return sphq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sphq *SecurityPriceHistoryQuery) Unique(unique bool) *SecurityPriceHistoryQuery {
	sphq.ctx.Unique = &unique
	return sphq
}

// Order specifies how the records should be ordered.
func (sphq *SecurityPriceHistoryQuery) Order(o ...securitypricehistory.OrderOption) *SecurityPriceHistoryQuery {
	sphq.order = append(sphq.order, o...)
	return sphq
}

// QuerySecurity chains the current query on the "security" edge.
func (sphq *SecurityPriceHistoryQuery) QuerySecurity() *SecurityQuery {
	query := (&SecurityClient{config: sphq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sphq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sphq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(securitypricehistory.Table, securitypricehistory.FieldID, selector),
			sqlgraph.To(security.Table, security.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, securitypricehistory.SecurityTable, securitypricehistory.SecurityColumn),
		)
		fromU = sqlgraph.SetNeighbors(sphq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SecurityPriceHistory entity from the query.
// Returns a *NotFoundError when no SecurityPriceHistory was found.
func (sphq *SecurityPriceHistoryQuery) First(ctx context.Context) (*SecurityPriceHistory, error) {
	nodes, err := sphq.Limit(1).All(setContextOp(ctx, sphq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{securitypricehistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) FirstX(ctx context.Context) *SecurityPriceHistory {
	node, err := sphq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SecurityPriceHistory ID from the query.
// Returns a *NotFoundError when no SecurityPriceHistory ID was found.
func (sphq *SecurityPriceHistoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sphq.Limit(1).IDs(setContextOp(ctx, sphq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{securitypricehistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := sphq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SecurityPriceHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SecurityPriceHistory entity is found.
// Returns a *NotFoundError when no SecurityPriceHistory entities are found.
func (sphq *SecurityPriceHistoryQuery) Only(ctx context.Context) (*SecurityPriceHistory, error) {
	nodes, err := sphq.Limit(2).All(setContextOp(ctx, sphq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{securitypricehistory.Label}
	default:
		return nil, &NotSingularError{securitypricehistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) OnlyX(ctx context.Context) *SecurityPriceHistory {
	node, err := sphq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SecurityPriceHistory ID in the query.
// Returns a *NotSingularError when more than one SecurityPriceHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (sphq *SecurityPriceHistoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sphq.Limit(2).IDs(setContextOp(ctx, sphq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{securitypricehistory.Label}
	default:
		err = &NotSingularError{securitypricehistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := sphq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SecurityPriceHistories.
func (sphq *SecurityPriceHistoryQuery) All(ctx context.Context) ([]*SecurityPriceHistory, error) {
	ctx = setContextOp(ctx, sphq.ctx, ent.OpQueryAll)
	if err := sphq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SecurityPriceHistory, *SecurityPriceHistoryQuery]()
	return withInterceptors[[]*SecurityPriceHistory](ctx, sphq, qr, sphq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) AllX(ctx context.Context) []*SecurityPriceHistory {
	nodes, err := sphq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SecurityPriceHistory IDs.
func (sphq *SecurityPriceHistoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if sphq.ctx.Unique == nil && sphq.path != nil {
		sphq.Unique(true)
	}
	ctx = setContextOp(ctx, sphq.ctx, ent.OpQueryIDs)
	if err = sphq.Select(securitypricehistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := sphq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sphq *SecurityPriceHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sphq.ctx, ent.OpQueryCount)
	if err := sphq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sphq, querierCount[*SecurityPriceHistoryQuery](), sphq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) CountX(ctx context.Context) int {
	count, err := sphq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sphq *SecurityPriceHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sphq.ctx, ent.OpQueryExist)
	switch _, err := sphq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sphq *SecurityPriceHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := sphq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SecurityPriceHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sphq *SecurityPriceHistoryQuery) Clone() *SecurityPriceHistoryQuery {
	if sphq == nil {
		return nil
	}
	return &SecurityPriceHistoryQuery{
		config:       sphq.config,
		ctx:          sphq.ctx.Clone(),
		order:        append([]securitypricehistory.OrderOption{}, sphq.order...),
		inters:       append([]Interceptor{}, sphq.inters...),
		predicates:   append([]predicate.SecurityPriceHistory{}, sphq.predicates...),
		withSecurity: sphq.withSecurity.Clone(),
		// clone intermediate query.
		sql:  sphq.sql.Clone(),
		path: sphq.path,
	}
}

// WithSecurity tells the query-builder to eager-load the nodes that are connected to
// the "security" edge. The optional arguments are used to configure the query builder of the edge.
func (sphq *SecurityPriceHistoryQuery) WithSecurity(opts ...func(*SecurityQuery)) *SecurityPriceHistoryQuery {
	query := (&SecurityClient{config: sphq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sphq.withSecurity = query
	return sphq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SecurityID uuid.UUID `json:"security_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SecurityPriceHistory.Query().
//		GroupBy(securitypricehistory.FieldSecurityID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sphq *SecurityPriceHistoryQuery) GroupBy(field string, fields ...string) *SecurityPriceHistoryGroupBy {
	sphq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SecurityPriceHistoryGroupBy{build: sphq}
	grbuild.flds = &sphq.ctx.Fields
	grbuild.label = securitypricehistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SecurityID uuid.UUID `json:"security_id,omitempty"`
//	}
//
//	client.SecurityPriceHistory.Query().
//		Select(securitypricehistory.FieldSecurityID).
//		Scan(ctx, &v)
func (sphq *SecurityPriceHistoryQuery) Select(fields ...string) *SecurityPriceHistorySelect {
	sphq.ctx.Fields = append(sphq.ctx.Fields, fields...)
	sbuild := &SecurityPriceHistorySelect{SecurityPriceHistoryQuery: sphq}
	sbuild.label = securitypricehistory.Label
	sbuild.flds, sbuild.scan = &sphq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SecurityPriceHistorySelect configured with the given aggregations.
func (sphq *SecurityPriceHistoryQuery) Aggregate(fns ...AggregateFunc) *SecurityPriceHistorySelect {
	return sphq.Select().Aggregate(fns...)
}

func (sphq *SecurityPriceHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sphq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sphq); err != nil {
				return err
			}
		}
	}
	for _, f := range sphq.ctx.Fields {
		if !securitypricehistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sphq.path != nil {
		prev, err := sphq.path(ctx)
		if err != nil {
			return err
		}
		sphq.sql = prev
	}
	return nil
}

func (sphq *SecurityPriceHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SecurityPriceHistory, error) {
	var (
		nodes       = []*SecurityPriceHistory{}
		_spec       = sphq.querySpec()
		loadedTypes = [1]bool{
			sphq.withSecurity != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SecurityPriceHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SecurityPriceHistory{config: sphq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sphq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sphq.withSecurity; query != nil {
		if err := sphq.loadSecurity(ctx, query, nodes, nil,
			func(n *SecurityPriceHistory, e *Security) { n.Edges.Security = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sphq *SecurityPriceHistoryQuery) loadSecurity(ctx context.Context, query *SecurityQuery, nodes []*SecurityPriceHistory, init func(*SecurityPriceHistory), assign func(*SecurityPriceHistory, *Security)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*SecurityPriceHistory)
	for i := range nodes {
		fk := nodes[i].SecurityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(security.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "security_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sphq *SecurityPriceHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sphq.querySpec()
	_spec.Node.Columns = sphq.ctx.Fields
	if len(sphq.ctx.Fields) > 0 {
		_spec.Unique = sphq.ctx.Unique != nil && *sphq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sphq.driver, _spec)
}

func (sphq *SecurityPriceHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(securitypricehistory.Table, securitypricehistory.Columns, sqlgraph.NewFieldSpec(securitypricehistory.FieldID, field.TypeUUID))
	_spec.From = sphq.sql
	if unique := sphq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sphq.path != nil {
		_spec.Unique = true
	}
	if fields := sphq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, securitypricehistory.FieldID)
		for i := range fields {
			if fields[i] != securitypricehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sphq.withSecurity != nil {
			_spec.Node.AddColumnOnce(securitypricehistory.FieldSecurityID)
		}
	}
	if ps := sphq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sphq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sphq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sphq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sphq *SecurityPriceHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sphq.driver.Dialect())
	t1 := builder.Table(securitypricehistory.Table)
	columns := sphq.ctx.Fields
	if len(columns) == 0 {
		columns = securitypricehistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sphq.sql != nil {
		selector = sphq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sphq.ctx.Unique != nil && *sphq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sphq.predicates {
		p(selector)
	}
	for _, p := range sphq.order {
		p(selector)
	}
	if offset := sphq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sphq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SecurityPriceHistoryGroupBy is the group-by builder for SecurityPriceHistory entities.
type SecurityPriceHistoryGroupBy struct {
	selector
	build *SecurityPriceHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sphgb *SecurityPriceHistoryGroupBy) Aggregate(fns ...AggregateFunc) *SecurityPriceHistoryGroupBy {
	sphgb.fns = append(sphgb.fns, fns...)
	return sphgb
}

// Scan applies the selector query and scans the result into the given value.
func (sphgb *SecurityPriceHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sphgb.build.ctx, ent.OpQueryGroupBy)
	if err := sphgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SecurityPriceHistoryQuery, *SecurityPriceHistoryGroupBy](ctx, sphgb.build, sphgb, sphgb.build.inters, v)
}

func (sphgb *SecurityPriceHistoryGroupBy) sqlScan(ctx context.Context, root *SecurityPriceHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sphgb.fns))
	for _, fn := range sphgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sphgb.flds)+len(sphgb.fns))
		for _, f := range *sphgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sphgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sphgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SecurityPriceHistorySelect is the builder for selecting fields of SecurityPriceHistory entities.
type SecurityPriceHistorySelect struct {
	*SecurityPriceHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sphs *SecurityPriceHistorySelect) Aggregate(fns ...AggregateFunc) *SecurityPriceHistorySelect {
	sphs.fns = append(sphs.fns, fns...)
	return sphs
}

// Scan applies the selector query and scans the result into the given value.
func (sphs *SecurityPriceHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sphs.ctx, ent.OpQuerySelect)
	if err := sphs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SecurityPriceHistoryQuery, *SecurityPriceHistorySelect](ctx, sphs.SecurityPriceHistoryQuery, sphs, sphs.inters, v)
}

func (sphs *SecurityPriceHistorySelect) sqlScan(ctx context.Context, root *SecurityPriceHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sphs.fns))
	for _, fn := range sphs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sphs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sphs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
