// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/holding/ent/security"
	"github.com/yucai/server/internal/holding/ent/securitypricehistory"
)

// SecurityPriceHistory is the model entity for the SecurityPriceHistory schema.
type SecurityPriceHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// owning security (incl. benchmark 000300)
	SecurityID uuid.UUID `json:"security_id,omitempty"`
	// one row per security per date
	PriceDate time.Time `json:"price_date,omitempty"`
	// close price in original currency cents
	PriceCents int64 `json:"price_cents,omitempty"`
	// CurrencyCode holds the value of the "currency_code" field.
	CurrencyCode string `json:"currency_code,omitempty"`
	// sina / backfill / manual
	Source string `json:"source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SecurityPriceHistoryQuery when eager-loading is set.
	Edges        SecurityPriceHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SecurityPriceHistoryEdges holds the relations/edges for other nodes in the graph.
type SecurityPriceHistoryEdges struct {
	// Security holds the value of the security edge.
	Security *Security `json:"security,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SecurityOrErr returns the Security value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecurityPriceHistoryEdges) SecurityOrErr() (*Security, error) {
	if e.Security != nil {
		return e.Security, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: security.Label}
	}
	return nil, &NotLoadedError{edge: "security"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecurityPriceHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case securitypricehistory.FieldPriceCents:
			values[i] = new(sql.NullInt64)
		case securitypricehistory.FieldCurrencyCode, securitypricehistory.FieldSource:
			values[i] = new(sql.NullString)
		case securitypricehistory.FieldPriceDate, securitypricehistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case securitypricehistory.FieldID, securitypricehistory.FieldSecurityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecurityPriceHistory fields.
func (sph *SecurityPriceHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case securitypricehistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sph.ID = *value
			}
		case securitypricehistory.FieldSecurityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field security_id", values[i])
			} else if value != nil {
				sph.SecurityID = *value
			}
		case securitypricehistory.FieldPriceDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field price_date", values[i])
			} else if value.Valid {
				sph.PriceDate = value.Time
			}
		case securitypricehistory.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				sph.PriceCents = value.Int64
			}
		case securitypricehistory.FieldCurrencyCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_code", values[i])
			} else if value.Valid {
				sph.CurrencyCode = value.String
			}
		case securitypricehistory.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				sph.Source = value.String
			}
		case securitypricehistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sph.CreatedAt = value.Time
			}
		default:
			sph.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecurityPriceHistory.
// This includes values selected through modifiers, order, etc.
func (sph *SecurityPriceHistory) Value(name string) (ent.Value, error) {
	return sph.selectValues.Get(name)
}

// QuerySecurity queries the "security" edge of the SecurityPriceHistory entity.
func (sph *SecurityPriceHistory) QuerySecurity() *SecurityQuery {
	return NewSecurityPriceHistoryClient(sph.config).QuerySecurity(sph)
}

// Update returns a builder for updating this SecurityPriceHistory.
// Note that you need to call SecurityPriceHistory.Unwrap() before calling this method if this SecurityPriceHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (sph *SecurityPriceHistory) Update() *SecurityPriceHistoryUpdateOne {
	return NewSecurityPriceHistoryClient(sph.config).UpdateOne(sph)
}

// Unwrap unwraps the SecurityPriceHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sph *SecurityPriceHistory) Unwrap() *SecurityPriceHistory {
	_tx, ok := sph.config.driver.(*txDriver)
	if !ok {
		panic("ent: SecurityPriceHistory is not a transactional entity")
	}
	sph.config.driver = _tx.drv
	return sph
}

// String implements the fmt.Stringer.
func (sph *SecurityPriceHistory) String() string {
	var builder strings.Builder
	builder.WriteString("SecurityPriceHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sph.ID))
	builder.WriteString("security_id=")
	builder.WriteString(fmt.Sprintf("%v", sph.SecurityID))
	builder.WriteString(", ")
	builder.WriteString("price_date=")
	builder.WriteString(sph.PriceDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("price_cents=")
	builder.WriteString(fmt.Sprintf("%v", sph.PriceCents))
	builder.WriteString(", ")
	builder.WriteString("currency_code=")
	builder.WriteString(sph.CurrencyCode)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(sph.Source)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sph.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SecurityPriceHistories is a parsable slice of SecurityPriceHistory.
type SecurityPriceHistories []*SecurityPriceHistory
