// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/holding/ent/security"
)

// Security is the model entity for the Security schema.
type Security struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// stock, fund, etf, bond, gold, option, other
	SecurityType string `json:"security_type,omitempty"`
	// Exchange holds the value of the "exchange" field.
	Exchange string `json:"exchange,omitempty"`
	// CurrencyCode holds the value of the "currency_code" field.
	CurrencyCode string `json:"currency_code,omitempty"`
	// CurrentPriceCents holds the value of the "current_price_cents" field.
	CurrentPriceCents int64 `json:"current_price_cents,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Security) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case security.FieldCurrentPriceCents:
			values[i] = new(sql.NullInt64)
		case security.FieldSymbol, security.FieldName, security.FieldSecurityType, security.FieldExchange, security.FieldCurrencyCode:
			values[i] = new(sql.NullString)
		case security.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case security.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Security fields.
func (s *Security) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case security.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case security.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				s.Symbol = value.String
			}
		case security.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case security.FieldSecurityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field security_type", values[i])
			} else if value.Valid {
				s.SecurityType = value.String
			}
		case security.FieldExchange:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exchange", values[i])
			} else if value.Valid {
				s.Exchange = value.String
			}
		case security.FieldCurrencyCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_code", values[i])
			} else if value.Valid {
				s.CurrencyCode = value.String
			}
		case security.FieldCurrentPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_price_cents", values[i])
			} else if value.Valid {
				s.CurrentPriceCents = value.Int64
			}
		case security.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Security.
// This includes values selected through modifiers, order, etc.
func (s *Security) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Security.
// Note that you need to call Security.Unwrap() before calling this method if this Security
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Security) Update() *SecurityUpdateOne {
	return NewSecurityClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Security entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Security) Unwrap() *Security {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Security is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Security) String() string {
	var builder strings.Builder
	builder.WriteString("Security(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("symbol=")
	builder.WriteString(s.Symbol)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("security_type=")
	builder.WriteString(s.SecurityType)
	builder.WriteString(", ")
	builder.WriteString("exchange=")
	builder.WriteString(s.Exchange)
	builder.WriteString(", ")
	builder.WriteString("currency_code=")
	builder.WriteString(s.CurrencyCode)
	builder.WriteString(", ")
	builder.WriteString("current_price_cents=")
	builder.WriteString(fmt.Sprintf("%v", s.CurrentPriceCents))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Securities is a parsable slice of Security.
type Securities []*Security
