// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/yucai/server/internal/tag/ent/schema"
	"github.com/yucai/server/internal/tag/ent/tag"
	"github.com/yucai/server/internal/tag/ent/transactiontag"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[1].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescColor is the schema descriptor for color field.
	tagDescColor := tagFields[2].Descriptor()
	// tag.DefaultColor holds the default value on creation for the color field.
	tag.DefaultColor = tagDescColor.Default.(string)
	// tagDescVersion is the schema descriptor for version field.
	tagDescVersion := tagFields[3].Descriptor()
	// tag.DefaultVersion holds the default value on creation for the version field.
	tag.DefaultVersion = tagDescVersion.Default.(int64)
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagFields[5].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(func() time.Time)
	// tagDescUpdatedAt is the schema descriptor for updated_at field.
	tagDescUpdatedAt := tagFields[6].Descriptor()
	// tag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tag.DefaultUpdatedAt = tagDescUpdatedAt.Default.(func() time.Time)
	// tag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tag.UpdateDefaultUpdatedAt = tagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tagDescID is the schema descriptor for id field.
	tagDescID := tagFields[0].Descriptor()
	// tag.DefaultID holds the default value on creation for the id field.
	tag.DefaultID = tagDescID.Default.(func() uuid.UUID)
	transactiontagFields := schema.TransactionTag{}.Fields()
	_ = transactiontagFields
	// transactiontagDescID is the schema descriptor for id field.
	transactiontagDescID := transactiontagFields[0].Descriptor()
	// transactiontag.DefaultID holds the default value on creation for the id field.
	transactiontag.DefaultID = transactiontagDescID.Default.(func() uuid.UUID)
}
