// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/account/ent/account"
)

// Account is the model entity for the Account schema.
type Account struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// FK to tenants table — data isolation boundary
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Account display name
	Name string `json:"name,omitempty"`
	// Account type per Chinese accounting standards
	AccountType account.AccountType `json:"account_type,omitempty"`
	// User-facing account category; drives account_type
	Category account.Category `json:"category,omitempty"`
	// ISO 4217 currency code
	CurrencyCode string `json:"currency_code,omitempty"`
	// Initial balance in integer cents
	InitialBalanceCents int64 `json:"initial_balance_cents,omitempty"`
	// Current calculated balance in integer cents
	CurrentBalanceCents int64 `json:"current_balance_cents,omitempty"`
	// Account ownership type
	Ownership account.Ownership `json:"ownership,omitempty"`
	// Icon name or emoji
	Icon string `json:"icon,omitempty"`
	// Hex color for display
	Color string `json:"color,omitempty"`
	// Chart of accounts code
	ChartCode string `json:"chart_code,omitempty"`
	// Parent account for hierarchical structure
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// Bank or financial institution name
	Institution string `json:"institution,omitempty"`
	// Credit limit in cents (for credit cards/lines)
	CreditLimitCents int64 `json:"credit_limit_cents,omitempty"`
	// Card/account last digits (financial types)
	CardNumberTail string `json:"card_number_tail,omitempty"`
	// Free-form notes
	Notes string `json:"notes,omitempty"`
	// Account opening date (financial types)
	OpeningDate *time.Time `json:"opening_date,omitempty"`
	// Annual rate %: savings/fixed/loan rate, credit card APR
	InterestRate *float64 `json:"interest_rate,omitempty"`
	// Credit card billing day (1-31)
	CreditBillingDay *int `json:"credit_billing_day,omitempty"`
	// Credit card repayment day (1-31)
	CreditRepaymentDay *int `json:"credit_repayment_day,omitempty"`
	// Credit card annual fee in cents
	CreditAnnualFeeCents *int64 `json:"credit_annual_fee_cents,omitempty"`
	// Investment total cost basis in cents
	InvestCostCents *int64 `json:"invest_cost_cents,omitempty"`
	// Investment current market value in cents
	InvestMarketValueCents *int64 `json:"invest_market_value_cents,omitempty"`
	// Investment year-to-date return rate (%)
	InvestReturnYtd *float64 `json:"invest_return_ytd,omitempty"`
	// Fixed deposit principal in cents
	FixedPrincipalCents *int64 `json:"fixed_principal_cents,omitempty"`
	// Fixed deposit start (value) date
	FixedStartDate *time.Time `json:"fixed_start_date,omitempty"`
	// Fixed deposit maturity date
	FixedMaturityDate *time.Time `json:"fixed_maturity_date,omitempty"`
	// Fixed deposit term in months
	FixedTermMonths *int `json:"fixed_term_months,omitempty"`
	// Gold/FX product type (e.g. gold, usd)
	GoldProductType string `json:"gold_product_type,omitempty"`
	// Gold/FX holding quantity
	GoldQuantity *float64 `json:"gold_quantity,omitempty"`
	// Gold/FX buy price in cents
	GoldBuyPriceCents *int64 `json:"gold_buy_price_cents,omitempty"`
	// Gold/FX current price in cents
	GoldCurrentPriceCents *int64 `json:"gold_current_price_cents,omitempty"`
	// Real estate purchase price in cents
	EstatePurchasePriceCents *int64 `json:"estate_purchase_price_cents,omitempty"`
	// Real estate current appraised value in cents
	EstateCurrentValueCents *int64 `json:"estate_current_value_cents,omitempty"`
	// Real estate purchase date
	EstatePurchaseDate *time.Time `json:"estate_purchase_date,omitempty"`
	// Real estate depreciation rate (%)
	EstateDepreciationRate *float64 `json:"estate_depreciation_rate,omitempty"`
	// Loan original principal in cents
	LoanOriginalCents *int64 `json:"loan_original_cents,omitempty"`
	// Loan remaining principal in cents
	LoanRemainingCents *int64 `json:"loan_remaining_cents,omitempty"`
	// Loan monthly payment in cents
	LoanMonthlyCents *int64 `json:"loan_monthly_cents,omitempty"`
	// Loan next payment date
	LoanNextPaymentDate *time.Time `json:"loan_next_payment_date,omitempty"`
	// Account status
	Status account.Status `json:"status,omitempty"`
	// Optimistic locking version
	Version int64 `json:"version,omitempty"`
	// Soft delete timestamp
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Record creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update time
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Account) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case account.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case account.FieldInterestRate, account.FieldInvestReturnYtd, account.FieldGoldQuantity, account.FieldEstateDepreciationRate:
			values[i] = new(sql.NullFloat64)
		case account.FieldInitialBalanceCents, account.FieldCurrentBalanceCents, account.FieldCreditLimitCents, account.FieldCreditBillingDay, account.FieldCreditRepaymentDay, account.FieldCreditAnnualFeeCents, account.FieldInvestCostCents, account.FieldInvestMarketValueCents, account.FieldFixedPrincipalCents, account.FieldFixedTermMonths, account.FieldGoldBuyPriceCents, account.FieldGoldCurrentPriceCents, account.FieldEstatePurchasePriceCents, account.FieldEstateCurrentValueCents, account.FieldLoanOriginalCents, account.FieldLoanRemainingCents, account.FieldLoanMonthlyCents, account.FieldVersion:
			values[i] = new(sql.NullInt64)
		case account.FieldName, account.FieldAccountType, account.FieldCategory, account.FieldCurrencyCode, account.FieldOwnership, account.FieldIcon, account.FieldColor, account.FieldChartCode, account.FieldInstitution, account.FieldCardNumberTail, account.FieldNotes, account.FieldGoldProductType, account.FieldStatus:
			values[i] = new(sql.NullString)
		case account.FieldOpeningDate, account.FieldFixedStartDate, account.FieldFixedMaturityDate, account.FieldEstatePurchaseDate, account.FieldLoanNextPaymentDate, account.FieldDeletedAt, account.FieldCreatedAt, account.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case account.FieldID, account.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Account fields.
func (a *Account) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case account.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				a.ID = *value
			}
		case account.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				a.TenantID = *value
			}
		case account.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case account.FieldAccountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_type", values[i])
			} else if value.Valid {
				a.AccountType = account.AccountType(value.String)
			}
		case account.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				a.Category = account.Category(value.String)
			}
		case account.FieldCurrencyCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_code", values[i])
			} else if value.Valid {
				a.CurrencyCode = value.String
			}
		case account.FieldInitialBalanceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field initial_balance_cents", values[i])
			} else if value.Valid {
				a.InitialBalanceCents = value.Int64
			}
		case account.FieldCurrentBalanceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_balance_cents", values[i])
			} else if value.Valid {
				a.CurrentBalanceCents = value.Int64
			}
		case account.FieldOwnership:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ownership", values[i])
			} else if value.Valid {
				a.Ownership = account.Ownership(value.String)
			}
		case account.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				a.Icon = value.String
			}
		case account.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				a.Color = value.String
			}
		case account.FieldChartCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chart_code", values[i])
			} else if value.Valid {
				a.ChartCode = value.String
			}
		case account.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				a.ParentID = new(uuid.UUID)
				*a.ParentID = *value.S.(*uuid.UUID)
			}
		case account.FieldInstitution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field institution", values[i])
			} else if value.Valid {
				a.Institution = value.String
			}
		case account.FieldCreditLimitCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_limit_cents", values[i])
			} else if value.Valid {
				a.CreditLimitCents = value.Int64
			}
		case account.FieldCardNumberTail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field card_number_tail", values[i])
			} else if value.Valid {
				a.CardNumberTail = value.String
			}
		case account.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				a.Notes = value.String
			}
		case account.FieldOpeningDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opening_date", values[i])
			} else if value.Valid {
				a.OpeningDate = new(time.Time)
				*a.OpeningDate = value.Time
			}
		case account.FieldInterestRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field interest_rate", values[i])
			} else if value.Valid {
				a.InterestRate = new(float64)
				*a.InterestRate = value.Float64
			}
		case account.FieldCreditBillingDay:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_billing_day", values[i])
			} else if value.Valid {
				a.CreditBillingDay = new(int)
				*a.CreditBillingDay = int(value.Int64)
			}
		case account.FieldCreditRepaymentDay:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_repayment_day", values[i])
			} else if value.Valid {
				a.CreditRepaymentDay = new(int)
				*a.CreditRepaymentDay = int(value.Int64)
			}
		case account.FieldCreditAnnualFeeCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_annual_fee_cents", values[i])
			} else if value.Valid {
				a.CreditAnnualFeeCents = new(int64)
				*a.CreditAnnualFeeCents = value.Int64
			}
		case account.FieldInvestCostCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invest_cost_cents", values[i])
			} else if value.Valid {
				a.InvestCostCents = new(int64)
				*a.InvestCostCents = value.Int64
			}
		case account.FieldInvestMarketValueCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invest_market_value_cents", values[i])
			} else if value.Valid {
				a.InvestMarketValueCents = new(int64)
				*a.InvestMarketValueCents = value.Int64
			}
		case account.FieldInvestReturnYtd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invest_return_ytd", values[i])
			} else if value.Valid {
				a.InvestReturnYtd = new(float64)
				*a.InvestReturnYtd = value.Float64
			}
		case account.FieldFixedPrincipalCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fixed_principal_cents", values[i])
			} else if value.Valid {
				a.FixedPrincipalCents = new(int64)
				*a.FixedPrincipalCents = value.Int64
			}
		case account.FieldFixedStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fixed_start_date", values[i])
			} else if value.Valid {
				a.FixedStartDate = new(time.Time)
				*a.FixedStartDate = value.Time
			}
		case account.FieldFixedMaturityDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fixed_maturity_date", values[i])
			} else if value.Valid {
				a.FixedMaturityDate = new(time.Time)
				*a.FixedMaturityDate = value.Time
			}
		case account.FieldFixedTermMonths:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fixed_term_months", values[i])
			} else if value.Valid {
				a.FixedTermMonths = new(int)
				*a.FixedTermMonths = int(value.Int64)
			}
		case account.FieldGoldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gold_product_type", values[i])
			} else if value.Valid {
				a.GoldProductType = value.String
			}
		case account.FieldGoldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gold_quantity", values[i])
			} else if value.Valid {
				a.GoldQuantity = new(float64)
				*a.GoldQuantity = value.Float64
			}
		case account.FieldGoldBuyPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gold_buy_price_cents", values[i])
			} else if value.Valid {
				a.GoldBuyPriceCents = new(int64)
				*a.GoldBuyPriceCents = value.Int64
			}
		case account.FieldGoldCurrentPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gold_current_price_cents", values[i])
			} else if value.Valid {
				a.GoldCurrentPriceCents = new(int64)
				*a.GoldCurrentPriceCents = value.Int64
			}
		case account.FieldEstatePurchasePriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field estate_purchase_price_cents", values[i])
			} else if value.Valid {
				a.EstatePurchasePriceCents = new(int64)
				*a.EstatePurchasePriceCents = value.Int64
			}
		case account.FieldEstateCurrentValueCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field estate_current_value_cents", values[i])
			} else if value.Valid {
				a.EstateCurrentValueCents = new(int64)
				*a.EstateCurrentValueCents = value.Int64
			}
		case account.FieldEstatePurchaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field estate_purchase_date", values[i])
			} else if value.Valid {
				a.EstatePurchaseDate = new(time.Time)
				*a.EstatePurchaseDate = value.Time
			}
		case account.FieldEstateDepreciationRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estate_depreciation_rate", values[i])
			} else if value.Valid {
				a.EstateDepreciationRate = new(float64)
				*a.EstateDepreciationRate = value.Float64
			}
		case account.FieldLoanOriginalCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field loan_original_cents", values[i])
			} else if value.Valid {
				a.LoanOriginalCents = new(int64)
				*a.LoanOriginalCents = value.Int64
			}
		case account.FieldLoanRemainingCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field loan_remaining_cents", values[i])
			} else if value.Valid {
				a.LoanRemainingCents = new(int64)
				*a.LoanRemainingCents = value.Int64
			}
		case account.FieldLoanMonthlyCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field loan_monthly_cents", values[i])
			} else if value.Valid {
				a.LoanMonthlyCents = new(int64)
				*a.LoanMonthlyCents = value.Int64
			}
		case account.FieldLoanNextPaymentDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field loan_next_payment_date", values[i])
			} else if value.Valid {
				a.LoanNextPaymentDate = new(time.Time)
				*a.LoanNextPaymentDate = value.Time
			}
		case account.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				a.Status = account.Status(value.String)
			}
		case account.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				a.Version = value.Int64
			}
		case account.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				a.DeletedAt = new(time.Time)
				*a.DeletedAt = value.Time
			}
		case account.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		case account.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				a.UpdatedAt = value.Time
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Account.
// This includes values selected through modifiers, order, etc.
func (a *Account) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// Update returns a builder for updating this Account.
// Note that you need to call Account.Unwrap() before calling this method if this Account
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Account) Update() *AccountUpdateOne {
	return NewAccountClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Account entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Account) Unwrap() *Account {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Account is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Account) String() string {
	var builder strings.Builder
	builder.WriteString("Account(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", a.TenantID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteString(", ")
	builder.WriteString("account_type=")
	builder.WriteString(fmt.Sprintf("%v", a.AccountType))
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", a.Category))
	builder.WriteString(", ")
	builder.WriteString("currency_code=")
	builder.WriteString(a.CurrencyCode)
	builder.WriteString(", ")
	builder.WriteString("initial_balance_cents=")
	builder.WriteString(fmt.Sprintf("%v", a.InitialBalanceCents))
	builder.WriteString(", ")
	builder.WriteString("current_balance_cents=")
	builder.WriteString(fmt.Sprintf("%v", a.CurrentBalanceCents))
	builder.WriteString(", ")
	builder.WriteString("ownership=")
	builder.WriteString(fmt.Sprintf("%v", a.Ownership))
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(a.Icon)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(a.Color)
	builder.WriteString(", ")
	builder.WriteString("chart_code=")
	builder.WriteString(a.ChartCode)
	builder.WriteString(", ")
	if v := a.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("institution=")
	builder.WriteString(a.Institution)
	builder.WriteString(", ")
	builder.WriteString("credit_limit_cents=")
	builder.WriteString(fmt.Sprintf("%v", a.CreditLimitCents))
	builder.WriteString(", ")
	builder.WriteString("card_number_tail=")
	builder.WriteString(a.CardNumberTail)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(a.Notes)
	builder.WriteString(", ")
	if v := a.OpeningDate; v != nil {
		builder.WriteString("opening_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := a.InterestRate; v != nil {
		builder.WriteString("interest_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.CreditBillingDay; v != nil {
		builder.WriteString("credit_billing_day=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.CreditRepaymentDay; v != nil {
		builder.WriteString("credit_repayment_day=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.CreditAnnualFeeCents; v != nil {
		builder.WriteString("credit_annual_fee_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.InvestCostCents; v != nil {
		builder.WriteString("invest_cost_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.InvestMarketValueCents; v != nil {
		builder.WriteString("invest_market_value_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.InvestReturnYtd; v != nil {
		builder.WriteString("invest_return_ytd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.FixedPrincipalCents; v != nil {
		builder.WriteString("fixed_principal_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.FixedStartDate; v != nil {
		builder.WriteString("fixed_start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := a.FixedMaturityDate; v != nil {
		builder.WriteString("fixed_maturity_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := a.FixedTermMonths; v != nil {
		builder.WriteString("fixed_term_months=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("gold_product_type=")
	builder.WriteString(a.GoldProductType)
	builder.WriteString(", ")
	if v := a.GoldQuantity; v != nil {
		builder.WriteString("gold_quantity=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.GoldBuyPriceCents; v != nil {
		builder.WriteString("gold_buy_price_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.GoldCurrentPriceCents; v != nil {
		builder.WriteString("gold_current_price_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.EstatePurchasePriceCents; v != nil {
		builder.WriteString("estate_purchase_price_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.EstateCurrentValueCents; v != nil {
		builder.WriteString("estate_current_value_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.EstatePurchaseDate; v != nil {
		builder.WriteString("estate_purchase_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := a.EstateDepreciationRate; v != nil {
		builder.WriteString("estate_depreciation_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.LoanOriginalCents; v != nil {
		builder.WriteString("loan_original_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.LoanRemainingCents; v != nil {
		builder.WriteString("loan_remaining_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.LoanMonthlyCents; v != nil {
		builder.WriteString("loan_monthly_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.LoanNextPaymentDate; v != nil {
		builder.WriteString("loan_next_payment_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", a.Status))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", a.Version))
	builder.WriteString(", ")
	if v := a.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(a.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Accounts is a parsable slice of Account.
type Accounts []*Account
