// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yucai/server/internal/account/ent/chartofaccounts"
	"github.com/yucai/server/internal/account/ent/predicate"
)

// ChartOfAccountsDelete is the builder for deleting a ChartOfAccounts entity.
type ChartOfAccountsDelete struct {
	config
	hooks    []Hook
	mutation *ChartOfAccountsMutation
}

// Where appends a list predicates to the ChartOfAccountsDelete builder.
func (coad *ChartOfAccountsDelete) Where(ps ...predicate.ChartOfAccounts) *ChartOfAccountsDelete {
	coad.mutation.Where(ps...)
	return coad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (coad *ChartOfAccountsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, coad.sqlExec, coad.mutation, coad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (coad *ChartOfAccountsDelete) ExecX(ctx context.Context) int {
	n, err := coad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (coad *ChartOfAccountsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chartofaccounts.Table, sqlgraph.NewFieldSpec(chartofaccounts.FieldID, field.TypeUUID))
	if ps := coad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, coad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	coad.mutation.done = true
	return affected, err
}

// ChartOfAccountsDeleteOne is the builder for deleting a single ChartOfAccounts entity.
type ChartOfAccountsDeleteOne struct {
	coad *ChartOfAccountsDelete
}

// Where appends a list predicates to the ChartOfAccountsDelete builder.
func (coado *ChartOfAccountsDeleteOne) Where(ps ...predicate.ChartOfAccounts) *ChartOfAccountsDeleteOne {
	coado.coad.mutation.Where(ps...)
	return coado
}

// Exec executes the deletion query.
func (coado *ChartOfAccountsDeleteOne) Exec(ctx context.Context) error {
	n, err := coado.coad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chartofaccounts.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (coado *ChartOfAccountsDeleteOne) ExecX(ctx context.Context) {
	if err := coado.Exec(ctx); err != nil {
		panic(err)
	}
}
