// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yucai/server/internal/debt/ent/paymentschedule"
	"github.com/yucai/server/internal/debt/ent/predicate"
)

// PaymentScheduleDelete is the builder for deleting a PaymentSchedule entity.
type PaymentScheduleDelete struct {
	config
	hooks    []Hook
	mutation *PaymentScheduleMutation
}

// Where appends a list predicates to the PaymentScheduleDelete builder.
func (psd *PaymentScheduleDelete) Where(ps ...predicate.PaymentSchedule) *PaymentScheduleDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PaymentScheduleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PaymentScheduleDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PaymentScheduleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentschedule.Table, sqlgraph.NewFieldSpec(paymentschedule.FieldID, field.TypeUUID))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PaymentScheduleDeleteOne is the builder for deleting a single PaymentSchedule entity.
type PaymentScheduleDeleteOne struct {
	psd *PaymentScheduleDelete
}

// Where appends a list predicates to the PaymentScheduleDelete builder.
func (psdo *PaymentScheduleDeleteOne) Where(ps ...predicate.PaymentSchedule) *PaymentScheduleDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PaymentScheduleDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentschedule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PaymentScheduleDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
