// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/goal/ent/goalprogresssnapshot"
	"github.com/yucai/server/internal/goal/ent/predicate"
)

// GoalProgressSnapshotUpdate is the builder for updating GoalProgressSnapshot entities.
type GoalProgressSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *GoalProgressSnapshotMutation
}

// Where appends a list predicates to the GoalProgressSnapshotUpdate builder.
func (gpsu *GoalProgressSnapshotUpdate) Where(ps ...predicate.GoalProgressSnapshot) *GoalProgressSnapshotUpdate {
	gpsu.mutation.Where(ps...)
	return gpsu
}

// SetGoalID sets the "goal_id" field.
func (gpsu *GoalProgressSnapshotUpdate) SetGoalID(u uuid.UUID) *GoalProgressSnapshotUpdate {
	gpsu.mutation.SetGoalID(u)
	return gpsu
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (gpsu *GoalProgressSnapshotUpdate) SetNillableGoalID(u *uuid.UUID) *GoalProgressSnapshotUpdate {
	if u != nil {
		gpsu.SetGoalID(*u)
	}
	return gpsu
}

// SetSnapshotDate sets the "snapshot_date" field.
func (gpsu *GoalProgressSnapshotUpdate) SetSnapshotDate(t time.Time) *GoalProgressSnapshotUpdate {
	gpsu.mutation.SetSnapshotDate(t)
	return gpsu
}

// SetNillableSnapshotDate sets the "snapshot_date" field if the given value is not nil.
func (gpsu *GoalProgressSnapshotUpdate) SetNillableSnapshotDate(t *time.Time) *GoalProgressSnapshotUpdate {
	if t != nil {
		gpsu.SetSnapshotDate(*t)
	}
	return gpsu
}

// SetCurrentAmountCents sets the "current_amount_cents" field.
func (gpsu *GoalProgressSnapshotUpdate) SetCurrentAmountCents(i int64) *GoalProgressSnapshotUpdate {
	gpsu.mutation.ResetCurrentAmountCents()
	gpsu.mutation.SetCurrentAmountCents(i)
	return gpsu
}

// SetNillableCurrentAmountCents sets the "current_amount_cents" field if the given value is not nil.
func (gpsu *GoalProgressSnapshotUpdate) SetNillableCurrentAmountCents(i *int64) *GoalProgressSnapshotUpdate {
	if i != nil {
		gpsu.SetCurrentAmountCents(*i)
	}
	return gpsu
}

// AddCurrentAmountCents adds i to the "current_amount_cents" field.
func (gpsu *GoalProgressSnapshotUpdate) AddCurrentAmountCents(i int64) *GoalProgressSnapshotUpdate {
	gpsu.mutation.AddCurrentAmountCents(i)
	return gpsu
}

// Mutation returns the GoalProgressSnapshotMutation object of the builder.
func (gpsu *GoalProgressSnapshotUpdate) Mutation() *GoalProgressSnapshotMutation {
	return gpsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gpsu *GoalProgressSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, gpsu.sqlSave, gpsu.mutation, gpsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gpsu *GoalProgressSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := gpsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gpsu *GoalProgressSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := gpsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gpsu *GoalProgressSnapshotUpdate) ExecX(ctx context.Context) {
	if err := gpsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gpsu *GoalProgressSnapshotUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(goalprogresssnapshot.Table, goalprogresssnapshot.Columns, sqlgraph.NewFieldSpec(goalprogresssnapshot.FieldID, field.TypeUUID))
	if ps := gpsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gpsu.mutation.GoalID(); ok {
		_spec.SetField(goalprogresssnapshot.FieldGoalID, field.TypeUUID, value)
	}
	if value, ok := gpsu.mutation.SnapshotDate(); ok {
		_spec.SetField(goalprogresssnapshot.FieldSnapshotDate, field.TypeTime, value)
	}
	if value, ok := gpsu.mutation.CurrentAmountCents(); ok {
		_spec.SetField(goalprogresssnapshot.FieldCurrentAmountCents, field.TypeInt64, value)
	}
	if value, ok := gpsu.mutation.AddedCurrentAmountCents(); ok {
		_spec.AddField(goalprogresssnapshot.FieldCurrentAmountCents, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gpsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goalprogresssnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gpsu.mutation.done = true
	return n, nil
}

// GoalProgressSnapshotUpdateOne is the builder for updating a single GoalProgressSnapshot entity.
type GoalProgressSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalProgressSnapshotMutation
}

// SetGoalID sets the "goal_id" field.
func (gpsuo *GoalProgressSnapshotUpdateOne) SetGoalID(u uuid.UUID) *GoalProgressSnapshotUpdateOne {
	gpsuo.mutation.SetGoalID(u)
	return gpsuo
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (gpsuo *GoalProgressSnapshotUpdateOne) SetNillableGoalID(u *uuid.UUID) *GoalProgressSnapshotUpdateOne {
	if u != nil {
		gpsuo.SetGoalID(*u)
	}
	return gpsuo
}

// SetSnapshotDate sets the "snapshot_date" field.
func (gpsuo *GoalProgressSnapshotUpdateOne) SetSnapshotDate(t time.Time) *GoalProgressSnapshotUpdateOne {
	gpsuo.mutation.SetSnapshotDate(t)
	return gpsuo
}

// SetNillableSnapshotDate sets the "snapshot_date" field if the given value is not nil.
func (gpsuo *GoalProgressSnapshotUpdateOne) SetNillableSnapshotDate(t *time.Time) *GoalProgressSnapshotUpdateOne {
	if t != nil {
		gpsuo.SetSnapshotDate(*t)
	}
	return gpsuo
}

// SetCurrentAmountCents sets the "current_amount_cents" field.
func (gpsuo *GoalProgressSnapshotUpdateOne) SetCurrentAmountCents(i int64) *GoalProgressSnapshotUpdateOne {
	gpsuo.mutation.ResetCurrentAmountCents()
	gpsuo.mutation.SetCurrentAmountCents(i)
	return gpsuo
}

// SetNillableCurrentAmountCents sets the "current_amount_cents" field if the given value is not nil.
func (gpsuo *GoalProgressSnapshotUpdateOne) SetNillableCurrentAmountCents(i *int64) *GoalProgressSnapshotUpdateOne {
	if i != nil {
		gpsuo.SetCurrentAmountCents(*i)
	}
	return gpsuo
}

// AddCurrentAmountCents adds i to the "current_amount_cents" field.
func (gpsuo *GoalProgressSnapshotUpdateOne) AddCurrentAmountCents(i int64) *GoalProgressSnapshotUpdateOne {
	gpsuo.mutation.AddCurrentAmountCents(i)
	return gpsuo
}

// Mutation returns the GoalProgressSnapshotMutation object of the builder.
func (gpsuo *GoalProgressSnapshotUpdateOne) Mutation() *GoalProgressSnapshotMutation {
	return gpsuo.mutation
}

// Where appends a list predicates to the GoalProgressSnapshotUpdate builder.
func (gpsuo *GoalProgressSnapshotUpdateOne) Where(ps ...predicate.GoalProgressSnapshot) *GoalProgressSnapshotUpdateOne {
	gpsuo.mutation.Where(ps...)
	return gpsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (gpsuo *GoalProgressSnapshotUpdateOne) Select(field string, fields ...string) *GoalProgressSnapshotUpdateOne {
	gpsuo.fields = append([]string{field}, fields...)
	return gpsuo
}

// Save executes the query and returns the updated GoalProgressSnapshot entity.
func (gpsuo *GoalProgressSnapshotUpdateOne) Save(ctx context.Context) (*GoalProgressSnapshot, error) {
	return withHooks(ctx, gpsuo.sqlSave, gpsuo.mutation, gpsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gpsuo *GoalProgressSnapshotUpdateOne) SaveX(ctx context.Context) *GoalProgressSnapshot {
	node, err := gpsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (gpsuo *GoalProgressSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := gpsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gpsuo *GoalProgressSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := gpsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gpsuo *GoalProgressSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *GoalProgressSnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(goalprogresssnapshot.Table, goalprogresssnapshot.Columns, sqlgraph.NewFieldSpec(goalprogresssnapshot.FieldID, field.TypeUUID))
	id, ok := gpsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GoalProgressSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := gpsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goalprogresssnapshot.FieldID)
		for _, f := range fields {
			if !goalprogresssnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != goalprogresssnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := gpsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gpsuo.mutation.GoalID(); ok {
		_spec.SetField(goalprogresssnapshot.FieldGoalID, field.TypeUUID, value)
	}
	if value, ok := gpsuo.mutation.SnapshotDate(); ok {
		_spec.SetField(goalprogresssnapshot.FieldSnapshotDate, field.TypeTime, value)
	}
	if value, ok := gpsuo.mutation.CurrentAmountCents(); ok {
		_spec.SetField(goalprogresssnapshot.FieldCurrentAmountCents, field.TypeInt64, value)
	}
	if value, ok := gpsuo.mutation.AddedCurrentAmountCents(); ok {
		_spec.AddField(goalprogresssnapshot.FieldCurrentAmountCents, field.TypeInt64, value)
	}
	_node = &GoalProgressSnapshot{config: gpsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, gpsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goalprogresssnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	gpsuo.mutation.done = true
	return _node, nil
}
