// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DebtDetails is the predicate function for debtdetails builders.
type DebtDetails func(*sql.Selector)

// PaymentSchedule is the predicate function for paymentschedule builders.
type PaymentSchedule func(*sql.Selector)
