// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/template/ent/predicate"
	"github.com/yucai/server/internal/template/ent/templaterecordlog"
	"github.com/yucai/server/internal/template/ent/transactiontemplate"
)

// TemplateRecordLogUpdate is the builder for updating TemplateRecordLog entities.
type TemplateRecordLogUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateRecordLogMutation
}

// Where appends a list predicates to the TemplateRecordLogUpdate builder.
func (trlu *TemplateRecordLogUpdate) Where(ps ...predicate.TemplateRecordLog) *TemplateRecordLogUpdate {
	trlu.mutation.Where(ps...)
	return trlu
}

// SetTemplateID sets the "template_id" field.
func (trlu *TemplateRecordLogUpdate) SetTemplateID(u uuid.UUID) *TemplateRecordLogUpdate {
	trlu.mutation.SetTemplateID(u)
	return trlu
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (trlu *TemplateRecordLogUpdate) SetNillableTemplateID(u *uuid.UUID) *TemplateRecordLogUpdate {
	if u != nil {
		trlu.SetTemplateID(*u)
	}
	return trlu
}

// SetRecordDate sets the "record_date" field.
func (trlu *TemplateRecordLogUpdate) SetRecordDate(t time.Time) *TemplateRecordLogUpdate {
	trlu.mutation.SetRecordDate(t)
	return trlu
}

// SetNillableRecordDate sets the "record_date" field if the given value is not nil.
func (trlu *TemplateRecordLogUpdate) SetNillableRecordDate(t *time.Time) *TemplateRecordLogUpdate {
	if t != nil {
		trlu.SetRecordDate(*t)
	}
	return trlu
}

// SetTransactionID sets the "transaction_id" field.
func (trlu *TemplateRecordLogUpdate) SetTransactionID(u uuid.UUID) *TemplateRecordLogUpdate {
	trlu.mutation.SetTransactionID(u)
	return trlu
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (trlu *TemplateRecordLogUpdate) SetNillableTransactionID(u *uuid.UUID) *TemplateRecordLogUpdate {
	if u != nil {
		trlu.SetTransactionID(*u)
	}
	return trlu
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (trlu *TemplateRecordLogUpdate) ClearTransactionID() *TemplateRecordLogUpdate {
	trlu.mutation.ClearTransactionID()
	return trlu
}

// SetTemplate sets the "template" edge to the TransactionTemplate entity.
func (trlu *TemplateRecordLogUpdate) SetTemplate(t *TransactionTemplate) *TemplateRecordLogUpdate {
	return trlu.SetTemplateID(t.ID)
}

// Mutation returns the TemplateRecordLogMutation object of the builder.
func (trlu *TemplateRecordLogUpdate) Mutation() *TemplateRecordLogMutation {
	return trlu.mutation
}

// ClearTemplate clears the "template" edge to the TransactionTemplate entity.
func (trlu *TemplateRecordLogUpdate) ClearTemplate() *TemplateRecordLogUpdate {
	trlu.mutation.ClearTemplate()
	return trlu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (trlu *TemplateRecordLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, trlu.sqlSave, trlu.mutation, trlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (trlu *TemplateRecordLogUpdate) SaveX(ctx context.Context) int {
	affected, err := trlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (trlu *TemplateRecordLogUpdate) Exec(ctx context.Context) error {
	_, err := trlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trlu *TemplateRecordLogUpdate) ExecX(ctx context.Context) {
	if err := trlu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (trlu *TemplateRecordLogUpdate) check() error {
	if trlu.mutation.TemplateCleared() && len(trlu.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemplateRecordLog.template"`)
	}
	return nil
}

func (trlu *TemplateRecordLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := trlu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(templaterecordlog.Table, templaterecordlog.Columns, sqlgraph.NewFieldSpec(templaterecordlog.FieldID, field.TypeUUID))
	if ps := trlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := trlu.mutation.RecordDate(); ok {
		_spec.SetField(templaterecordlog.FieldRecordDate, field.TypeTime, value)
	}
	if value, ok := trlu.mutation.TransactionID(); ok {
		_spec.SetField(templaterecordlog.FieldTransactionID, field.TypeUUID, value)
	}
	if trlu.mutation.TransactionIDCleared() {
		_spec.ClearField(templaterecordlog.FieldTransactionID, field.TypeUUID)
	}
	if trlu.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templaterecordlog.TemplateTable,
			Columns: []string{templaterecordlog.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactiontemplate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := trlu.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templaterecordlog.TemplateTable,
			Columns: []string{templaterecordlog.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactiontemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, trlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templaterecordlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	trlu.mutation.done = true
	return n, nil
}

// TemplateRecordLogUpdateOne is the builder for updating a single TemplateRecordLog entity.
type TemplateRecordLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateRecordLogMutation
}

// SetTemplateID sets the "template_id" field.
func (trluo *TemplateRecordLogUpdateOne) SetTemplateID(u uuid.UUID) *TemplateRecordLogUpdateOne {
	trluo.mutation.SetTemplateID(u)
	return trluo
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (trluo *TemplateRecordLogUpdateOne) SetNillableTemplateID(u *uuid.UUID) *TemplateRecordLogUpdateOne {
	if u != nil {
		trluo.SetTemplateID(*u)
	}
	return trluo
}

// SetRecordDate sets the "record_date" field.
func (trluo *TemplateRecordLogUpdateOne) SetRecordDate(t time.Time) *TemplateRecordLogUpdateOne {
	trluo.mutation.SetRecordDate(t)
	return trluo
}

// SetNillableRecordDate sets the "record_date" field if the given value is not nil.
func (trluo *TemplateRecordLogUpdateOne) SetNillableRecordDate(t *time.Time) *TemplateRecordLogUpdateOne {
	if t != nil {
		trluo.SetRecordDate(*t)
	}
	return trluo
}

// SetTransactionID sets the "transaction_id" field.
func (trluo *TemplateRecordLogUpdateOne) SetTransactionID(u uuid.UUID) *TemplateRecordLogUpdateOne {
	trluo.mutation.SetTransactionID(u)
	return trluo
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (trluo *TemplateRecordLogUpdateOne) SetNillableTransactionID(u *uuid.UUID) *TemplateRecordLogUpdateOne {
	if u != nil {
		trluo.SetTransactionID(*u)
	}
	return trluo
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (trluo *TemplateRecordLogUpdateOne) ClearTransactionID() *TemplateRecordLogUpdateOne {
	trluo.mutation.ClearTransactionID()
	return trluo
}

// SetTemplate sets the "template" edge to the TransactionTemplate entity.
func (trluo *TemplateRecordLogUpdateOne) SetTemplate(t *TransactionTemplate) *TemplateRecordLogUpdateOne {
	return trluo.SetTemplateID(t.ID)
}

// Mutation returns the TemplateRecordLogMutation object of the builder.
func (trluo *TemplateRecordLogUpdateOne) Mutation() *TemplateRecordLogMutation {
	return trluo.mutation
}

// ClearTemplate clears the "template" edge to the TransactionTemplate entity.
func (trluo *TemplateRecordLogUpdateOne) ClearTemplate() *TemplateRecordLogUpdateOne {
	trluo.mutation.ClearTemplate()
	return trluo
}

// Where appends a list predicates to the TemplateRecordLogUpdate builder.
func (trluo *TemplateRecordLogUpdateOne) Where(ps ...predicate.TemplateRecordLog) *TemplateRecordLogUpdateOne {
	trluo.mutation.Where(ps...)
	return trluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (trluo *TemplateRecordLogUpdateOne) Select(field string, fields ...string) *TemplateRecordLogUpdateOne {
	trluo.fields = append([]string{field}, fields...)
	return trluo
}

// Save executes the query and returns the updated TemplateRecordLog entity.
func (trluo *TemplateRecordLogUpdateOne) Save(ctx context.Context) (*TemplateRecordLog, error) {
	return withHooks(ctx, trluo.sqlSave, trluo.mutation, trluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (trluo *TemplateRecordLogUpdateOne) SaveX(ctx context.Context) *TemplateRecordLog {
	node, err := trluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (trluo *TemplateRecordLogUpdateOne) Exec(ctx context.Context) error {
	_, err := trluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trluo *TemplateRecordLogUpdateOne) ExecX(ctx context.Context) {
	if err := trluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (trluo *TemplateRecordLogUpdateOne) check() error {
	if trluo.mutation.TemplateCleared() && len(trluo.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemplateRecordLog.template"`)
	}
	return nil
}

func (trluo *TemplateRecordLogUpdateOne) sqlSave(ctx context.Context) (_node *TemplateRecordLog, err error) {
	if err := trluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templaterecordlog.Table, templaterecordlog.Columns, sqlgraph.NewFieldSpec(templaterecordlog.FieldID, field.TypeUUID))
	id, ok := trluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TemplateRecordLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := trluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templaterecordlog.FieldID)
		for _, f := range fields {
			if !templaterecordlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != templaterecordlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := trluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := trluo.mutation.RecordDate(); ok {
		_spec.SetField(templaterecordlog.FieldRecordDate, field.TypeTime, value)
	}
	if value, ok := trluo.mutation.TransactionID(); ok {
		_spec.SetField(templaterecordlog.FieldTransactionID, field.TypeUUID, value)
	}
	if trluo.mutation.TransactionIDCleared() {
		_spec.ClearField(templaterecordlog.FieldTransactionID, field.TypeUUID)
	}
	if trluo.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templaterecordlog.TemplateTable,
			Columns: []string{templaterecordlog.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactiontemplate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := trluo.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templaterecordlog.TemplateTable,
			Columns: []string{templaterecordlog.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactiontemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TemplateRecordLog{config: trluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, trluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templaterecordlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	trluo.mutation.done = true
	return _node, nil
}
