// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: template/v1/template.proto

package templatev1

import (
	v1 "github.com/yucai/server/internal/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateDirection int32

const (
	TemplateDirection_DIRECTION_UNSPECIFIED TemplateDirection = 0
	TemplateDirection_DIRECTION_EXPENSE     TemplateDirection = 1
	TemplateDirection_DIRECTION_INCOME      TemplateDirection = 2
	TemplateDirection_DIRECTION_TRANSFER    TemplateDirection = 3
)

// Enum value maps for TemplateDirection.
var (
	TemplateDirection_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_EXPENSE",
		2: "DIRECTION_INCOME",
		3: "DIRECTION_TRANSFER",
	}
	TemplateDirection_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_EXPENSE":     1,
		"DIRECTION_INCOME":      2,
		"DIRECTION_TRANSFER":    3,
	}
)

func (x TemplateDirection) Enum() *TemplateDirection {
	p := new(TemplateDirection)
	*p = x
	return p
}

func (x TemplateDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_template_v1_template_proto_enumTypes[0].Descriptor()
}

func (TemplateDirection) Type() protoreflect.EnumType {
	return &file_template_v1_template_proto_enumTypes[0]
}

func (x TemplateDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateDirection.Descriptor instead.
func (TemplateDirection) EnumDescriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{0}
}

type TemplateCycle int32

const (
	TemplateCycle_CYCLE_UNSPECIFIED TemplateCycle = 0
	TemplateCycle_CYCLE_WEEKLY      TemplateCycle = 1
	TemplateCycle_CYCLE_MONTHLY     TemplateCycle = 2
	TemplateCycle_CYCLE_YEARLY      TemplateCycle = 3
	TemplateCycle_CYCLE_CUSTOM      TemplateCycle = 4
)

// Enum value maps for TemplateCycle.
var (
	TemplateCycle_name = map[int32]string{
		0: "CYCLE_UNSPECIFIED",
		1: "CYCLE_WEEKLY",
		2: "CYCLE_MONTHLY",
		3: "CYCLE_YEARLY",
		4: "CYCLE_CUSTOM",
	}
	TemplateCycle_value = map[string]int32{
		"CYCLE_UNSPECIFIED": 0,
		"CYCLE_WEEKLY":      1,
		"CYCLE_MONTHLY":     2,
		"CYCLE_YEARLY":      3,
		"CYCLE_CUSTOM":      4,
	}
)

func (x TemplateCycle) Enum() *TemplateCycle {
	p := new(TemplateCycle)
	*p = x
	return p
}

func (x TemplateCycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateCycle) Descriptor() protoreflect.EnumDescriptor {
	return file_template_v1_template_proto_enumTypes[1].Descriptor()
}

func (TemplateCycle) Type() protoreflect.EnumType {
	return &file_template_v1_template_proto_enumTypes[1]
}

func (x TemplateCycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateCycle.Descriptor instead.
func (TemplateCycle) EnumDescriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{1}
}

type TemplateDTO struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AmountCents          int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Direction            TemplateDirection      `protobuf:"varint,5,opt,name=direction,proto3,enum=yucai.template.v1.TemplateDirection" json:"direction,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,6,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,7,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Cycle                TemplateCycle          `protobuf:"varint,8,opt,name=cycle,proto3,enum=yucai.template.v1.TemplateCycle" json:"cycle,omitempty"`
	CycleDays            int32                  `protobuf:"varint,9,opt,name=cycle_days,json=cycleDays,proto3" json:"cycle_days,omitempty"`
	BillingDay           int32                  `protobuf:"varint,10,opt,name=billing_day,json=billingDay,proto3" json:"billing_day,omitempty"`
	NextDate             string                 `protobuf:"bytes,11,opt,name=next_date,json=nextDate,proto3" json:"next_date,omitempty"`
	StartDate            string                 `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string                 `protobuf:"bytes,13,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AutoRecord           bool                   `protobuf:"varint,14,opt,name=auto_record,json=autoRecord,proto3" json:"auto_record,omitempty"`
	Paused               bool                   `protobuf:"varint,15,opt,name=paused,proto3" json:"paused,omitempty"`
	LastTransactionId    string                 `protobuf:"bytes,16,opt,name=last_transaction_id,json=lastTransactionId,proto3" json:"last_transaction_id,omitempty"`
	Category             string                 `protobuf:"bytes,17,opt,name=category,proto3" json:"category,omitempty"`
	Version              int64                  `protobuf:"varint,18,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TemplateDTO) Reset() {
	*x = TemplateDTO{}
	mi := &file_template_v1_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateDTO) ProtoMessage() {}

func (x *TemplateDTO) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateDTO.ProtoReflect.Descriptor instead.
func (*TemplateDTO) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TemplateDTO) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *TemplateDTO) GetDirection() TemplateDirection {
	if x != nil {
		return x.Direction
	}
	return TemplateDirection_DIRECTION_UNSPECIFIED
}

func (x *TemplateDTO) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *TemplateDTO) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *TemplateDTO) GetCycle() TemplateCycle {
	if x != nil {
		return x.Cycle
	}
	return TemplateCycle_CYCLE_UNSPECIFIED
}

func (x *TemplateDTO) GetCycleDays() int32 {
	if x != nil {
		return x.CycleDays
	}
	return 0
}

func (x *TemplateDTO) GetBillingDay() int32 {
	if x != nil {
		return x.BillingDay
	}
	return 0
}

func (x *TemplateDTO) GetNextDate() string {
	if x != nil {
		return x.NextDate
	}
	return ""
}

func (x *TemplateDTO) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TemplateDTO) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TemplateDTO) GetAutoRecord() bool {
	if x != nil {
		return x.AutoRecord
	}
	return false
}

func (x *TemplateDTO) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *TemplateDTO) GetLastTransactionId() string {
	if x != nil {
		return x.LastTransactionId
	}
	return ""
}

func (x *TemplateDTO) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TemplateDTO) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TemplateDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TemplateDTO) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTemplateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AmountCents          int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Direction            TemplateDirection      `protobuf:"varint,4,opt,name=direction,proto3,enum=yucai.template.v1.TemplateDirection" json:"direction,omitempty"`
	SourceAccountId      string                 `protobuf:"bytes,5,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,6,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Cycle                TemplateCycle          `protobuf:"varint,7,opt,name=cycle,proto3,enum=yucai.template.v1.TemplateCycle" json:"cycle,omitempty"`
	CycleDays            int32                  `protobuf:"varint,8,opt,name=cycle_days,json=cycleDays,proto3" json:"cycle_days,omitempty"`
	BillingDay           int32                  `protobuf:"varint,9,opt,name=billing_day,json=billingDay,proto3" json:"billing_day,omitempty"`
	StartDate            string                 `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string                 `protobuf:"bytes,11,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AutoRecord           bool                   `protobuf:"varint,12,opt,name=auto_record,json=autoRecord,proto3" json:"auto_record,omitempty"`
	Category             string                 `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CreateTemplateRequest) GetDirection() TemplateDirection {
	if x != nil {
		return x.Direction
	}
	return TemplateDirection_DIRECTION_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *CreateTemplateRequest) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *CreateTemplateRequest) GetCycle() TemplateCycle {
	if x != nil {
		return x.Cycle
	}
	return TemplateCycle_CYCLE_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetCycleDays() int32 {
	if x != nil {
		return x.CycleDays
	}
	return 0
}

func (x *CreateTemplateRequest) GetBillingDay() int32 {
	if x != nil {
		return x.BillingDay
	}
	return 0
}

func (x *CreateTemplateRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateTemplateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateTemplateRequest) GetAutoRecord() bool {
	if x != nil {
		return x.AutoRecord
	}
	return false
}

func (x *CreateTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AmountCents   int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Cycle         TemplateCycle          `protobuf:"varint,5,opt,name=cycle,proto3,enum=yucai.template.v1.TemplateCycle" json:"cycle,omitempty"`
	CycleDays     int32                  `protobuf:"varint,6,opt,name=cycle_days,json=cycleDays,proto3" json:"cycle_days,omitempty"`
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AutoRecord    bool                   `protobuf:"varint,8,opt,name=auto_record,json=autoRecord,proto3" json:"auto_record,omitempty"`
	Version       int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *UpdateTemplateRequest) GetCycle() TemplateCycle {
	if x != nil {
		return x.Cycle
	}
	return TemplateCycle_CYCLE_UNSPECIFIED
}

func (x *UpdateTemplateRequest) GetCycleDays() int32 {
	if x != nil {
		return x.CycleDays
	}
	return 0
}

func (x *UpdateTemplateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UpdateTemplateRequest) GetAutoRecord() bool {
	if x != nil {
		return x.AutoRecord
	}
	return false
}

func (x *UpdateTemplateRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PauseTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTemplateRequest) Reset() {
	*x = PauseTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTemplateRequest) ProtoMessage() {}

func (x *PauseTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTemplateRequest.ProtoReflect.Descriptor instead.
func (*PauseTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{4}
}

func (x *PauseTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTemplateRequest) Reset() {
	*x = ResumeTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTemplateRequest) ProtoMessage() {}

func (x *ResumeTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTemplateRequest.ProtoReflect.Descriptor instead.
func (*ResumeTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{6}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Paused        bool                   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_template_v1_template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{7}
}

func (x *ListTemplatesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListTemplatesRequest) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateDTO         `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_template_v1_template_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{8}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateDTO {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type TemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TemplateDTO           `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateResponse) Reset() {
	*x = TemplateResponse{}
	mi := &file_template_v1_template_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateResponse) ProtoMessage() {}

func (x *TemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateResponse.ProtoReflect.Descriptor instead.
func (*TemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{9}
}

func (x *TemplateResponse) GetTemplate() *TemplateDTO {
	if x != nil {
		return x.Template
	}
	return nil
}

type RecordTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTemplateRequest) Reset() {
	*x = RecordTemplateRequest{}
	mi := &file_template_v1_template_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTemplateRequest) ProtoMessage() {}

func (x *RecordTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTemplateRequest.ProtoReflect.Descriptor instead.
func (*RecordTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{10}
}

func (x *RecordTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type RecordTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	NextDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_date,json=nextDate,proto3" json:"next_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionResponse) Reset() {
	*x = RecordTransactionResponse{}
	mi := &file_template_v1_template_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionResponse) ProtoMessage() {}

func (x *RecordTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_v1_template_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionResponse.ProtoReflect.Descriptor instead.
func (*RecordTransactionResponse) Descriptor() ([]byte, []int) {
	return file_template_v1_template_proto_rawDescGZIP(), []int{11}
}

func (x *RecordTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordTransactionResponse) GetNextDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextDate
	}
	return nil
}

var File_template_v1_template_proto protoreflect.FileDescriptor

const file_template_v1_template_proto_rawDesc = "" +
	"\n" +
	"\x1atemplate/v1/template.proto\x12\x11yucai.template.v1\x1a\x1acommon/v1/pagination.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x06\n" +
	"\vTemplateDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12B\n" +
	"\tdirection\x18\x05 \x01(\x0e2$.yucai.template.v1.TemplateDirectionR\tdirection\x12*\n" +
	"\x11source_account_id\x18\x06 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\a \x01(\tR\x14destinationAccountId\x126\n" +
	"\x05cycle\x18\b \x01(\x0e2 .yucai.template.v1.TemplateCycleR\x05cycle\x12\x1d\n" +
	"\n" +
	"cycle_days\x18\t \x01(\x05R\tcycleDays\x12\x1f\n" +
	"\vbilling_day\x18\n" +
	" \x01(\x05R\n" +
	"billingDay\x12\x1b\n" +
	"\tnext_date\x18\v \x01(\tR\bnextDate\x12\x1d\n" +
	"\n" +
	"start_date\x18\f \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\r \x01(\tR\aendDate\x12\x1f\n" +
	"\vauto_record\x18\x0e \x01(\bR\n" +
	"autoRecord\x12\x16\n" +
	"\x06paused\x18\x0f \x01(\bR\x06paused\x12.\n" +
	"\x13last_transaction_id\x18\x10 \x01(\tR\x11lastTransactionId\x12\x1a\n" +
	"\bcategory\x18\x11 \x01(\tR\bcategory\x12\x18\n" +
	"\aversion\x18\x12 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x85\x04\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12B\n" +
	"\tdirection\x18\x04 \x01(\x0e2$.yucai.template.v1.TemplateDirectionR\tdirection\x12*\n" +
	"\x11source_account_id\x18\x05 \x01(\tR\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x06 \x01(\tR\x14destinationAccountId\x126\n" +
	"\x05cycle\x18\a \x01(\x0e2 .yucai.template.v1.TemplateCycleR\x05cycle\x12\x1d\n" +
	"\n" +
	"cycle_days\x18\b \x01(\x05R\tcycleDays\x12\x1f\n" +
	"\vbilling_day\x18\t \x01(\x05R\n" +
	"billingDay\x12\x1d\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\v \x01(\tR\aendDate\x12\x1f\n" +
	"\vauto_record\x18\f \x01(\bR\n" +
	"autoRecord\x12\x1a\n" +
	"\bcategory\x18\r \x01(\tR\bcategory\"\xad\x02\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x126\n" +
	"\x05cycle\x18\x05 \x01(\x0e2 .yucai.template.v1.TemplateCycleR\x05cycle\x12\x1d\n" +
	"\n" +
	"cycle_days\x18\x06 \x01(\x05R\tcycleDays\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x1f\n" +
	"\vauto_record\x18\b \x01(\bR\n" +
	"autoRecord\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14PauseTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15ResumeTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x14ListTemplatesRequest\x120\n" +
	"\x04page\x18\x01 \x01(\v2\x1c.yucai.common.v1.PageRequestR\x04page\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\"\x88\x01\n" +
	"\x15ListTemplatesResponse\x12<\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1e.yucai.template.v1.TemplateDTOR\ttemplates\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.yucai.common.v1.PageResponseR\x04page\"N\n" +
	"\x10TemplateResponse\x12:\n" +
	"\btemplate\x18\x01 \x01(\v2\x1e.yucai.template.v1.TemplateDTOR\btemplate\"8\n" +
	"\x15RecordTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"{\n" +
	"\x19RecordTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x127\n" +
	"\tnext_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnextDate*s\n" +
	"\x11TemplateDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_EXPENSE\x10\x01\x12\x14\n" +
	"\x10DIRECTION_INCOME\x10\x02\x12\x16\n" +
	"\x12DIRECTION_TRANSFER\x10\x03*o\n" +
	"\rTemplateCycle\x12\x15\n" +
	"\x11CYCLE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCYCLE_WEEKLY\x10\x01\x12\x11\n" +
	"\rCYCLE_MONTHLY\x10\x02\x12\x10\n" +
	"\fCYCLE_YEARLY\x10\x03\x12\x10\n" +
	"\fCYCLE_CUSTOM\x10\x042\xeb\x06\n" +
	"\x1aTransactionTemplateService\x12j\n" +
	"\x19CreateTransactionTemplate\x12(.yucai.template.v1.CreateTemplateRequest\x1a#.yucai.template.v1.TemplateResponse\x12j\n" +
	"\x19UpdateTransactionTemplate\x12(.yucai.template.v1.UpdateTemplateRequest\x1a#.yucai.template.v1.TemplateResponse\x12]\n" +
	"\x19DeleteTransactionTemplate\x12(.yucai.template.v1.DeleteTemplateRequest\x1a\x16.google.protobuf.Empty\x12h\n" +
	"\x18PauseTransactionTemplate\x12'.yucai.template.v1.PauseTemplateRequest\x1a#.yucai.template.v1.TemplateResponse\x12j\n" +
	"\x19ResumeTransactionTemplate\x12(.yucai.template.v1.ResumeTemplateRequest\x1a#.yucai.template.v1.TemplateResponse\x12d\n" +
	"\x16GetTransactionTemplate\x12%.yucai.template.v1.GetTemplateRequest\x1a#.yucai.template.v1.TemplateResponse\x12m\n" +
	"\x18ListTransactionTemplates\x12'.yucai.template.v1.ListTemplatesRequest\x1a(.yucai.template.v1.ListTemplatesResponse\x12k\n" +
	"\x11RecordTransaction\x12(.yucai.template.v1.RecordTemplateRequest\x1a,.yucai.template.v1.RecordTransactionResponseB\xcb\x01\n" +
	"\x15com.yucai.template.v1B\rTemplateProtoP\x01Z=github.com/yucai/server/internal/proto/template/v1;templatev1\xa2\x02\x03YTX\xaa\x02\x11Yucai.Template.V1\xca\x02\x11Yucai\\Template\\V1\xe2\x02\x1dYucai\\Template\\V1\\GPBMetadata\xea\x02\x13Yucai::Template::V1b\x06proto3"

var (
	file_template_v1_template_proto_rawDescOnce sync.Once
	file_template_v1_template_proto_rawDescData []byte
)

func file_template_v1_template_proto_rawDescGZIP() []byte {
	file_template_v1_template_proto_rawDescOnce.Do(func() {
		file_template_v1_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_v1_template_proto_rawDesc), len(file_template_v1_template_proto_rawDesc)))
	})
	return file_template_v1_template_proto_rawDescData
}

var file_template_v1_template_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_template_v1_template_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_template_v1_template_proto_goTypes = []any{
	(TemplateDirection)(0),            // 0: yucai.template.v1.TemplateDirection
	(TemplateCycle)(0),                // 1: yucai.template.v1.TemplateCycle
	(*TemplateDTO)(nil),               // 2: yucai.template.v1.TemplateDTO
	(*CreateTemplateRequest)(nil),     // 3: yucai.template.v1.CreateTemplateRequest
	(*UpdateTemplateRequest)(nil),     // 4: yucai.template.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),     // 5: yucai.template.v1.DeleteTemplateRequest
	(*PauseTemplateRequest)(nil),      // 6: yucai.template.v1.PauseTemplateRequest
	(*ResumeTemplateRequest)(nil),     // 7: yucai.template.v1.ResumeTemplateRequest
	(*GetTemplateRequest)(nil),        // 8: yucai.template.v1.GetTemplateRequest
	(*ListTemplatesRequest)(nil),      // 9: yucai.template.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),     // 10: yucai.template.v1.ListTemplatesResponse
	(*TemplateResponse)(nil),          // 11: yucai.template.v1.TemplateResponse
	(*RecordTemplateRequest)(nil),     // 12: yucai.template.v1.RecordTemplateRequest
	(*RecordTransactionResponse)(nil), // 13: yucai.template.v1.RecordTransactionResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),            // 15: yucai.common.v1.PageRequest
	(*v1.PageResponse)(nil),           // 16: yucai.common.v1.PageResponse
	(*emptypb.Empty)(nil),             // 17: google.protobuf.Empty
}
var file_template_v1_template_proto_depIdxs = []int32{
	0,  // 0: yucai.template.v1.TemplateDTO.direction:type_name -> yucai.template.v1.TemplateDirection
	1,  // 1: yucai.template.v1.TemplateDTO.cycle:type_name -> yucai.template.v1.TemplateCycle
	14, // 2: yucai.template.v1.TemplateDTO.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: yucai.template.v1.TemplateDTO.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: yucai.template.v1.CreateTemplateRequest.direction:type_name -> yucai.template.v1.TemplateDirection
	1,  // 5: yucai.template.v1.CreateTemplateRequest.cycle:type_name -> yucai.template.v1.TemplateCycle
	1,  // 6: yucai.template.v1.UpdateTemplateRequest.cycle:type_name -> yucai.template.v1.TemplateCycle
	15, // 7: yucai.template.v1.ListTemplatesRequest.page:type_name -> yucai.common.v1.PageRequest
	2,  // 8: yucai.template.v1.ListTemplatesResponse.templates:type_name -> yucai.template.v1.TemplateDTO
	16, // 9: yucai.template.v1.ListTemplatesResponse.page:type_name -> yucai.common.v1.PageResponse
	2,  // 10: yucai.template.v1.TemplateResponse.template:type_name -> yucai.template.v1.TemplateDTO
	14, // 11: yucai.template.v1.RecordTransactionResponse.next_date:type_name -> google.protobuf.Timestamp
	3,  // 12: yucai.template.v1.TransactionTemplateService.CreateTransactionTemplate:input_type -> yucai.template.v1.CreateTemplateRequest
	4,  // 13: yucai.template.v1.TransactionTemplateService.UpdateTransactionTemplate:input_type -> yucai.template.v1.UpdateTemplateRequest
	5,  // 14: yucai.template.v1.TransactionTemplateService.DeleteTransactionTemplate:input_type -> yucai.template.v1.DeleteTemplateRequest
	6,  // 15: yucai.template.v1.TransactionTemplateService.PauseTransactionTemplate:input_type -> yucai.template.v1.PauseTemplateRequest
	7,  // 16: yucai.template.v1.TransactionTemplateService.ResumeTransactionTemplate:input_type -> yucai.template.v1.ResumeTemplateRequest
	8,  // 17: yucai.template.v1.TransactionTemplateService.GetTransactionTemplate:input_type -> yucai.template.v1.GetTemplateRequest
	9,  // 18: yucai.template.v1.TransactionTemplateService.ListTransactionTemplates:input_type -> yucai.template.v1.ListTemplatesRequest
	12, // 19: yucai.template.v1.TransactionTemplateService.RecordTransaction:input_type -> yucai.template.v1.RecordTemplateRequest
	11, // 20: yucai.template.v1.TransactionTemplateService.CreateTransactionTemplate:output_type -> yucai.template.v1.TemplateResponse
	11, // 21: yucai.template.v1.TransactionTemplateService.UpdateTransactionTemplate:output_type -> yucai.template.v1.TemplateResponse
	17, // 22: yucai.template.v1.TransactionTemplateService.DeleteTransactionTemplate:output_type -> google.protobuf.Empty
	11, // 23: yucai.template.v1.TransactionTemplateService.PauseTransactionTemplate:output_type -> yucai.template.v1.TemplateResponse
	11, // 24: yucai.template.v1.TransactionTemplateService.ResumeTransactionTemplate:output_type -> yucai.template.v1.TemplateResponse
	11, // 25: yucai.template.v1.TransactionTemplateService.GetTransactionTemplate:output_type -> yucai.template.v1.TemplateResponse
	10, // 26: yucai.template.v1.TransactionTemplateService.ListTransactionTemplates:output_type -> yucai.template.v1.ListTemplatesResponse
	13, // 27: yucai.template.v1.TransactionTemplateService.RecordTransaction:output_type -> yucai.template.v1.RecordTransactionResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_template_v1_template_proto_init() }
func file_template_v1_template_proto_init() {
	if File_template_v1_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_v1_template_proto_rawDesc), len(file_template_v1_template_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_v1_template_proto_goTypes,
		DependencyIndexes: file_template_v1_template_proto_depIdxs,
		EnumInfos:         file_template_v1_template_proto_enumTypes,
		MessageInfos:      file_template_v1_template_proto_msgTypes,
	}.Build()
	File_template_v1_template_proto = out.File
	file_template_v1_template_proto_goTypes = nil
	file_template_v1_template_proto_depIdxs = nil
}
