// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/yucai/server/internal/category/ent/category"
	"github.com/yucai/server/internal/category/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescIcon is the schema descriptor for icon field.
	categoryDescIcon := categoryFields[3].Descriptor()
	// category.DefaultIcon holds the default value on creation for the icon field.
	category.DefaultIcon = categoryDescIcon.Default.(string)
	// categoryDescColor is the schema descriptor for color field.
	categoryDescColor := categoryFields[4].Descriptor()
	// category.DefaultColor holds the default value on creation for the color field.
	category.DefaultColor = categoryDescColor.Default.(string)
	// categoryDescIsSystem is the schema descriptor for is_system field.
	categoryDescIsSystem := categoryFields[6].Descriptor()
	// category.DefaultIsSystem holds the default value on creation for the is_system field.
	category.DefaultIsSystem = categoryDescIsSystem.Default.(bool)
	// categoryDescSortOrder is the schema descriptor for sort_order field.
	categoryDescSortOrder := categoryFields[7].Descriptor()
	// category.DefaultSortOrder holds the default value on creation for the sort_order field.
	category.DefaultSortOrder = categoryDescSortOrder.Default.(int32)
	// categoryDescVersion is the schema descriptor for version field.
	categoryDescVersion := categoryFields[8].Descriptor()
	// category.DefaultVersion holds the default value on creation for the version field.
	category.DefaultVersion = categoryDescVersion.Default.(int64)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[10].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[11].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
}
