// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: holding/v1/holding.proto

package holdingv1

import (
	v1 "github.com/yucai/server/internal/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityType int32

const (
	SecurityType_SECURITY_TYPE_UNSPECIFIED SecurityType = 0
	SecurityType_SECURITY_TYPE_STOCK       SecurityType = 1
	SecurityType_SECURITY_TYPE_FUND        SecurityType = 2
	SecurityType_SECURITY_TYPE_ETF         SecurityType = 3
	SecurityType_SECURITY_TYPE_BOND        SecurityType = 4
	SecurityType_SECURITY_TYPE_GOLD        SecurityType = 5
	SecurityType_SECURITY_TYPE_OPTION      SecurityType = 6
	SecurityType_SECURITY_TYPE_OTHER       SecurityType = 7
)

// Enum value maps for SecurityType.
var (
	SecurityType_name = map[int32]string{
		0: "SECURITY_TYPE_UNSPECIFIED",
		1: "SECURITY_TYPE_STOCK",
		2: "SECURITY_TYPE_FUND",
		3: "SECURITY_TYPE_ETF",
		4: "SECURITY_TYPE_BOND",
		5: "SECURITY_TYPE_GOLD",
		6: "SECURITY_TYPE_OPTION",
		7: "SECURITY_TYPE_OTHER",
	}
	SecurityType_value = map[string]int32{
		"SECURITY_TYPE_UNSPECIFIED": 0,
		"SECURITY_TYPE_STOCK":       1,
		"SECURITY_TYPE_FUND":        2,
		"SECURITY_TYPE_ETF":         3,
		"SECURITY_TYPE_BOND":        4,
		"SECURITY_TYPE_GOLD":        5,
		"SECURITY_TYPE_OPTION":      6,
		"SECURITY_TYPE_OTHER":       7,
	}
)

func (x SecurityType) Enum() *SecurityType {
	p := new(SecurityType)
	*p = x
	return p
}

func (x SecurityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityType) Descriptor() protoreflect.EnumDescriptor {
	return file_holding_v1_holding_proto_enumTypes[0].Descriptor()
}

func (SecurityType) Type() protoreflect.EnumType {
	return &file_holding_v1_holding_proto_enumTypes[0]
}

func (x SecurityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityType.Descriptor instead.
func (SecurityType) EnumDescriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{0}
}

type TradeType int32

const (
	TradeType_TRADE_TYPE_UNSPECIFIED TradeType = 0
	TradeType_TRADE_TYPE_BUY         TradeType = 1
	TradeType_TRADE_TYPE_SELL        TradeType = 2
	TradeType_TRADE_TYPE_DIVIDEND    TradeType = 3
	TradeType_TRADE_TYPE_SPLIT       TradeType = 4
)

// Enum value maps for TradeType.
var (
	TradeType_name = map[int32]string{
		0: "TRADE_TYPE_UNSPECIFIED",
		1: "TRADE_TYPE_BUY",
		2: "TRADE_TYPE_SELL",
		3: "TRADE_TYPE_DIVIDEND",
		4: "TRADE_TYPE_SPLIT",
	}
	TradeType_value = map[string]int32{
		"TRADE_TYPE_UNSPECIFIED": 0,
		"TRADE_TYPE_BUY":         1,
		"TRADE_TYPE_SELL":        2,
		"TRADE_TYPE_DIVIDEND":    3,
		"TRADE_TYPE_SPLIT":       4,
	}
)

func (x TradeType) Enum() *TradeType {
	p := new(TradeType)
	*p = x
	return p
}

func (x TradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_holding_v1_holding_proto_enumTypes[1].Descriptor()
}

func (TradeType) Type() protoreflect.EnumType {
	return &file_holding_v1_holding_proto_enumTypes[1]
}

func (x TradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeType.Descriptor instead.
func (TradeType) EnumDescriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{1}
}

type CurveRange int32

const (
	CurveRange_CURVE_RANGE_UNSPECIFIED CurveRange = 0
	CurveRange_CURVE_RANGE_DAY         CurveRange = 1
	CurveRange_CURVE_RANGE_MONTH       CurveRange = 2
	CurveRange_CURVE_RANGE_YEAR        CurveRange = 3
)

// Enum value maps for CurveRange.
var (
	CurveRange_name = map[int32]string{
		0: "CURVE_RANGE_UNSPECIFIED",
		1: "CURVE_RANGE_DAY",
		2: "CURVE_RANGE_MONTH",
		3: "CURVE_RANGE_YEAR",
	}
	CurveRange_value = map[string]int32{
		"CURVE_RANGE_UNSPECIFIED": 0,
		"CURVE_RANGE_DAY":         1,
		"CURVE_RANGE_MONTH":       2,
		"CURVE_RANGE_YEAR":        3,
	}
)

func (x CurveRange) Enum() *CurveRange {
	p := new(CurveRange)
	*p = x
	return p
}

func (x CurveRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurveRange) Descriptor() protoreflect.EnumDescriptor {
	return file_holding_v1_holding_proto_enumTypes[2].Descriptor()
}

func (CurveRange) Type() protoreflect.EnumType {
	return &file_holding_v1_holding_proto_enumTypes[2]
}

func (x CurveRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurveRange.Descriptor instead.
func (CurveRange) EnumDescriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{2}
}

type SecurityDTO struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SecurityType      SecurityType           `protobuf:"varint,4,opt,name=security_type,json=securityType,proto3,enum=yucai.holding.v1.SecurityType" json:"security_type,omitempty"`
	Exchange          string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	CurrencyCode      string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrentPriceCents int64                  `protobuf:"varint,7,opt,name=current_price_cents,json=currentPriceCents,proto3" json:"current_price_cents,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SecurityDTO) Reset() {
	*x = SecurityDTO{}
	mi := &file_holding_v1_holding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityDTO) ProtoMessage() {}

func (x *SecurityDTO) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityDTO.ProtoReflect.Descriptor instead.
func (*SecurityDTO) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityDTO) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SecurityDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityDTO) GetSecurityType() SecurityType {
	if x != nil {
		return x.SecurityType
	}
	return SecurityType_SECURITY_TYPE_UNSPECIFIED
}

func (x *SecurityDTO) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *SecurityDTO) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *SecurityDTO) GetCurrentPriceCents() int64 {
	if x != nil {
		return x.CurrentPriceCents
	}
	return 0
}

func (x *SecurityDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type HoldingDTO struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId          string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SecurityId         string                 `protobuf:"bytes,3,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	SecurityName       string                 `protobuf:"bytes,4,opt,name=security_name,json=securityName,proto3" json:"security_name,omitempty"`
	SecuritySymbol     string                 `protobuf:"bytes,5,opt,name=security_symbol,json=securitySymbol,proto3" json:"security_symbol,omitempty"`
	Quantity           float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AvgCostCents       int64                  `protobuf:"varint,7,opt,name=avg_cost_cents,json=avgCostCents,proto3" json:"avg_cost_cents,omitempty"`
	MarketValueCents   int64                  `protobuf:"varint,8,opt,name=market_value_cents,json=marketValueCents,proto3" json:"market_value_cents,omitempty"`
	UnrealizedPnlCents int64                  `protobuf:"varint,9,opt,name=unrealized_pnl_cents,json=unrealizedPnlCents,proto3" json:"unrealized_pnl_cents,omitempty"`
	Version            int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HoldingDTO) Reset() {
	*x = HoldingDTO{}
	mi := &file_holding_v1_holding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingDTO) ProtoMessage() {}

func (x *HoldingDTO) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingDTO.ProtoReflect.Descriptor instead.
func (*HoldingDTO) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{1}
}

func (x *HoldingDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HoldingDTO) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *HoldingDTO) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *HoldingDTO) GetSecurityName() string {
	if x != nil {
		return x.SecurityName
	}
	return ""
}

func (x *HoldingDTO) GetSecuritySymbol() string {
	if x != nil {
		return x.SecuritySymbol
	}
	return ""
}

func (x *HoldingDTO) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HoldingDTO) GetAvgCostCents() int64 {
	if x != nil {
		return x.AvgCostCents
	}
	return 0
}

func (x *HoldingDTO) GetMarketValueCents() int64 {
	if x != nil {
		return x.MarketValueCents
	}
	return 0
}

func (x *HoldingDTO) GetUnrealizedPnlCents() int64 {
	if x != nil {
		return x.UnrealizedPnlCents
	}
	return 0
}

func (x *HoldingDTO) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type HoldingTransactionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SecurityId    string                 `protobuf:"bytes,3,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	TradeType     TradeType              `protobuf:"varint,4,opt,name=trade_type,json=tradeType,proto3,enum=yucai.holding.v1.TradeType" json:"trade_type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceCents    int64                  `protobuf:"varint,6,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	AmountCents   int64                  `protobuf:"varint,7,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	FeeCents      int64                  `protobuf:"varint,8,opt,name=fee_cents,json=feeCents,proto3" json:"fee_cents,omitempty"`
	TradeDate     string                 `protobuf:"bytes,9,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	Notes         string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldingTransactionDTO) Reset() {
	*x = HoldingTransactionDTO{}
	mi := &file_holding_v1_holding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingTransactionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingTransactionDTO) ProtoMessage() {}

func (x *HoldingTransactionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingTransactionDTO.ProtoReflect.Descriptor instead.
func (*HoldingTransactionDTO) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{2}
}

func (x *HoldingTransactionDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HoldingTransactionDTO) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *HoldingTransactionDTO) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *HoldingTransactionDTO) GetTradeType() TradeType {
	if x != nil {
		return x.TradeType
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *HoldingTransactionDTO) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HoldingTransactionDTO) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *HoldingTransactionDTO) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *HoldingTransactionDTO) GetFeeCents() int64 {
	if x != nil {
		return x.FeeCents
	}
	return 0
}

func (x *HoldingTransactionDTO) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *HoldingTransactionDTO) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *HoldingTransactionDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SecurityType  SecurityType           `protobuf:"varint,3,opt,name=security_type,json=securityType,proto3,enum=yucai.holding.v1.SecurityType" json:"security_type,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecurityRequest) Reset() {
	*x = CreateSecurityRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecurityRequest) ProtoMessage() {}

func (x *CreateSecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecurityRequest.ProtoReflect.Descriptor instead.
func (*CreateSecurityRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSecurityRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateSecurityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecurityRequest) GetSecurityType() SecurityType {
	if x != nil {
		return x.SecurityType
	}
	return SecurityType_SECURITY_TYPE_UNSPECIFIED
}

func (x *CreateSecurityRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CreateSecurityRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type ListSecuritiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	SecurityType  SecurityType           `protobuf:"varint,2,opt,name=security_type,json=securityType,proto3,enum=yucai.holding.v1.SecurityType" json:"security_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecuritiesRequest) Reset() {
	*x = ListSecuritiesRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecuritiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecuritiesRequest) ProtoMessage() {}

func (x *ListSecuritiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecuritiesRequest.ProtoReflect.Descriptor instead.
func (*ListSecuritiesRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{4}
}

func (x *ListSecuritiesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListSecuritiesRequest) GetSecurityType() SecurityType {
	if x != nil {
		return x.SecurityType
	}
	return SecurityType_SECURITY_TYPE_UNSPECIFIED
}

type UpdatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecurityId    string                 `protobuf:"bytes,1,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	PriceCents    int64                  `protobuf:"varint,2,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceRequest) Reset() {
	*x = UpdatePriceRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceRequest) ProtoMessage() {}

func (x *UpdatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePriceRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePriceRequest) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *UpdatePriceRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

type SearchSecuritiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSecuritiesRequest) Reset() {
	*x = SearchSecuritiesRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSecuritiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSecuritiesRequest) ProtoMessage() {}

func (x *SearchSecuritiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSecuritiesRequest.ProtoReflect.Descriptor instead.
func (*SearchSecuritiesRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{6}
}

func (x *SearchSecuritiesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSecuritiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HoldingTradeRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AccountId  string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SecurityId string                 `protobuf:"bytes,2,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	Quantity   float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceCents int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	FeeCents   int64                  `protobuf:"varint,5,opt,name=fee_cents,json=feeCents,proto3" json:"fee_cents,omitempty"`
	TradeDate  string                 `protobuf:"bytes,6,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	Notes      string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	// 双写资金来源账户(cash asset,savings/investment)。BuyHolding/SellHolding 必填;
	// buy:credit(现金−);sell:debit(现金+)。
	FromAccountId string `protobuf:"bytes,8,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldingTradeRequest) Reset() {
	*x = HoldingTradeRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingTradeRequest) ProtoMessage() {}

func (x *HoldingTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingTradeRequest.ProtoReflect.Descriptor instead.
func (*HoldingTradeRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{7}
}

func (x *HoldingTradeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *HoldingTradeRequest) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *HoldingTradeRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HoldingTradeRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *HoldingTradeRequest) GetFeeCents() int64 {
	if x != nil {
		return x.FeeCents
	}
	return 0
}

func (x *HoldingTradeRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *HoldingTradeRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *HoldingTradeRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

type RecordDividendRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SecurityId        string                 `protobuf:"bytes,2,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	Quantity          float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CashPerShareCents int64                  `protobuf:"varint,4,opt,name=cash_per_share_cents,json=cashPerShareCents,proto3" json:"cash_per_share_cents,omitempty"`
	TotalAmountCents  int64                  `protobuf:"varint,5,opt,name=total_amount_cents,json=totalAmountCents,proto3" json:"total_amount_cents,omitempty"`
	TradeDate         string                 `protobuf:"bytes,6,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	Notes             string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordDividendRequest) Reset() {
	*x = RecordDividendRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDividendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDividendRequest) ProtoMessage() {}

func (x *RecordDividendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDividendRequest.ProtoReflect.Descriptor instead.
func (*RecordDividendRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{8}
}

func (x *RecordDividendRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RecordDividendRequest) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *RecordDividendRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecordDividendRequest) GetCashPerShareCents() int64 {
	if x != nil {
		return x.CashPerShareCents
	}
	return 0
}

func (x *RecordDividendRequest) GetTotalAmountCents() int64 {
	if x != nil {
		return x.TotalAmountCents
	}
	return 0
}

func (x *RecordDividendRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *RecordDividendRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RecordSplitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SecurityId    string                 `protobuf:"bytes,2,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	Ratio         float64                `protobuf:"fixed64,3,opt,name=ratio,proto3" json:"ratio,omitempty"`
	SplitDate     string                 `protobuf:"bytes,4,opt,name=split_date,json=splitDate,proto3" json:"split_date,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSplitRequest) Reset() {
	*x = RecordSplitRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSplitRequest) ProtoMessage() {}

func (x *RecordSplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSplitRequest.ProtoReflect.Descriptor instead.
func (*RecordSplitRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{9}
}

func (x *RecordSplitRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RecordSplitRequest) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *RecordSplitRequest) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *RecordSplitRequest) GetSplitDate() string {
	if x != nil {
		return x.SplitDate
	}
	return ""
}

func (x *RecordSplitRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ListHoldingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHoldingsRequest) Reset() {
	*x = ListHoldingsRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHoldingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHoldingsRequest) ProtoMessage() {}

func (x *ListHoldingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHoldingsRequest.ProtoReflect.Descriptor instead.
func (*ListHoldingsRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{10}
}

func (x *ListHoldingsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListHoldingsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SecurityId    string                 `protobuf:"bytes,2,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRequest) Reset() {
	*x = ListTradesRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRequest) ProtoMessage() {}

func (x *ListTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRequest.ProtoReflect.Descriptor instead.
func (*ListTradesRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{11}
}

func (x *ListTradesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTradesRequest) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *ListTradesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type SecurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *SecurityDTO           `protobuf:"bytes,1,opt,name=security,proto3" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{12}
}

func (x *SecurityResponse) GetSecurity() *SecurityDTO {
	if x != nil {
		return x.Security
	}
	return nil
}

type ListSecuritiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Securities    []*SecurityDTO         `protobuf:"bytes,1,rep,name=securities,proto3" json:"securities,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecuritiesResponse) Reset() {
	*x = ListSecuritiesResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecuritiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecuritiesResponse) ProtoMessage() {}

func (x *ListSecuritiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecuritiesResponse.ProtoReflect.Descriptor instead.
func (*ListSecuritiesResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{13}
}

func (x *ListSecuritiesResponse) GetSecurities() []*SecurityDTO {
	if x != nil {
		return x.Securities
	}
	return nil
}

func (x *ListSecuritiesResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type SearchSecuritiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Securities    []*SecurityDTO         `protobuf:"bytes,1,rep,name=securities,proto3" json:"securities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSecuritiesResponse) Reset() {
	*x = SearchSecuritiesResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSecuritiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSecuritiesResponse) ProtoMessage() {}

func (x *SearchSecuritiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSecuritiesResponse.ProtoReflect.Descriptor instead.
func (*SearchSecuritiesResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{14}
}

func (x *SearchSecuritiesResponse) GetSecurities() []*SecurityDTO {
	if x != nil {
		return x.Securities
	}
	return nil
}

type HoldingTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *HoldingTransactionDTO `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldingTransactionResponse) Reset() {
	*x = HoldingTransactionResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingTransactionResponse) ProtoMessage() {}

func (x *HoldingTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingTransactionResponse.ProtoReflect.Descriptor instead.
func (*HoldingTransactionResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{15}
}

func (x *HoldingTransactionResponse) GetTransaction() *HoldingTransactionDTO {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ListHoldingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holdings      []*HoldingDTO          `protobuf:"bytes,1,rep,name=holdings,proto3" json:"holdings,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHoldingsResponse) Reset() {
	*x = ListHoldingsResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHoldingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHoldingsResponse) ProtoMessage() {}

func (x *ListHoldingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHoldingsResponse.ProtoReflect.Descriptor instead.
func (*ListHoldingsResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{16}
}

func (x *ListHoldingsResponse) GetHoldings() []*HoldingDTO {
	if x != nil {
		return x.Holdings
	}
	return nil
}

func (x *ListHoldingsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListTradesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Trades        []*HoldingTransactionDTO `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	Page          *v1.PageResponse         `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesResponse) Reset() {
	*x = ListTradesResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesResponse) ProtoMessage() {}

func (x *ListTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesResponse.ProtoReflect.Descriptor instead.
func (*ListTradesResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{17}
}

func (x *ListTradesResponse) GetTrades() []*HoldingTransactionDTO {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *ListTradesResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type SyncPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPricesRequest) Reset() {
	*x = SyncPricesRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPricesRequest) ProtoMessage() {}

func (x *SyncPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPricesRequest.ProtoReflect.Descriptor instead.
func (*SyncPricesRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{18}
}

type SyncPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	SyncedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPricesResponse) Reset() {
	*x = SyncPricesResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPricesResponse) ProtoMessage() {}

func (x *SyncPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPricesResponse.ProtoReflect.Descriptor instead.
func (*SyncPricesResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{19}
}

func (x *SyncPricesResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncPricesResponse) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

type CurvePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurvePoint) Reset() {
	*x = CurvePoint{}
	mi := &file_holding_v1_holding_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurvePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurvePoint) ProtoMessage() {}

func (x *CurvePoint) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurvePoint.ProtoReflect.Descriptor instead.
func (*CurvePoint) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{20}
}

func (x *CurvePoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CurvePoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetPortfolioPerformanceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Range            CurveRange             `protobuf:"varint,2,opt,name=range,proto3,enum=yucai.holding.v1.CurveRange" json:"range,omitempty"`
	IncludeBenchmark bool                   `protobuf:"varint,3,opt,name=include_benchmark,json=includeBenchmark,proto3" json:"include_benchmark,omitempty"`
	// Base currency to convert all amounts into (ISO 4217, e.g. "CNY").
	// Empty/unknown falls back to the tenant base currency (default CNY).
	BaseCurrency  string `protobuf:"bytes,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioPerformanceRequest) Reset() {
	*x = GetPortfolioPerformanceRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioPerformanceRequest) ProtoMessage() {}

func (x *GetPortfolioPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{21}
}

func (x *GetPortfolioPerformanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetPortfolioPerformanceRequest) GetRange() CurveRange {
	if x != nil {
		return x.Range
	}
	return CurveRange_CURVE_RANGE_UNSPECIFIED
}

func (x *GetPortfolioPerformanceRequest) GetIncludeBenchmark() bool {
	if x != nil {
		return x.IncludeBenchmark
	}
	return false
}

func (x *GetPortfolioPerformanceRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type PortfolioPerformanceResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PortfolioPoints       []*CurvePoint          `protobuf:"bytes,1,rep,name=portfolio_points,json=portfolioPoints,proto3" json:"portfolio_points,omitempty"`
	BenchmarkPoints       []*CurvePoint          `protobuf:"bytes,2,rep,name=benchmark_points,json=benchmarkPoints,proto3" json:"benchmark_points,omitempty"`
	BenchmarkName         string                 `protobuf:"bytes,3,opt,name=benchmark_name,json=benchmarkName,proto3" json:"benchmark_name,omitempty"`
	RealizedCents         int64                  `protobuf:"varint,4,opt,name=realized_cents,json=realizedCents,proto3" json:"realized_cents,omitempty"`
	UnrealizedCents       int64                  `protobuf:"varint,5,opt,name=unrealized_cents,json=unrealizedCents,proto3" json:"unrealized_cents,omitempty"`
	TotalCents            int64                  `protobuf:"varint,6,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	AnnualizedPct         *float64               `protobuf:"fixed64,7,opt,name=annualized_pct,json=annualizedPct,proto3,oneof" json:"annualized_pct,omitempty"` // 全期 XIRR 年化%(nil=降级)
	TotalPct              float64                `protobuf:"fixed64,8,opt,name=total_pct,json=totalPct,proto3" json:"total_pct,omitempty"`
	Currency              string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	RangeAnnualizedPct    *float64               `protobuf:"fixed64,10,opt,name=range_annualized_pct,json=rangeAnnualizedPct,proto3,oneof" json:"range_annualized_pct,omitempty"`            // 区间 XIRR 年化%(随 CurveRange)
	TwrAnnualizedPct      *float64               `protobuf:"fixed64,11,opt,name=twr_annualized_pct,json=twrAnnualizedPct,proto3,oneof" json:"twr_annualized_pct,omitempty"`                  // TWR 时间加权年化%(全期,nil=降级)
	RangeTwrAnnualizedPct *float64               `protobuf:"fixed64,12,opt,name=range_twr_annualized_pct,json=rangeTwrAnnualizedPct,proto3,oneof" json:"range_twr_annualized_pct,omitempty"` // TWR 区间年化%(随 CurveRange,nil=降级/区间不足)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PortfolioPerformanceResponse) Reset() {
	*x = PortfolioPerformanceResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPerformanceResponse) ProtoMessage() {}

func (x *PortfolioPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPerformanceResponse.ProtoReflect.Descriptor instead.
func (*PortfolioPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{22}
}

func (x *PortfolioPerformanceResponse) GetPortfolioPoints() []*CurvePoint {
	if x != nil {
		return x.PortfolioPoints
	}
	return nil
}

func (x *PortfolioPerformanceResponse) GetBenchmarkPoints() []*CurvePoint {
	if x != nil {
		return x.BenchmarkPoints
	}
	return nil
}

func (x *PortfolioPerformanceResponse) GetBenchmarkName() string {
	if x != nil {
		return x.BenchmarkName
	}
	return ""
}

func (x *PortfolioPerformanceResponse) GetRealizedCents() int64 {
	if x != nil {
		return x.RealizedCents
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetUnrealizedCents() int64 {
	if x != nil {
		return x.UnrealizedCents
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetAnnualizedPct() float64 {
	if x != nil && x.AnnualizedPct != nil {
		return *x.AnnualizedPct
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetTotalPct() float64 {
	if x != nil {
		return x.TotalPct
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PortfolioPerformanceResponse) GetRangeAnnualizedPct() float64 {
	if x != nil && x.RangeAnnualizedPct != nil {
		return *x.RangeAnnualizedPct
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetTwrAnnualizedPct() float64 {
	if x != nil && x.TwrAnnualizedPct != nil {
		return *x.TwrAnnualizedPct
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetRangeTwrAnnualizedPct() float64 {
	if x != nil && x.RangeTwrAnnualizedPct != nil {
		return *x.RangeTwrAnnualizedPct
	}
	return 0
}

type GetHoldingPerformanceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	HoldingId string                 `protobuf:"bytes,1,opt,name=holding_id,json=holdingId,proto3" json:"holding_id,omitempty"`
	Range     CurveRange             `protobuf:"varint,2,opt,name=range,proto3,enum=yucai.holding.v1.CurveRange" json:"range,omitempty"`
	// Base currency to convert all amounts into (ISO 4217, e.g. "CNY").
	// Empty/unknown falls back to the tenant base currency (default CNY).
	BaseCurrency  string `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingPerformanceRequest) Reset() {
	*x = GetHoldingPerformanceRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingPerformanceRequest) ProtoMessage() {}

func (x *GetHoldingPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetHoldingPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{23}
}

func (x *GetHoldingPerformanceRequest) GetHoldingId() string {
	if x != nil {
		return x.HoldingId
	}
	return ""
}

func (x *GetHoldingPerformanceRequest) GetRange() CurveRange {
	if x != nil {
		return x.Range
	}
	return CurveRange_CURVE_RANGE_UNSPECIFIED
}

func (x *GetHoldingPerformanceRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type HoldingPerformanceResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PricePoints        []*CurvePoint          `protobuf:"bytes,1,rep,name=price_points,json=pricePoints,proto3" json:"price_points,omitempty"`
	RealizedCents      int64                  `protobuf:"varint,2,opt,name=realized_cents,json=realizedCents,proto3" json:"realized_cents,omitempty"`
	UnrealizedCents    int64                  `protobuf:"varint,3,opt,name=unrealized_cents,json=unrealizedCents,proto3" json:"unrealized_cents,omitempty"`
	TotalCents         int64                  `protobuf:"varint,4,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	AnnualizedPct      *float64               `protobuf:"fixed64,6,opt,name=annualized_pct,json=annualizedPct,proto3,oneof" json:"annualized_pct,omitempty"`                  // 全期 XIRR(原币)
	RangeAnnualizedPct *float64               `protobuf:"fixed64,7,opt,name=range_annualized_pct,json=rangeAnnualizedPct,proto3,oneof" json:"range_annualized_pct,omitempty"` // 区间 XIRR(原币)
	TwrAnnualizedPct   *float64               `protobuf:"fixed64,8,opt,name=twr_annualized_pct,json=twrAnnualizedPct,proto3,oneof" json:"twr_annualized_pct,omitempty"`       // TWR(原币,全期,nil=降级)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HoldingPerformanceResponse) Reset() {
	*x = HoldingPerformanceResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingPerformanceResponse) ProtoMessage() {}

func (x *HoldingPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingPerformanceResponse.ProtoReflect.Descriptor instead.
func (*HoldingPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{24}
}

func (x *HoldingPerformanceResponse) GetPricePoints() []*CurvePoint {
	if x != nil {
		return x.PricePoints
	}
	return nil
}

func (x *HoldingPerformanceResponse) GetRealizedCents() int64 {
	if x != nil {
		return x.RealizedCents
	}
	return 0
}

func (x *HoldingPerformanceResponse) GetUnrealizedCents() int64 {
	if x != nil {
		return x.UnrealizedCents
	}
	return 0
}

func (x *HoldingPerformanceResponse) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *HoldingPerformanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *HoldingPerformanceResponse) GetAnnualizedPct() float64 {
	if x != nil && x.AnnualizedPct != nil {
		return *x.AnnualizedPct
	}
	return 0
}

func (x *HoldingPerformanceResponse) GetRangeAnnualizedPct() float64 {
	if x != nil && x.RangeAnnualizedPct != nil {
		return *x.RangeAnnualizedPct
	}
	return 0
}

func (x *HoldingPerformanceResponse) GetTwrAnnualizedPct() float64 {
	if x != nil && x.TwrAnnualizedPct != nil {
		return *x.TwrAnnualizedPct
	}
	return 0
}

type BackfillPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         CurveRange             `protobuf:"varint,1,opt,name=range,proto3,enum=yucai.holding.v1.CurveRange" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillPriceHistoryRequest) Reset() {
	*x = BackfillPriceHistoryRequest{}
	mi := &file_holding_v1_holding_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillPriceHistoryRequest) ProtoMessage() {}

func (x *BackfillPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*BackfillPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{25}
}

func (x *BackfillPriceHistoryRequest) GetRange() CurveRange {
	if x != nil {
		return x.Range
	}
	return CurveRange_CURVE_RANGE_UNSPECIFIED
}

type BackfillPriceHistoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackfilledCount int32                  `protobuf:"varint,1,opt,name=backfilled_count,json=backfilledCount,proto3" json:"backfilled_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BackfillPriceHistoryResponse) Reset() {
	*x = BackfillPriceHistoryResponse{}
	mi := &file_holding_v1_holding_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillPriceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillPriceHistoryResponse) ProtoMessage() {}

func (x *BackfillPriceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holding_v1_holding_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillPriceHistoryResponse.ProtoReflect.Descriptor instead.
func (*BackfillPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_holding_v1_holding_proto_rawDescGZIP(), []int{26}
}

func (x *BackfillPriceHistoryResponse) GetBackfilledCount() int32 {
	if x != nil {
		return x.BackfilledCount
	}
	return 0
}

var File_holding_v1_holding_proto protoreflect.FileDescriptor

const file_holding_v1_holding_proto_rawDesc = "" +
	"\n" +
	"\x18holding/v1/holding.proto\x12\x10yucai.holding.v1\x1a\x1acommon/v1/pagination.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n" +
	"\vSecurityDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12C\n" +
	"\rsecurity_type\x18\x04 \x01(\x0e2\x1e.yucai.holding.v1.SecurityTypeR\fsecurityType\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12.\n" +
	"\x13current_price_cents\x18\a \x01(\x03R\x11currentPriceCents\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe6\x02\n" +
	"\n" +
	"HoldingDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1f\n" +
	"\vsecurity_id\x18\x03 \x01(\tR\n" +
	"securityId\x12#\n" +
	"\rsecurity_name\x18\x04 \x01(\tR\fsecurityName\x12'\n" +
	"\x0fsecurity_symbol\x18\x05 \x01(\tR\x0esecuritySymbol\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12$\n" +
	"\x0eavg_cost_cents\x18\a \x01(\x03R\favgCostCents\x12,\n" +
	"\x12market_value_cents\x18\b \x01(\x03R\x10marketValueCents\x120\n" +
	"\x14unrealized_pnl_cents\x18\t \x01(\x03R\x12unrealizedPnlCents\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\"\x90\x03\n" +
	"\x15HoldingTransactionDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1f\n" +
	"\vsecurity_id\x18\x03 \x01(\tR\n" +
	"securityId\x12:\n" +
	"\n" +
	"trade_type\x18\x04 \x01(\x0e2\x1b.yucai.holding.v1.TradeTypeR\ttradeType\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vprice_cents\x18\x06 \x01(\x03R\n" +
	"priceCents\x12!\n" +
	"\famount_cents\x18\a \x01(\x03R\vamountCents\x12\x1b\n" +
	"\tfee_cents\x18\b \x01(\x03R\bfeeCents\x12\x1d\n" +
	"\n" +
	"trade_date\x18\t \x01(\tR\ttradeDate\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc9\x01\n" +
	"\x15CreateSecurityRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12C\n" +
	"\rsecurity_type\x18\x03 \x01(\x0e2\x1e.yucai.holding.v1.SecurityTypeR\fsecurityType\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\"\x8e\x01\n" +
	"\x15ListSecuritiesRequest\x120\n" +
	"\x04page\x18\x01 \x01(\v2\x1c.yucai.common.v1.PageRequestR\x04page\x12C\n" +
	"\rsecurity_type\x18\x02 \x01(\x0e2\x1e.yucai.holding.v1.SecurityTypeR\fsecurityType\"V\n" +
	"\x12UpdatePriceRequest\x12\x1f\n" +
	"\vsecurity_id\x18\x01 \x01(\tR\n" +
	"securityId\x12\x1f\n" +
	"\vprice_cents\x18\x02 \x01(\x03R\n" +
	"priceCents\"E\n" +
	"\x17SearchSecuritiesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x8c\x02\n" +
	"\x13HoldingTradeRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vsecurity_id\x18\x02 \x01(\tR\n" +
	"securityId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x1b\n" +
	"\tfee_cents\x18\x05 \x01(\x03R\bfeeCents\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x06 \x01(\tR\ttradeDate\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12&\n" +
	"\x0ffrom_account_id\x18\b \x01(\tR\rfromAccountId\"\x87\x02\n" +
	"\x15RecordDividendRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vsecurity_id\x18\x02 \x01(\tR\n" +
	"securityId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12/\n" +
	"\x14cash_per_share_cents\x18\x04 \x01(\x03R\x11cashPerShareCents\x12,\n" +
	"\x12total_amount_cents\x18\x05 \x01(\x03R\x10totalAmountCents\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x06 \x01(\tR\ttradeDate\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"\x9f\x01\n" +
	"\x12RecordSplitRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vsecurity_id\x18\x02 \x01(\tR\n" +
	"securityId\x12\x14\n" +
	"\x05ratio\x18\x03 \x01(\x01R\x05ratio\x12\x1d\n" +
	"\n" +
	"split_date\x18\x04 \x01(\tR\tsplitDate\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"f\n" +
	"\x13ListHoldingsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x120\n" +
	"\x04page\x18\x02 \x01(\v2\x1c.yucai.common.v1.PageRequestR\x04page\"\x85\x01\n" +
	"\x11ListTradesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vsecurity_id\x18\x02 \x01(\tR\n" +
	"securityId\x120\n" +
	"\x04page\x18\x03 \x01(\v2\x1c.yucai.common.v1.PageRequestR\x04page\"M\n" +
	"\x10SecurityResponse\x129\n" +
	"\bsecurity\x18\x01 \x01(\v2\x1d.yucai.holding.v1.SecurityDTOR\bsecurity\"\x8a\x01\n" +
	"\x16ListSecuritiesResponse\x12=\n" +
	"\n" +
	"securities\x18\x01 \x03(\v2\x1d.yucai.holding.v1.SecurityDTOR\n" +
	"securities\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.yucai.common.v1.PageResponseR\x04page\"Y\n" +
	"\x18SearchSecuritiesResponse\x12=\n" +
	"\n" +
	"securities\x18\x01 \x03(\v2\x1d.yucai.holding.v1.SecurityDTOR\n" +
	"securities\"g\n" +
	"\x1aHoldingTransactionResponse\x12I\n" +
	"\vtransaction\x18\x01 \x01(\v2'.yucai.holding.v1.HoldingTransactionDTOR\vtransaction\"\x83\x01\n" +
	"\x14ListHoldingsResponse\x128\n" +
	"\bholdings\x18\x01 \x03(\v2\x1c.yucai.holding.v1.HoldingDTOR\bholdings\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.yucai.common.v1.PageResponseR\x04page\"\x88\x01\n" +
	"\x12ListTradesResponse\x12?\n" +
	"\x06trades\x18\x01 \x03(\v2'.yucai.holding.v1.HoldingTransactionDTOR\x06trades\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.yucai.common.v1.PageResponseR\x04page\"\x13\n" +
	"\x11SyncPricesRequest\"p\n" +
	"\x12SyncPricesResponse\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x127\n" +
	"\tsynced_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt\"R\n" +
	"\n" +
	"CurvePoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xc5\x01\n" +
	"\x1eGetPortfolioPerformanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x122\n" +
	"\x05range\x18\x02 \x01(\x0e2\x1c.yucai.holding.v1.CurveRangeR\x05range\x12+\n" +
	"\x11include_benchmark\x18\x03 \x01(\bR\x10includeBenchmark\x12#\n" +
	"\rbase_currency\x18\x04 \x01(\tR\fbaseCurrency\"\xb7\x05\n" +
	"\x1cPortfolioPerformanceResponse\x12G\n" +
	"\x10portfolio_points\x18\x01 \x03(\v2\x1c.yucai.holding.v1.CurvePointR\x0fportfolioPoints\x12G\n" +
	"\x10benchmark_points\x18\x02 \x03(\v2\x1c.yucai.holding.v1.CurvePointR\x0fbenchmarkPoints\x12%\n" +
	"\x0ebenchmark_name\x18\x03 \x01(\tR\rbenchmarkName\x12%\n" +
	"\x0erealized_cents\x18\x04 \x01(\x03R\rrealizedCents\x12)\n" +
	"\x10unrealized_cents\x18\x05 \x01(\x03R\x0funrealizedCents\x12\x1f\n" +
	"\vtotal_cents\x18\x06 \x01(\x03R\n" +
	"totalCents\x12*\n" +
	"\x0eannualized_pct\x18\a \x01(\x01H\x00R\rannualizedPct\x88\x01\x01\x12\x1b\n" +
	"\ttotal_pct\x18\b \x01(\x01R\btotalPct\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x125\n" +
	"\x14range_annualized_pct\x18\n" +
	" \x01(\x01H\x01R\x12rangeAnnualizedPct\x88\x01\x01\x121\n" +
	"\x12twr_annualized_pct\x18\v \x01(\x01H\x02R\x10twrAnnualizedPct\x88\x01\x01\x12<\n" +
	"\x18range_twr_annualized_pct\x18\f \x01(\x01H\x03R\x15rangeTwrAnnualizedPct\x88\x01\x01B\x11\n" +
	"\x0f_annualized_pctB\x17\n" +
	"\x15_range_annualized_pctB\x15\n" +
	"\x13_twr_annualized_pctB\x1b\n" +
	"\x19_range_twr_annualized_pct\"\x96\x01\n" +
	"\x1cGetHoldingPerformanceRequest\x12\x1d\n" +
	"\n" +
	"holding_id\x18\x01 \x01(\tR\tholdingId\x122\n" +
	"\x05range\x18\x02 \x01(\x0e2\x1c.yucai.holding.v1.CurveRangeR\x05range\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\"\xc5\x03\n" +
	"\x1aHoldingPerformanceResponse\x12?\n" +
	"\fprice_points\x18\x01 \x03(\v2\x1c.yucai.holding.v1.CurvePointR\vpricePoints\x12%\n" +
	"\x0erealized_cents\x18\x02 \x01(\x03R\rrealizedCents\x12)\n" +
	"\x10unrealized_cents\x18\x03 \x01(\x03R\x0funrealizedCents\x12\x1f\n" +
	"\vtotal_cents\x18\x04 \x01(\x03R\n" +
	"totalCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12*\n" +
	"\x0eannualized_pct\x18\x06 \x01(\x01H\x00R\rannualizedPct\x88\x01\x01\x125\n" +
	"\x14range_annualized_pct\x18\a \x01(\x01H\x01R\x12rangeAnnualizedPct\x88\x01\x01\x121\n" +
	"\x12twr_annualized_pct\x18\b \x01(\x01H\x02R\x10twrAnnualizedPct\x88\x01\x01B\x11\n" +
	"\x0f_annualized_pctB\x17\n" +
	"\x15_range_annualized_pctB\x15\n" +
	"\x13_twr_annualized_pct\"Q\n" +
	"\x1bBackfillPriceHistoryRequest\x122\n" +
	"\x05range\x18\x01 \x01(\x0e2\x1c.yucai.holding.v1.CurveRangeR\x05range\"I\n" +
	"\x1cBackfillPriceHistoryResponse\x12)\n" +
	"\x10backfilled_count\x18\x01 \x01(\x05R\x0fbackfilledCount*\xd8\x01\n" +
	"\fSecurityType\x12\x1d\n" +
	"\x19SECURITY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SECURITY_TYPE_STOCK\x10\x01\x12\x16\n" +
	"\x12SECURITY_TYPE_FUND\x10\x02\x12\x15\n" +
	"\x11SECURITY_TYPE_ETF\x10\x03\x12\x16\n" +
	"\x12SECURITY_TYPE_BOND\x10\x04\x12\x16\n" +
	"\x12SECURITY_TYPE_GOLD\x10\x05\x12\x18\n" +
	"\x14SECURITY_TYPE_OPTION\x10\x06\x12\x17\n" +
	"\x13SECURITY_TYPE_OTHER\x10\a*\x7f\n" +
	"\tTradeType\x12\x1a\n" +
	"\x16TRADE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTRADE_TYPE_BUY\x10\x01\x12\x13\n" +
	"\x0fTRADE_TYPE_SELL\x10\x02\x12\x17\n" +
	"\x13TRADE_TYPE_DIVIDEND\x10\x03\x12\x14\n" +
	"\x10TRADE_TYPE_SPLIT\x10\x04*k\n" +
	"\n" +
	"CurveRange\x12\x1b\n" +
	"\x17CURVE_RANGE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCURVE_RANGE_DAY\x10\x01\x12\x15\n" +
	"\x11CURVE_RANGE_MONTH\x10\x02\x12\x14\n" +
	"\x10CURVE_RANGE_YEAR\x10\x032\xb0\v\n" +
	"\x0eHoldingService\x12]\n" +
	"\x0eCreateSecurity\x12'.yucai.holding.v1.CreateSecurityRequest\x1a\".yucai.holding.v1.SecurityResponse\x12c\n" +
	"\x0eListSecurities\x12'.yucai.holding.v1.ListSecuritiesRequest\x1a(.yucai.holding.v1.ListSecuritiesResponse\x12S\n" +
	"\x13UpdateSecurityPrice\x12$.yucai.holding.v1.UpdatePriceRequest\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\x10SearchSecurities\x12).yucai.holding.v1.SearchSecuritiesRequest\x1a*.yucai.holding.v1.SearchSecuritiesResponse\x12a\n" +
	"\n" +
	"BuyHolding\x12%.yucai.holding.v1.HoldingTradeRequest\x1a,.yucai.holding.v1.HoldingTransactionResponse\x12b\n" +
	"\vSellHolding\x12%.yucai.holding.v1.HoldingTradeRequest\x1a,.yucai.holding.v1.HoldingTransactionResponse\x12g\n" +
	"\x0eRecordDividend\x12'.yucai.holding.v1.RecordDividendRequest\x1a,.yucai.holding.v1.HoldingTransactionResponse\x12a\n" +
	"\vRecordSplit\x12$.yucai.holding.v1.RecordSplitRequest\x1a,.yucai.holding.v1.HoldingTransactionResponse\x12]\n" +
	"\fListHoldings\x12%.yucai.holding.v1.ListHoldingsRequest\x1a&.yucai.holding.v1.ListHoldingsResponse\x12d\n" +
	"\x17ListHoldingTransactions\x12#.yucai.holding.v1.ListTradesRequest\x1a$.yucai.holding.v1.ListTradesResponse\x12W\n" +
	"\n" +
	"SyncPrices\x12#.yucai.holding.v1.SyncPricesRequest\x1a$.yucai.holding.v1.SyncPricesResponse\x12{\n" +
	"\x17GetPortfolioPerformance\x120.yucai.holding.v1.GetPortfolioPerformanceRequest\x1a..yucai.holding.v1.PortfolioPerformanceResponse\x12u\n" +
	"\x15GetHoldingPerformance\x12..yucai.holding.v1.GetHoldingPerformanceRequest\x1a,.yucai.holding.v1.HoldingPerformanceResponse\x12u\n" +
	"\x14BackfillPriceHistory\x12-.yucai.holding.v1.BackfillPriceHistoryRequest\x1a..yucai.holding.v1.BackfillPriceHistoryResponseB\xc3\x01\n" +
	"\x14com.yucai.holding.v1B\fHoldingProtoP\x01Z;github.com/yucai/server/internal/proto/holding/v1;holdingv1\xa2\x02\x03YHX\xaa\x02\x10Yucai.Holding.V1\xca\x02\x10Yucai\\Holding\\V1\xe2\x02\x1cYucai\\Holding\\V1\\GPBMetadata\xea\x02\x12Yucai::Holding::V1b\x06proto3"

var (
	file_holding_v1_holding_proto_rawDescOnce sync.Once
	file_holding_v1_holding_proto_rawDescData []byte
)

func file_holding_v1_holding_proto_rawDescGZIP() []byte {
	file_holding_v1_holding_proto_rawDescOnce.Do(func() {
		file_holding_v1_holding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_holding_v1_holding_proto_rawDesc), len(file_holding_v1_holding_proto_rawDesc)))
	})
	return file_holding_v1_holding_proto_rawDescData
}

var file_holding_v1_holding_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_holding_v1_holding_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_holding_v1_holding_proto_goTypes = []any{
	(SecurityType)(0),                      // 0: yucai.holding.v1.SecurityType
	(TradeType)(0),                         // 1: yucai.holding.v1.TradeType
	(CurveRange)(0),                        // 2: yucai.holding.v1.CurveRange
	(*SecurityDTO)(nil),                    // 3: yucai.holding.v1.SecurityDTO
	(*HoldingDTO)(nil),                     // 4: yucai.holding.v1.HoldingDTO
	(*HoldingTransactionDTO)(nil),          // 5: yucai.holding.v1.HoldingTransactionDTO
	(*CreateSecurityRequest)(nil),          // 6: yucai.holding.v1.CreateSecurityRequest
	(*ListSecuritiesRequest)(nil),          // 7: yucai.holding.v1.ListSecuritiesRequest
	(*UpdatePriceRequest)(nil),             // 8: yucai.holding.v1.UpdatePriceRequest
	(*SearchSecuritiesRequest)(nil),        // 9: yucai.holding.v1.SearchSecuritiesRequest
	(*HoldingTradeRequest)(nil),            // 10: yucai.holding.v1.HoldingTradeRequest
	(*RecordDividendRequest)(nil),          // 11: yucai.holding.v1.RecordDividendRequest
	(*RecordSplitRequest)(nil),             // 12: yucai.holding.v1.RecordSplitRequest
	(*ListHoldingsRequest)(nil),            // 13: yucai.holding.v1.ListHoldingsRequest
	(*ListTradesRequest)(nil),              // 14: yucai.holding.v1.ListTradesRequest
	(*SecurityResponse)(nil),               // 15: yucai.holding.v1.SecurityResponse
	(*ListSecuritiesResponse)(nil),         // 16: yucai.holding.v1.ListSecuritiesResponse
	(*SearchSecuritiesResponse)(nil),       // 17: yucai.holding.v1.SearchSecuritiesResponse
	(*HoldingTransactionResponse)(nil),     // 18: yucai.holding.v1.HoldingTransactionResponse
	(*ListHoldingsResponse)(nil),           // 19: yucai.holding.v1.ListHoldingsResponse
	(*ListTradesResponse)(nil),             // 20: yucai.holding.v1.ListTradesResponse
	(*SyncPricesRequest)(nil),              // 21: yucai.holding.v1.SyncPricesRequest
	(*SyncPricesResponse)(nil),             // 22: yucai.holding.v1.SyncPricesResponse
	(*CurvePoint)(nil),                     // 23: yucai.holding.v1.CurvePoint
	(*GetPortfolioPerformanceRequest)(nil), // 24: yucai.holding.v1.GetPortfolioPerformanceRequest
	(*PortfolioPerformanceResponse)(nil),   // 25: yucai.holding.v1.PortfolioPerformanceResponse
	(*GetHoldingPerformanceRequest)(nil),   // 26: yucai.holding.v1.GetHoldingPerformanceRequest
	(*HoldingPerformanceResponse)(nil),     // 27: yucai.holding.v1.HoldingPerformanceResponse
	(*BackfillPriceHistoryRequest)(nil),    // 28: yucai.holding.v1.BackfillPriceHistoryRequest
	(*BackfillPriceHistoryResponse)(nil),   // 29: yucai.holding.v1.BackfillPriceHistoryResponse
	(*timestamppb.Timestamp)(nil),          // 30: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),                 // 31: yucai.common.v1.PageRequest
	(*v1.PageResponse)(nil),                // 32: yucai.common.v1.PageResponse
	(*emptypb.Empty)(nil),                  // 33: google.protobuf.Empty
}
var file_holding_v1_holding_proto_depIdxs = []int32{
	0,  // 0: yucai.holding.v1.SecurityDTO.security_type:type_name -> yucai.holding.v1.SecurityType
	30, // 1: yucai.holding.v1.SecurityDTO.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: yucai.holding.v1.HoldingTransactionDTO.trade_type:type_name -> yucai.holding.v1.TradeType
	30, // 3: yucai.holding.v1.HoldingTransactionDTO.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: yucai.holding.v1.CreateSecurityRequest.security_type:type_name -> yucai.holding.v1.SecurityType
	31, // 5: yucai.holding.v1.ListSecuritiesRequest.page:type_name -> yucai.common.v1.PageRequest
	0,  // 6: yucai.holding.v1.ListSecuritiesRequest.security_type:type_name -> yucai.holding.v1.SecurityType
	31, // 7: yucai.holding.v1.ListHoldingsRequest.page:type_name -> yucai.common.v1.PageRequest
	31, // 8: yucai.holding.v1.ListTradesRequest.page:type_name -> yucai.common.v1.PageRequest
	3,  // 9: yucai.holding.v1.SecurityResponse.security:type_name -> yucai.holding.v1.SecurityDTO
	3,  // 10: yucai.holding.v1.ListSecuritiesResponse.securities:type_name -> yucai.holding.v1.SecurityDTO
	32, // 11: yucai.holding.v1.ListSecuritiesResponse.page:type_name -> yucai.common.v1.PageResponse
	3,  // 12: yucai.holding.v1.SearchSecuritiesResponse.securities:type_name -> yucai.holding.v1.SecurityDTO
	5,  // 13: yucai.holding.v1.HoldingTransactionResponse.transaction:type_name -> yucai.holding.v1.HoldingTransactionDTO
	4,  // 14: yucai.holding.v1.ListHoldingsResponse.holdings:type_name -> yucai.holding.v1.HoldingDTO
	32, // 15: yucai.holding.v1.ListHoldingsResponse.page:type_name -> yucai.common.v1.PageResponse
	5,  // 16: yucai.holding.v1.ListTradesResponse.trades:type_name -> yucai.holding.v1.HoldingTransactionDTO
	32, // 17: yucai.holding.v1.ListTradesResponse.page:type_name -> yucai.common.v1.PageResponse
	30, // 18: yucai.holding.v1.SyncPricesResponse.synced_at:type_name -> google.protobuf.Timestamp
	30, // 19: yucai.holding.v1.CurvePoint.time:type_name -> google.protobuf.Timestamp
	2,  // 20: yucai.holding.v1.GetPortfolioPerformanceRequest.range:type_name -> yucai.holding.v1.CurveRange
	23, // 21: yucai.holding.v1.PortfolioPerformanceResponse.portfolio_points:type_name -> yucai.holding.v1.CurvePoint
	23, // 22: yucai.holding.v1.PortfolioPerformanceResponse.benchmark_points:type_name -> yucai.holding.v1.CurvePoint
	2,  // 23: yucai.holding.v1.GetHoldingPerformanceRequest.range:type_name -> yucai.holding.v1.CurveRange
	23, // 24: yucai.holding.v1.HoldingPerformanceResponse.price_points:type_name -> yucai.holding.v1.CurvePoint
	2,  // 25: yucai.holding.v1.BackfillPriceHistoryRequest.range:type_name -> yucai.holding.v1.CurveRange
	6,  // 26: yucai.holding.v1.HoldingService.CreateSecurity:input_type -> yucai.holding.v1.CreateSecurityRequest
	7,  // 27: yucai.holding.v1.HoldingService.ListSecurities:input_type -> yucai.holding.v1.ListSecuritiesRequest
	8,  // 28: yucai.holding.v1.HoldingService.UpdateSecurityPrice:input_type -> yucai.holding.v1.UpdatePriceRequest
	9,  // 29: yucai.holding.v1.HoldingService.SearchSecurities:input_type -> yucai.holding.v1.SearchSecuritiesRequest
	10, // 30: yucai.holding.v1.HoldingService.BuyHolding:input_type -> yucai.holding.v1.HoldingTradeRequest
	10, // 31: yucai.holding.v1.HoldingService.SellHolding:input_type -> yucai.holding.v1.HoldingTradeRequest
	11, // 32: yucai.holding.v1.HoldingService.RecordDividend:input_type -> yucai.holding.v1.RecordDividendRequest
	12, // 33: yucai.holding.v1.HoldingService.RecordSplit:input_type -> yucai.holding.v1.RecordSplitRequest
	13, // 34: yucai.holding.v1.HoldingService.ListHoldings:input_type -> yucai.holding.v1.ListHoldingsRequest
	14, // 35: yucai.holding.v1.HoldingService.ListHoldingTransactions:input_type -> yucai.holding.v1.ListTradesRequest
	21, // 36: yucai.holding.v1.HoldingService.SyncPrices:input_type -> yucai.holding.v1.SyncPricesRequest
	24, // 37: yucai.holding.v1.HoldingService.GetPortfolioPerformance:input_type -> yucai.holding.v1.GetPortfolioPerformanceRequest
	26, // 38: yucai.holding.v1.HoldingService.GetHoldingPerformance:input_type -> yucai.holding.v1.GetHoldingPerformanceRequest
	28, // 39: yucai.holding.v1.HoldingService.BackfillPriceHistory:input_type -> yucai.holding.v1.BackfillPriceHistoryRequest
	15, // 40: yucai.holding.v1.HoldingService.CreateSecurity:output_type -> yucai.holding.v1.SecurityResponse
	16, // 41: yucai.holding.v1.HoldingService.ListSecurities:output_type -> yucai.holding.v1.ListSecuritiesResponse
	33, // 42: yucai.holding.v1.HoldingService.UpdateSecurityPrice:output_type -> google.protobuf.Empty
	17, // 43: yucai.holding.v1.HoldingService.SearchSecurities:output_type -> yucai.holding.v1.SearchSecuritiesResponse
	18, // 44: yucai.holding.v1.HoldingService.BuyHolding:output_type -> yucai.holding.v1.HoldingTransactionResponse
	18, // 45: yucai.holding.v1.HoldingService.SellHolding:output_type -> yucai.holding.v1.HoldingTransactionResponse
	18, // 46: yucai.holding.v1.HoldingService.RecordDividend:output_type -> yucai.holding.v1.HoldingTransactionResponse
	18, // 47: yucai.holding.v1.HoldingService.RecordSplit:output_type -> yucai.holding.v1.HoldingTransactionResponse
	19, // 48: yucai.holding.v1.HoldingService.ListHoldings:output_type -> yucai.holding.v1.ListHoldingsResponse
	20, // 49: yucai.holding.v1.HoldingService.ListHoldingTransactions:output_type -> yucai.holding.v1.ListTradesResponse
	22, // 50: yucai.holding.v1.HoldingService.SyncPrices:output_type -> yucai.holding.v1.SyncPricesResponse
	25, // 51: yucai.holding.v1.HoldingService.GetPortfolioPerformance:output_type -> yucai.holding.v1.PortfolioPerformanceResponse
	27, // 52: yucai.holding.v1.HoldingService.GetHoldingPerformance:output_type -> yucai.holding.v1.HoldingPerformanceResponse
	29, // 53: yucai.holding.v1.HoldingService.BackfillPriceHistory:output_type -> yucai.holding.v1.BackfillPriceHistoryResponse
	40, // [40:54] is the sub-list for method output_type
	26, // [26:40] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_holding_v1_holding_proto_init() }
func file_holding_v1_holding_proto_init() {
	if File_holding_v1_holding_proto != nil {
		return
	}
	file_holding_v1_holding_proto_msgTypes[22].OneofWrappers = []any{}
	file_holding_v1_holding_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_holding_v1_holding_proto_rawDesc), len(file_holding_v1_holding_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_holding_v1_holding_proto_goTypes,
		DependencyIndexes: file_holding_v1_holding_proto_depIdxs,
		EnumInfos:         file_holding_v1_holding_proto_enumTypes,
		MessageInfos:      file_holding_v1_holding_proto_msgTypes,
	}.Build()
	File_holding_v1_holding_proto = out.File
	file_holding_v1_holding_proto_goTypes = nil
	file_holding_v1_holding_proto_depIdxs = nil
}
