// Code generated by ent, DO NOT EDIT.

package debtdetails

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/yucai/server/internal/debt/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldTenantID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldAccountID, v))
}

// Counterparty applies equality check predicate on the "counterparty" field. It's identical to CounterpartyEQ.
func Counterparty(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCounterparty, v))
}

// InterestRate applies equality check predicate on the "interest_rate" field. It's identical to InterestRateEQ.
func InterestRate(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldInterestRate, v))
}

// AmortizationMethod applies equality check predicate on the "amortization_method" field. It's identical to AmortizationMethodEQ.
func AmortizationMethod(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldAmortizationMethod, v))
}

// Cycle applies equality check predicate on the "cycle" field. It's identical to CycleEQ.
func Cycle(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCycle, v))
}

// Interval applies equality check predicate on the "interval" field. It's identical to IntervalEQ.
func Interval(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldInterval, v))
}

// WeekdayMask applies equality check predicate on the "weekday_mask" field. It's identical to WeekdayMaskEQ.
func WeekdayMask(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldWeekdayMask, v))
}

// MonthlyMode applies equality check predicate on the "monthly_mode" field. It's identical to MonthlyModeEQ.
func MonthlyMode(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldMonthlyMode, v))
}

// Nth applies equality check predicate on the "nth" field. It's identical to NthEQ.
func Nth(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldNth, v))
}

// InterestWaivedCents applies equality check predicate on the "interest_waived_cents" field. It's identical to InterestWaivedCentsEQ.
func InterestWaivedCents(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldInterestWaivedCents, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldStartDate, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldDueDate, v))
}

// TotalPrincipalCents applies equality check predicate on the "total_principal_cents" field. It's identical to TotalPrincipalCentsEQ.
func TotalPrincipalCents(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldTotalPrincipalCents, v))
}

// DebtType applies equality check predicate on the "debt_type" field. It's identical to DebtTypeEQ.
func DebtType(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldDebtType, v))
}

// Subtype applies equality check predicate on the "subtype" field. It's identical to SubtypeEQ.
func Subtype(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldSubtype, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldVersion, v))
}

// Contact applies equality check predicate on the "contact" field. It's identical to ContactEQ.
func Contact(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldContact, v))
}

// ContractRef applies equality check predicate on the "contract_ref" field. It's identical to ContractRefEQ.
func ContractRef(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldContractRef, v))
}

// CollectionAccountID applies equality check predicate on the "collection_account_id" field. It's identical to CollectionAccountIDEQ.
func CollectionAccountID(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCollectionAccountID, v))
}

// GuarantorName applies equality check predicate on the "guarantor_name" field. It's identical to GuarantorNameEQ.
func GuarantorName(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldGuarantorName, v))
}

// GuarantorContact applies equality check predicate on the "guarantor_contact" field. It's identical to GuarantorContactEQ.
func GuarantorContact(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldGuarantorContact, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldTenantID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldAccountID, v))
}

// CounterpartyEQ applies the EQ predicate on the "counterparty" field.
func CounterpartyEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCounterparty, v))
}

// CounterpartyNEQ applies the NEQ predicate on the "counterparty" field.
func CounterpartyNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldCounterparty, v))
}

// CounterpartyIn applies the In predicate on the "counterparty" field.
func CounterpartyIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldCounterparty, vs...))
}

// CounterpartyNotIn applies the NotIn predicate on the "counterparty" field.
func CounterpartyNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldCounterparty, vs...))
}

// CounterpartyGT applies the GT predicate on the "counterparty" field.
func CounterpartyGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldCounterparty, v))
}

// CounterpartyGTE applies the GTE predicate on the "counterparty" field.
func CounterpartyGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldCounterparty, v))
}

// CounterpartyLT applies the LT predicate on the "counterparty" field.
func CounterpartyLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldCounterparty, v))
}

// CounterpartyLTE applies the LTE predicate on the "counterparty" field.
func CounterpartyLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldCounterparty, v))
}

// CounterpartyContains applies the Contains predicate on the "counterparty" field.
func CounterpartyContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldCounterparty, v))
}

// CounterpartyHasPrefix applies the HasPrefix predicate on the "counterparty" field.
func CounterpartyHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldCounterparty, v))
}

// CounterpartyHasSuffix applies the HasSuffix predicate on the "counterparty" field.
func CounterpartyHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldCounterparty, v))
}

// CounterpartyEqualFold applies the EqualFold predicate on the "counterparty" field.
func CounterpartyEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldCounterparty, v))
}

// CounterpartyContainsFold applies the ContainsFold predicate on the "counterparty" field.
func CounterpartyContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldCounterparty, v))
}

// InterestRateEQ applies the EQ predicate on the "interest_rate" field.
func InterestRateEQ(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldInterestRate, v))
}

// InterestRateNEQ applies the NEQ predicate on the "interest_rate" field.
func InterestRateNEQ(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldInterestRate, v))
}

// InterestRateIn applies the In predicate on the "interest_rate" field.
func InterestRateIn(vs ...float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldInterestRate, vs...))
}

// InterestRateNotIn applies the NotIn predicate on the "interest_rate" field.
func InterestRateNotIn(vs ...float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldInterestRate, vs...))
}

// InterestRateGT applies the GT predicate on the "interest_rate" field.
func InterestRateGT(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldInterestRate, v))
}

// InterestRateGTE applies the GTE predicate on the "interest_rate" field.
func InterestRateGTE(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldInterestRate, v))
}

// InterestRateLT applies the LT predicate on the "interest_rate" field.
func InterestRateLT(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldInterestRate, v))
}

// InterestRateLTE applies the LTE predicate on the "interest_rate" field.
func InterestRateLTE(v float64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldInterestRate, v))
}

// AmortizationMethodEQ applies the EQ predicate on the "amortization_method" field.
func AmortizationMethodEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldAmortizationMethod, v))
}

// AmortizationMethodNEQ applies the NEQ predicate on the "amortization_method" field.
func AmortizationMethodNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldAmortizationMethod, v))
}

// AmortizationMethodIn applies the In predicate on the "amortization_method" field.
func AmortizationMethodIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldAmortizationMethod, vs...))
}

// AmortizationMethodNotIn applies the NotIn predicate on the "amortization_method" field.
func AmortizationMethodNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldAmortizationMethod, vs...))
}

// AmortizationMethodGT applies the GT predicate on the "amortization_method" field.
func AmortizationMethodGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldAmortizationMethod, v))
}

// AmortizationMethodGTE applies the GTE predicate on the "amortization_method" field.
func AmortizationMethodGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldAmortizationMethod, v))
}

// AmortizationMethodLT applies the LT predicate on the "amortization_method" field.
func AmortizationMethodLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldAmortizationMethod, v))
}

// AmortizationMethodLTE applies the LTE predicate on the "amortization_method" field.
func AmortizationMethodLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldAmortizationMethod, v))
}

// AmortizationMethodContains applies the Contains predicate on the "amortization_method" field.
func AmortizationMethodContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldAmortizationMethod, v))
}

// AmortizationMethodHasPrefix applies the HasPrefix predicate on the "amortization_method" field.
func AmortizationMethodHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldAmortizationMethod, v))
}

// AmortizationMethodHasSuffix applies the HasSuffix predicate on the "amortization_method" field.
func AmortizationMethodHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldAmortizationMethod, v))
}

// AmortizationMethodEqualFold applies the EqualFold predicate on the "amortization_method" field.
func AmortizationMethodEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldAmortizationMethod, v))
}

// AmortizationMethodContainsFold applies the ContainsFold predicate on the "amortization_method" field.
func AmortizationMethodContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldAmortizationMethod, v))
}

// CycleEQ applies the EQ predicate on the "cycle" field.
func CycleEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCycle, v))
}

// CycleNEQ applies the NEQ predicate on the "cycle" field.
func CycleNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldCycle, v))
}

// CycleIn applies the In predicate on the "cycle" field.
func CycleIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldCycle, vs...))
}

// CycleNotIn applies the NotIn predicate on the "cycle" field.
func CycleNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldCycle, vs...))
}

// CycleGT applies the GT predicate on the "cycle" field.
func CycleGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldCycle, v))
}

// CycleGTE applies the GTE predicate on the "cycle" field.
func CycleGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldCycle, v))
}

// CycleLT applies the LT predicate on the "cycle" field.
func CycleLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldCycle, v))
}

// CycleLTE applies the LTE predicate on the "cycle" field.
func CycleLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldCycle, v))
}

// CycleContains applies the Contains predicate on the "cycle" field.
func CycleContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldCycle, v))
}

// CycleHasPrefix applies the HasPrefix predicate on the "cycle" field.
func CycleHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldCycle, v))
}

// CycleHasSuffix applies the HasSuffix predicate on the "cycle" field.
func CycleHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldCycle, v))
}

// CycleEqualFold applies the EqualFold predicate on the "cycle" field.
func CycleEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldCycle, v))
}

// CycleContainsFold applies the ContainsFold predicate on the "cycle" field.
func CycleContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldCycle, v))
}

// IntervalEQ applies the EQ predicate on the "interval" field.
func IntervalEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldInterval, v))
}

// IntervalNEQ applies the NEQ predicate on the "interval" field.
func IntervalNEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldInterval, v))
}

// IntervalIn applies the In predicate on the "interval" field.
func IntervalIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldInterval, vs...))
}

// IntervalNotIn applies the NotIn predicate on the "interval" field.
func IntervalNotIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldInterval, vs...))
}

// IntervalGT applies the GT predicate on the "interval" field.
func IntervalGT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldInterval, v))
}

// IntervalGTE applies the GTE predicate on the "interval" field.
func IntervalGTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldInterval, v))
}

// IntervalLT applies the LT predicate on the "interval" field.
func IntervalLT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldInterval, v))
}

// IntervalLTE applies the LTE predicate on the "interval" field.
func IntervalLTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldInterval, v))
}

// IntervalIsNil applies the IsNil predicate on the "interval" field.
func IntervalIsNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIsNull(FieldInterval))
}

// IntervalNotNil applies the NotNil predicate on the "interval" field.
func IntervalNotNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotNull(FieldInterval))
}

// WeekdayMaskEQ applies the EQ predicate on the "weekday_mask" field.
func WeekdayMaskEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldWeekdayMask, v))
}

// WeekdayMaskNEQ applies the NEQ predicate on the "weekday_mask" field.
func WeekdayMaskNEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldWeekdayMask, v))
}

// WeekdayMaskIn applies the In predicate on the "weekday_mask" field.
func WeekdayMaskIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldWeekdayMask, vs...))
}

// WeekdayMaskNotIn applies the NotIn predicate on the "weekday_mask" field.
func WeekdayMaskNotIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldWeekdayMask, vs...))
}

// WeekdayMaskGT applies the GT predicate on the "weekday_mask" field.
func WeekdayMaskGT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldWeekdayMask, v))
}

// WeekdayMaskGTE applies the GTE predicate on the "weekday_mask" field.
func WeekdayMaskGTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldWeekdayMask, v))
}

// WeekdayMaskLT applies the LT predicate on the "weekday_mask" field.
func WeekdayMaskLT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldWeekdayMask, v))
}

// WeekdayMaskLTE applies the LTE predicate on the "weekday_mask" field.
func WeekdayMaskLTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldWeekdayMask, v))
}

// WeekdayMaskIsNil applies the IsNil predicate on the "weekday_mask" field.
func WeekdayMaskIsNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIsNull(FieldWeekdayMask))
}

// WeekdayMaskNotNil applies the NotNil predicate on the "weekday_mask" field.
func WeekdayMaskNotNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotNull(FieldWeekdayMask))
}

// MonthlyModeEQ applies the EQ predicate on the "monthly_mode" field.
func MonthlyModeEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldMonthlyMode, v))
}

// MonthlyModeNEQ applies the NEQ predicate on the "monthly_mode" field.
func MonthlyModeNEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldMonthlyMode, v))
}

// MonthlyModeIn applies the In predicate on the "monthly_mode" field.
func MonthlyModeIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldMonthlyMode, vs...))
}

// MonthlyModeNotIn applies the NotIn predicate on the "monthly_mode" field.
func MonthlyModeNotIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldMonthlyMode, vs...))
}

// MonthlyModeGT applies the GT predicate on the "monthly_mode" field.
func MonthlyModeGT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldMonthlyMode, v))
}

// MonthlyModeGTE applies the GTE predicate on the "monthly_mode" field.
func MonthlyModeGTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldMonthlyMode, v))
}

// MonthlyModeLT applies the LT predicate on the "monthly_mode" field.
func MonthlyModeLT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldMonthlyMode, v))
}

// MonthlyModeLTE applies the LTE predicate on the "monthly_mode" field.
func MonthlyModeLTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldMonthlyMode, v))
}

// MonthlyModeIsNil applies the IsNil predicate on the "monthly_mode" field.
func MonthlyModeIsNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIsNull(FieldMonthlyMode))
}

// MonthlyModeNotNil applies the NotNil predicate on the "monthly_mode" field.
func MonthlyModeNotNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotNull(FieldMonthlyMode))
}

// NthEQ applies the EQ predicate on the "nth" field.
func NthEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldNth, v))
}

// NthNEQ applies the NEQ predicate on the "nth" field.
func NthNEQ(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldNth, v))
}

// NthIn applies the In predicate on the "nth" field.
func NthIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldNth, vs...))
}

// NthNotIn applies the NotIn predicate on the "nth" field.
func NthNotIn(vs ...int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldNth, vs...))
}

// NthGT applies the GT predicate on the "nth" field.
func NthGT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldNth, v))
}

// NthGTE applies the GTE predicate on the "nth" field.
func NthGTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldNth, v))
}

// NthLT applies the LT predicate on the "nth" field.
func NthLT(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldNth, v))
}

// NthLTE applies the LTE predicate on the "nth" field.
func NthLTE(v int32) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldNth, v))
}

// NthIsNil applies the IsNil predicate on the "nth" field.
func NthIsNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIsNull(FieldNth))
}

// NthNotNil applies the NotNil predicate on the "nth" field.
func NthNotNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotNull(FieldNth))
}

// InterestWaivedCentsEQ applies the EQ predicate on the "interest_waived_cents" field.
func InterestWaivedCentsEQ(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldInterestWaivedCents, v))
}

// InterestWaivedCentsNEQ applies the NEQ predicate on the "interest_waived_cents" field.
func InterestWaivedCentsNEQ(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldInterestWaivedCents, v))
}

// InterestWaivedCentsIn applies the In predicate on the "interest_waived_cents" field.
func InterestWaivedCentsIn(vs ...int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldInterestWaivedCents, vs...))
}

// InterestWaivedCentsNotIn applies the NotIn predicate on the "interest_waived_cents" field.
func InterestWaivedCentsNotIn(vs ...int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldInterestWaivedCents, vs...))
}

// InterestWaivedCentsGT applies the GT predicate on the "interest_waived_cents" field.
func InterestWaivedCentsGT(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldInterestWaivedCents, v))
}

// InterestWaivedCentsGTE applies the GTE predicate on the "interest_waived_cents" field.
func InterestWaivedCentsGTE(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldInterestWaivedCents, v))
}

// InterestWaivedCentsLT applies the LT predicate on the "interest_waived_cents" field.
func InterestWaivedCentsLT(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldInterestWaivedCents, v))
}

// InterestWaivedCentsLTE applies the LTE predicate on the "interest_waived_cents" field.
func InterestWaivedCentsLTE(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldInterestWaivedCents, v))
}

// InterestWaivedCentsIsNil applies the IsNil predicate on the "interest_waived_cents" field.
func InterestWaivedCentsIsNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIsNull(FieldInterestWaivedCents))
}

// InterestWaivedCentsNotNil applies the NotNil predicate on the "interest_waived_cents" field.
func InterestWaivedCentsNotNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotNull(FieldInterestWaivedCents))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldStartDate, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldDueDate, v))
}

// TotalPrincipalCentsEQ applies the EQ predicate on the "total_principal_cents" field.
func TotalPrincipalCentsEQ(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldTotalPrincipalCents, v))
}

// TotalPrincipalCentsNEQ applies the NEQ predicate on the "total_principal_cents" field.
func TotalPrincipalCentsNEQ(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldTotalPrincipalCents, v))
}

// TotalPrincipalCentsIn applies the In predicate on the "total_principal_cents" field.
func TotalPrincipalCentsIn(vs ...int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldTotalPrincipalCents, vs...))
}

// TotalPrincipalCentsNotIn applies the NotIn predicate on the "total_principal_cents" field.
func TotalPrincipalCentsNotIn(vs ...int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldTotalPrincipalCents, vs...))
}

// TotalPrincipalCentsGT applies the GT predicate on the "total_principal_cents" field.
func TotalPrincipalCentsGT(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldTotalPrincipalCents, v))
}

// TotalPrincipalCentsGTE applies the GTE predicate on the "total_principal_cents" field.
func TotalPrincipalCentsGTE(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldTotalPrincipalCents, v))
}

// TotalPrincipalCentsLT applies the LT predicate on the "total_principal_cents" field.
func TotalPrincipalCentsLT(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldTotalPrincipalCents, v))
}

// TotalPrincipalCentsLTE applies the LTE predicate on the "total_principal_cents" field.
func TotalPrincipalCentsLTE(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldTotalPrincipalCents, v))
}

// DebtTypeEQ applies the EQ predicate on the "debt_type" field.
func DebtTypeEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldDebtType, v))
}

// DebtTypeNEQ applies the NEQ predicate on the "debt_type" field.
func DebtTypeNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldDebtType, v))
}

// DebtTypeIn applies the In predicate on the "debt_type" field.
func DebtTypeIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldDebtType, vs...))
}

// DebtTypeNotIn applies the NotIn predicate on the "debt_type" field.
func DebtTypeNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldDebtType, vs...))
}

// DebtTypeGT applies the GT predicate on the "debt_type" field.
func DebtTypeGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldDebtType, v))
}

// DebtTypeGTE applies the GTE predicate on the "debt_type" field.
func DebtTypeGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldDebtType, v))
}

// DebtTypeLT applies the LT predicate on the "debt_type" field.
func DebtTypeLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldDebtType, v))
}

// DebtTypeLTE applies the LTE predicate on the "debt_type" field.
func DebtTypeLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldDebtType, v))
}

// DebtTypeContains applies the Contains predicate on the "debt_type" field.
func DebtTypeContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldDebtType, v))
}

// DebtTypeHasPrefix applies the HasPrefix predicate on the "debt_type" field.
func DebtTypeHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldDebtType, v))
}

// DebtTypeHasSuffix applies the HasSuffix predicate on the "debt_type" field.
func DebtTypeHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldDebtType, v))
}

// DebtTypeEqualFold applies the EqualFold predicate on the "debt_type" field.
func DebtTypeEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldDebtType, v))
}

// DebtTypeContainsFold applies the ContainsFold predicate on the "debt_type" field.
func DebtTypeContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldDebtType, v))
}

// SubtypeEQ applies the EQ predicate on the "subtype" field.
func SubtypeEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldSubtype, v))
}

// SubtypeNEQ applies the NEQ predicate on the "subtype" field.
func SubtypeNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldSubtype, v))
}

// SubtypeIn applies the In predicate on the "subtype" field.
func SubtypeIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldSubtype, vs...))
}

// SubtypeNotIn applies the NotIn predicate on the "subtype" field.
func SubtypeNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldSubtype, vs...))
}

// SubtypeGT applies the GT predicate on the "subtype" field.
func SubtypeGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldSubtype, v))
}

// SubtypeGTE applies the GTE predicate on the "subtype" field.
func SubtypeGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldSubtype, v))
}

// SubtypeLT applies the LT predicate on the "subtype" field.
func SubtypeLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldSubtype, v))
}

// SubtypeLTE applies the LTE predicate on the "subtype" field.
func SubtypeLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldSubtype, v))
}

// SubtypeContains applies the Contains predicate on the "subtype" field.
func SubtypeContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldSubtype, v))
}

// SubtypeHasPrefix applies the HasPrefix predicate on the "subtype" field.
func SubtypeHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldSubtype, v))
}

// SubtypeHasSuffix applies the HasSuffix predicate on the "subtype" field.
func SubtypeHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldSubtype, v))
}

// SubtypeEqualFold applies the EqualFold predicate on the "subtype" field.
func SubtypeEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldSubtype, v))
}

// SubtypeContainsFold applies the ContainsFold predicate on the "subtype" field.
func SubtypeContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldSubtype, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldVersion, v))
}

// ContactEQ applies the EQ predicate on the "contact" field.
func ContactEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldContact, v))
}

// ContactNEQ applies the NEQ predicate on the "contact" field.
func ContactNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldContact, v))
}

// ContactIn applies the In predicate on the "contact" field.
func ContactIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldContact, vs...))
}

// ContactNotIn applies the NotIn predicate on the "contact" field.
func ContactNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldContact, vs...))
}

// ContactGT applies the GT predicate on the "contact" field.
func ContactGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldContact, v))
}

// ContactGTE applies the GTE predicate on the "contact" field.
func ContactGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldContact, v))
}

// ContactLT applies the LT predicate on the "contact" field.
func ContactLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldContact, v))
}

// ContactLTE applies the LTE predicate on the "contact" field.
func ContactLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldContact, v))
}

// ContactContains applies the Contains predicate on the "contact" field.
func ContactContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldContact, v))
}

// ContactHasPrefix applies the HasPrefix predicate on the "contact" field.
func ContactHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldContact, v))
}

// ContactHasSuffix applies the HasSuffix predicate on the "contact" field.
func ContactHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldContact, v))
}

// ContactEqualFold applies the EqualFold predicate on the "contact" field.
func ContactEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldContact, v))
}

// ContactContainsFold applies the ContainsFold predicate on the "contact" field.
func ContactContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldContact, v))
}

// ContractRefEQ applies the EQ predicate on the "contract_ref" field.
func ContractRefEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldContractRef, v))
}

// ContractRefNEQ applies the NEQ predicate on the "contract_ref" field.
func ContractRefNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldContractRef, v))
}

// ContractRefIn applies the In predicate on the "contract_ref" field.
func ContractRefIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldContractRef, vs...))
}

// ContractRefNotIn applies the NotIn predicate on the "contract_ref" field.
func ContractRefNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldContractRef, vs...))
}

// ContractRefGT applies the GT predicate on the "contract_ref" field.
func ContractRefGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldContractRef, v))
}

// ContractRefGTE applies the GTE predicate on the "contract_ref" field.
func ContractRefGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldContractRef, v))
}

// ContractRefLT applies the LT predicate on the "contract_ref" field.
func ContractRefLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldContractRef, v))
}

// ContractRefLTE applies the LTE predicate on the "contract_ref" field.
func ContractRefLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldContractRef, v))
}

// ContractRefContains applies the Contains predicate on the "contract_ref" field.
func ContractRefContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldContractRef, v))
}

// ContractRefHasPrefix applies the HasPrefix predicate on the "contract_ref" field.
func ContractRefHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldContractRef, v))
}

// ContractRefHasSuffix applies the HasSuffix predicate on the "contract_ref" field.
func ContractRefHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldContractRef, v))
}

// ContractRefEqualFold applies the EqualFold predicate on the "contract_ref" field.
func ContractRefEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldContractRef, v))
}

// ContractRefContainsFold applies the ContainsFold predicate on the "contract_ref" field.
func ContractRefContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldContractRef, v))
}

// CollectionAccountIDEQ applies the EQ predicate on the "collection_account_id" field.
func CollectionAccountIDEQ(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCollectionAccountID, v))
}

// CollectionAccountIDNEQ applies the NEQ predicate on the "collection_account_id" field.
func CollectionAccountIDNEQ(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldCollectionAccountID, v))
}

// CollectionAccountIDIn applies the In predicate on the "collection_account_id" field.
func CollectionAccountIDIn(vs ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldCollectionAccountID, vs...))
}

// CollectionAccountIDNotIn applies the NotIn predicate on the "collection_account_id" field.
func CollectionAccountIDNotIn(vs ...uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldCollectionAccountID, vs...))
}

// CollectionAccountIDGT applies the GT predicate on the "collection_account_id" field.
func CollectionAccountIDGT(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldCollectionAccountID, v))
}

// CollectionAccountIDGTE applies the GTE predicate on the "collection_account_id" field.
func CollectionAccountIDGTE(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldCollectionAccountID, v))
}

// CollectionAccountIDLT applies the LT predicate on the "collection_account_id" field.
func CollectionAccountIDLT(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldCollectionAccountID, v))
}

// CollectionAccountIDLTE applies the LTE predicate on the "collection_account_id" field.
func CollectionAccountIDLTE(v uuid.UUID) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldCollectionAccountID, v))
}

// CollectionAccountIDIsNil applies the IsNil predicate on the "collection_account_id" field.
func CollectionAccountIDIsNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIsNull(FieldCollectionAccountID))
}

// CollectionAccountIDNotNil applies the NotNil predicate on the "collection_account_id" field.
func CollectionAccountIDNotNil() predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotNull(FieldCollectionAccountID))
}

// GuarantorNameEQ applies the EQ predicate on the "guarantor_name" field.
func GuarantorNameEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldGuarantorName, v))
}

// GuarantorNameNEQ applies the NEQ predicate on the "guarantor_name" field.
func GuarantorNameNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldGuarantorName, v))
}

// GuarantorNameIn applies the In predicate on the "guarantor_name" field.
func GuarantorNameIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldGuarantorName, vs...))
}

// GuarantorNameNotIn applies the NotIn predicate on the "guarantor_name" field.
func GuarantorNameNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldGuarantorName, vs...))
}

// GuarantorNameGT applies the GT predicate on the "guarantor_name" field.
func GuarantorNameGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldGuarantorName, v))
}

// GuarantorNameGTE applies the GTE predicate on the "guarantor_name" field.
func GuarantorNameGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldGuarantorName, v))
}

// GuarantorNameLT applies the LT predicate on the "guarantor_name" field.
func GuarantorNameLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldGuarantorName, v))
}

// GuarantorNameLTE applies the LTE predicate on the "guarantor_name" field.
func GuarantorNameLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldGuarantorName, v))
}

// GuarantorNameContains applies the Contains predicate on the "guarantor_name" field.
func GuarantorNameContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldGuarantorName, v))
}

// GuarantorNameHasPrefix applies the HasPrefix predicate on the "guarantor_name" field.
func GuarantorNameHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldGuarantorName, v))
}

// GuarantorNameHasSuffix applies the HasSuffix predicate on the "guarantor_name" field.
func GuarantorNameHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldGuarantorName, v))
}

// GuarantorNameEqualFold applies the EqualFold predicate on the "guarantor_name" field.
func GuarantorNameEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldGuarantorName, v))
}

// GuarantorNameContainsFold applies the ContainsFold predicate on the "guarantor_name" field.
func GuarantorNameContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldGuarantorName, v))
}

// GuarantorContactEQ applies the EQ predicate on the "guarantor_contact" field.
func GuarantorContactEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldGuarantorContact, v))
}

// GuarantorContactNEQ applies the NEQ predicate on the "guarantor_contact" field.
func GuarantorContactNEQ(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldGuarantorContact, v))
}

// GuarantorContactIn applies the In predicate on the "guarantor_contact" field.
func GuarantorContactIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldGuarantorContact, vs...))
}

// GuarantorContactNotIn applies the NotIn predicate on the "guarantor_contact" field.
func GuarantorContactNotIn(vs ...string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldGuarantorContact, vs...))
}

// GuarantorContactGT applies the GT predicate on the "guarantor_contact" field.
func GuarantorContactGT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldGuarantorContact, v))
}

// GuarantorContactGTE applies the GTE predicate on the "guarantor_contact" field.
func GuarantorContactGTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldGuarantorContact, v))
}

// GuarantorContactLT applies the LT predicate on the "guarantor_contact" field.
func GuarantorContactLT(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldGuarantorContact, v))
}

// GuarantorContactLTE applies the LTE predicate on the "guarantor_contact" field.
func GuarantorContactLTE(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldGuarantorContact, v))
}

// GuarantorContactContains applies the Contains predicate on the "guarantor_contact" field.
func GuarantorContactContains(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContains(FieldGuarantorContact, v))
}

// GuarantorContactHasPrefix applies the HasPrefix predicate on the "guarantor_contact" field.
func GuarantorContactHasPrefix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasPrefix(FieldGuarantorContact, v))
}

// GuarantorContactHasSuffix applies the HasSuffix predicate on the "guarantor_contact" field.
func GuarantorContactHasSuffix(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldHasSuffix(FieldGuarantorContact, v))
}

// GuarantorContactEqualFold applies the EqualFold predicate on the "guarantor_contact" field.
func GuarantorContactEqualFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEqualFold(FieldGuarantorContact, v))
}

// GuarantorContactContainsFold applies the ContainsFold predicate on the "guarantor_contact" field.
func GuarantorContactContainsFold(v string) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldContainsFold(FieldGuarantorContact, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DebtDetails {
	return predicate.DebtDetails(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSchedule applies the HasEdge predicate on the "schedule" edge.
func HasSchedule() predicate.DebtDetails {
	return predicate.DebtDetails(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ScheduleTable, ScheduleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScheduleWith applies the HasEdge predicate on the "schedule" edge with a given conditions (other predicates).
func HasScheduleWith(preds ...predicate.PaymentSchedule) predicate.DebtDetails {
	return predicate.DebtDetails(func(s *sql.Selector) {
		step := newScheduleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProgressSnapshots applies the HasEdge predicate on the "progress_snapshots" edge.
func HasProgressSnapshots() predicate.DebtDetails {
	return predicate.DebtDetails(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProgressSnapshotsTable, ProgressSnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProgressSnapshotsWith applies the HasEdge predicate on the "progress_snapshots" edge with a given conditions (other predicates).
func HasProgressSnapshotsWith(preds ...predicate.DebtProgressSnapshot) predicate.DebtDetails {
	return predicate.DebtDetails(func(s *sql.Selector) {
		step := newProgressSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DebtDetails) predicate.DebtDetails {
	return predicate.DebtDetails(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DebtDetails) predicate.DebtDetails {
	return predicate.DebtDetails(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DebtDetails) predicate.DebtDetails {
	return predicate.DebtDetails(sql.NotPredicates(p))
}
