// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire ./wire/
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/yucai/server/pkg/config"
)

// InitializeApp creates the application with all dependencies wired.
func InitializeApp(cfg *config.Config) (*App, error) {
	log := provideLogger(cfg)
	rdb := provideRedisClient(cfg)
	client, err := provideEntClient(cfg)
	if err != nil {
		return nil, err
	}
	ts := provideTokenService(cfg)
	tenantRepo := provideTenantRepo(client)
	userRepo := provideUserRepo(client)
	sessionStore := provideSessionStore(rdb)
	registerHandler := provideRegisterHandler(tenantRepo, userRepo, ts)
	loginHandler := provideLoginHandler(userRepo, ts)
	refreshHandler := provideRefreshHandler(userRepo, ts, sessionStore)
	profileHandler := provideProfileHandler(userRepo)
	authService := provideAuthService(tenantRepo, userRepo, ts, registerHandler, loginHandler, refreshHandler, profileHandler)
	authHandler := provideAuthHandler(authService)
	grpcSrv := provideGRPCServer(ts)
	app := NewApp(cfg, log, grpcSrv, authHandler)
	return app, nil
}
